package com.manage.wiresysrecord.model;

import com.manage.wiresysrecord.model.original.AbstractWireSysRecord;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class WireSysRecord extends AbstractWireSysRecord {

}
