package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractANotsecretpcoutTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractANotsecretpcoutTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String deptname;
	private Integer deptid;
	private String borrower;
	private Integer borrowerid;
	private String outplace;
	private String devicenum;
	private String diskfrom;
	private String mediumnum;
	private Integer issecret;
	private String borrowreason;
	private String borrowersign;
	private Date borrowersigndate;
	private String deptleaderopinion;
	private String deptleadersign;
	private Integer deptleaderid;
	private Date leadersigndate;
	private String devtransfer;
	private String receivesign;
	private Date receivesigndate;
	private String returncondition;
	private String checkersign;
	private Integer checkerid;
	private Date checkersigndate;
	private String devmanager;
	private Integer devmanagerid;
	private Date devmansigndate;
	private String securityopinion;
	private String securitysign;
	private Integer securityid;
	private Date securitysigndate;

	// Constructors

	/** default constructor */
	public AbstractANotsecretpcoutTab() {
	}

	/** minimal constructor */
	public AbstractANotsecretpcoutTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractANotsecretpcoutTab(Integer id, Integer version,
			String deptname, Integer deptid, String borrower,
			Integer borrowerid, String outplace, String devicenum,
			String diskfrom, String mediumnum, Integer issecret,
			String borrowreason, String borrowersign, Date borrowersigndate,
			String deptleaderopinion, String deptleadersign,
			Integer deptleaderid, Date leadersigndate, String devtransfer,
			String receivesign, Date receivesigndate, String returncondition,
			String checkersign, Integer checkerid, Date checkersigndate,
			String devmanager, Integer devmanagerid, Date devmansigndate,
			String securityopinion, String securitysign, Integer securityid,
			Date securitysigndate) {
		this.id = id;
		this.version = version;
		this.deptname = deptname;
		this.deptid = deptid;
		this.borrower = borrower;
		this.borrowerid = borrowerid;
		this.outplace = outplace;
		this.devicenum = devicenum;
		this.diskfrom = diskfrom;
		this.mediumnum = mediumnum;
		this.issecret = issecret;
		this.borrowreason = borrowreason;
		this.borrowersign = borrowersign;
		this.borrowersigndate = borrowersigndate;
		this.deptleaderopinion = deptleaderopinion;
		this.deptleadersign = deptleadersign;
		this.deptleaderid = deptleaderid;
		this.leadersigndate = leadersigndate;
		this.devtransfer = devtransfer;
		this.receivesign = receivesign;
		this.receivesigndate = receivesigndate;
		this.returncondition = returncondition;
		this.checkersign = checkersign;
		this.checkerid = checkerid;
		this.checkersigndate = checkersigndate;
		this.devmanager = devmanager;
		this.devmanagerid = devmanagerid;
		this.devmansigndate = devmansigndate;
		this.securityopinion = securityopinion;
		this.securitysign = securitysign;
		this.securityid = securityid;
		this.securitysigndate = securitysigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public String getBorrower() {
		return this.borrower;
	}

	public void setBorrower(String borrower) {
		this.borrower = borrower;
	}

	public Integer getBorrowerid() {
		return this.borrowerid;
	}

	public void setBorrowerid(Integer borrowerid) {
		this.borrowerid = borrowerid;
	}

	public String getOutplace() {
		return this.outplace;
	}

	public void setOutplace(String outplace) {
		this.outplace = outplace;
	}

	public String getDevicenum() {
		return this.devicenum;
	}

	public void setDevicenum(String devicenum) {
		this.devicenum = devicenum;
	}

	public String getDiskfrom() {
		return this.diskfrom;
	}

	public void setDiskfrom(String diskfrom) {
		this.diskfrom = diskfrom;
	}

	public String getMediumnum() {
		return this.mediumnum;
	}

	public void setMediumnum(String mediumnum) {
		this.mediumnum = mediumnum;
	}

	public Integer getIssecret() {
		return this.issecret;
	}

	public void setIssecret(Integer issecret) {
		this.issecret = issecret;
	}

	public String getBorrowreason() {
		return this.borrowreason;
	}

	public void setBorrowreason(String borrowreason) {
		this.borrowreason = borrowreason;
	}

	public String getBorrowersign() {
		return this.borrowersign;
	}

	public void setBorrowersign(String borrowersign) {
		this.borrowersign = borrowersign;
	}

	public Date getBorrowersigndate() {
		return this.borrowersigndate;
	}

	public void setBorrowersigndate(Date borrowersigndate) {
		this.borrowersigndate = borrowersigndate;
	}

	public String getDeptleaderopinion() {
		return this.deptleaderopinion;
	}

	public void setDeptleaderopinion(String deptleaderopinion) {
		this.deptleaderopinion = deptleaderopinion;
	}

	public String getDeptleadersign() {
		return this.deptleadersign;
	}

	public void setDeptleadersign(String deptleadersign) {
		this.deptleadersign = deptleadersign;
	}

	public Integer getDeptleaderid() {
		return this.deptleaderid;
	}

	public void setDeptleaderid(Integer deptleaderid) {
		this.deptleaderid = deptleaderid;
	}

	public Date getLeadersigndate() {
		return this.leadersigndate;
	}

	public void setLeadersigndate(Date leadersigndate) {
		this.leadersigndate = leadersigndate;
	}

	public String getDevtransfer() {
		return this.devtransfer;
	}

	public void setDevtransfer(String devtransfer) {
		this.devtransfer = devtransfer;
	}

	public String getReceivesign() {
		return this.receivesign;
	}

	public void setReceivesign(String receivesign) {
		this.receivesign = receivesign;
	}

	public Date getReceivesigndate() {
		return this.receivesigndate;
	}

	public void setReceivesigndate(Date receivesigndate) {
		this.receivesigndate = receivesigndate;
	}

	public String getReturncondition() {
		return this.returncondition;
	}

	public void setReturncondition(String returncondition) {
		this.returncondition = returncondition;
	}

	public String getCheckersign() {
		return this.checkersign;
	}

	public void setCheckersign(String checkersign) {
		this.checkersign = checkersign;
	}

	public Integer getCheckerid() {
		return this.checkerid;
	}

	public void setCheckerid(Integer checkerid) {
		this.checkerid = checkerid;
	}

	public Date getCheckersigndate() {
		return this.checkersigndate;
	}

	public void setCheckersigndate(Date checkersigndate) {
		this.checkersigndate = checkersigndate;
	}

	public String getDevmanager() {
		return this.devmanager;
	}

	public void setDevmanager(String devmanager) {
		this.devmanager = devmanager;
	}

	public Integer getDevmanagerid() {
		return this.devmanagerid;
	}

	public void setDevmanagerid(Integer devmanagerid) {
		this.devmanagerid = devmanagerid;
	}

	public Date getDevmansigndate() {
		return this.devmansigndate;
	}

	public void setDevmansigndate(Date devmansigndate) {
		this.devmansigndate = devmansigndate;
	}

	public String getSecurityopinion() {
		return this.securityopinion;
	}

	public void setSecurityopinion(String securityopinion) {
		this.securityopinion = securityopinion;
	}

	public String getSecuritysign() {
		return this.securitysign;
	}

	public void setSecuritysign(String securitysign) {
		this.securitysign = securitysign;
	}

	public Integer getSecurityid() {
		return this.securityid;
	}

	public void setSecurityid(Integer securityid) {
		this.securityid = securityid;
	}

	public Date getSecuritysigndate() {
		return this.securitysigndate;
	}

	public void setSecuritysigndate(Date securitysigndate) {
		this.securitysigndate = securitysigndate;
	}

}