package com.manage.secexamregist.model.original;

import java.util.Date;

/**
 * AbstractSSecexamregistTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSSecexamregistTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String pname;
	private String orgname;
	private String orgid;
	private String recontent;
	private Integer isclassification;
	private String classification;
	private String fullname;
	private String depdesc;
	private String depsign;
	private Integer depid;
	private Date depdate;
	private String officedesc;
	private String officesign;
	private Integer officeid;
	private Date officedate;
	private String expertsdesc;
	private String scomdesc;
	private String scomsign;
	private Integer scomid;
	private Date scomdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSSecexamregistTab() {
	}

	/** minimal constructor */
	public AbstractSSecexamregistTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSSecexamregistTab(Integer id, Integer version, String pname,
			String orgname, String orgid, String recontent,
			Integer isclassification, String classification, String fullname,
			String depdesc, String depsign, Integer depid, Date depdate,
			String officedesc, String officesign, Integer officeid,
			Date officedate, String expertsdesc, String scomdesc,
			String scomsign, Integer scomid, Date scomdate,String username,Integer userid) {
		this.id = id;
		this.version = version;
		this.pname = pname;
		this.orgname = orgname;
		this.orgid = orgid;
		this.recontent = recontent;
		this.isclassification = isclassification;
		this.classification = classification;
		this.fullname = fullname;
		this.depdesc = depdesc;
		this.depsign = depsign;
		this.depid = depid;
		this.depdate = depdate;
		this.officedesc = officedesc;
		this.officesign = officesign;
		this.officeid = officeid;
		this.officedate = officedate;
		this.expertsdesc = expertsdesc;
		this.scomdesc = scomdesc;
		this.scomsign = scomsign;
		this.scomid = scomid;
		this.scomdate = scomdate;
		this.username = username;
		this.userid = userid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getRecontent() {
		return this.recontent;
	}

	public void setRecontent(String recontent) {
		this.recontent = recontent;
	}

	public Integer getIsclassification() {
		return this.isclassification;
	}

	public void setIsclassification(Integer isclassification) {
		this.isclassification = isclassification;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getDepdesc() {
		return this.depdesc;
	}

	public void setDepdesc(String depdesc) {
		this.depdesc = depdesc;
	}

	public String getDepsign() {
		return this.depsign;
	}

	public void setDepsign(String depsign) {
		this.depsign = depsign;
	}

	public Integer getDepid() {
		return this.depid;
	}

	public void setDepid(Integer depid) {
		this.depid = depid;
	}

	public Date getDepdate() {
		return this.depdate;
	}

	public void setDepdate(Date depdate) {
		this.depdate = depdate;
	}

	public String getOfficedesc() {
		return this.officedesc;
	}

	public void setOfficedesc(String officedesc) {
		this.officedesc = officedesc;
	}

	public String getOfficesign() {
		return this.officesign;
	}

	public void setOfficesign(String officesign) {
		this.officesign = officesign;
	}

	public Integer getOfficeid() {
		return this.officeid;
	}

	public void setOfficeid(Integer officeid) {
		this.officeid = officeid;
	}

	public Date getOfficedate() {
		return this.officedate;
	}

	public void setOfficedate(Date officedate) {
		this.officedate = officedate;
	}

	public String getExpertsdesc() {
		return this.expertsdesc;
	}

	public void setExpertsdesc(String expertsdesc) {
		this.expertsdesc = expertsdesc;
	}

	public String getScomdesc() {
		return this.scomdesc;
	}

	public void setScomdesc(String scomdesc) {
		this.scomdesc = scomdesc;
	}

	public String getScomsign() {
		return this.scomsign;
	}

	public void setScomsign(String scomsign) {
		this.scomsign = scomsign;
	}

	public Integer getScomid() {
		return this.scomid;
	}

	public void setScomid(Integer scomid) {
		this.scomid = scomid;
	}

	public Date getScomdate() {
		return this.scomdate;
	}

	public void setScomdate(Date scomdate) {
		this.scomdate = scomdate;
	}

}