package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAAppsysalterTab;

/**
 * AAppsysalterTab generated by MyEclipse Persistence Tools
 */
public class AAppsysalterTab extends AbstractAAppsysalterTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AAppsysalterTab() {
	}

	/** minimal constructor */
	public AAppsysalterTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AAppsysalterTab(Integer id, Integer version, String sysname,
			String applydept, Integer applydeptid, String applicant,
			Integer applicantid, Date appliydate, String sysalterreason,
			String altercontent, String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String infordeptopinion, String infordeptsign,
			Integer infordeptsignid, Date infordeptsigndate,
			String operateresult, String sysmanager, Integer sysmanagerid,
			Date managersigndate) {
		super(id, version, sysname, applydept, applydeptid, applicant,
				applicantid, appliydate, sysalterreason, altercontent,
				applydeptopinion, applydeptsign, applydeptsignid,
				applydeptsigndate, infordeptopinion, infordeptsign,
				infordeptsignid, infordeptsigndate, operateresult, sysmanager,
				sysmanagerid, managersigndate);
	}

}
