package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSForeignersvisitTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSForeignersvisitTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String orgname;
	private String orgid;
	private String shead;
	private String purpose;
	private String personarea;
	private String location;
	private Date vdate;
	private Integer isshoot;
	private String confidentiality;
	private String depdesc;
	private String depsign;
	private Integer depid;
	private Date depdate;
	private String officedesc;
	private String officesign;
	private Integer officeid;
	private Date officedate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSForeignersvisitTab() {
	}

	/** minimal constructor */
	public AbstractSForeignersvisitTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSForeignersvisitTab(Integer id, Integer version,
			String orgname, String orgid, String shead, String purpose,
			String personarea, String location, Date vdate, Integer isshoot,
			String confidentiality, String depdesc, String depsign,
			Integer depid, Date depdate, String officedesc, String officesign,
			Integer officeid, Date officedate) {
		this.id = id;
		this.version = version;
		this.orgname = orgname;
		this.orgid = orgid;
		this.shead = shead;
		this.purpose = purpose;
		this.personarea = personarea;
		this.location = location;
		this.vdate = vdate;
		this.isshoot = isshoot;
		this.confidentiality = confidentiality;
		this.depdesc = depdesc;
		this.depsign = depsign;
		this.depid = depid;
		this.depdate = depdate;
		this.officedesc = officedesc;
		this.officesign = officesign;
		this.officeid = officeid;
		this.officedate = officedate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getShead() {
		return this.shead;
	}

	public void setShead(String shead) {
		this.shead = shead;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getPersonarea() {
		return this.personarea;
	}

	public void setPersonarea(String personarea) {
		this.personarea = personarea;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getVdate() {
		return this.vdate;
	}

	public void setVdate(Date vdate) {
		this.vdate = vdate;
	}

	public Integer getIsshoot() {
		return this.isshoot;
	}

	public void setIsshoot(Integer isshoot) {
		this.isshoot = isshoot;
	}

	public String getConfidentiality() {
		return this.confidentiality;
	}

	public void setConfidentiality(String confidentiality) {
		this.confidentiality = confidentiality;
	}

	public String getDepdesc() {
		return this.depdesc;
	}

	public void setDepdesc(String depdesc) {
		this.depdesc = depdesc;
	}

	public String getDepsign() {
		return this.depsign;
	}

	public void setDepsign(String depsign) {
		this.depsign = depsign;
	}

	public Integer getDepid() {
		return this.depid;
	}

	public void setDepid(Integer depid) {
		this.depid = depid;
	}

	public Date getDepdate() {
		return this.depdate;
	}

	public void setDepdate(Date depdate) {
		this.depdate = depdate;
	}

	public String getOfficedesc() {
		return this.officedesc;
	}

	public void setOfficedesc(String officedesc) {
		this.officedesc = officedesc;
	}

	public String getOfficesign() {
		return this.officesign;
	}

	public void setOfficesign(String officesign) {
		this.officesign = officesign;
	}

	public Integer getOfficeid() {
		return this.officeid;
	}

	public void setOfficeid(Integer officeid) {
		this.officeid = officeid;
	}

	public Date getOfficedate() {
		return this.officedate;
	}

	public void setOfficedate(Date officedate) {
		this.officedate = officedate;
	}

}