package com.manage.changemedium.model.original;

import java.util.Date;

/**
 * AbstractSChangemediumTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSChangemediumTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String orgname;
	private String orgid;
	private String code;
	private String departdesc;
	private Date departdate;
	private String officedesc;
	private Date officedate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSChangemediumTab() {
	}

	/** minimal constructor */
	public AbstractSChangemediumTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSChangemediumTab(Integer id, Integer version,
			String orgname, String orgid, String code,String departdesc, Date departdate, String officedesc,
			Date officedate,String username,Integer userid) {
		this.id = id;
		this.version = version;
		this.orgname = orgname;
		this.orgid = orgid;
		this.code = code;
		this.departdesc = departdesc;
		this.departdate = departdate;
		this.officedesc = officedesc;
		this.officedate = officedate;
		this.username = username;
		this.userid = userid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}



	public String getDepartdesc() {
		return departdesc;
	}

	public void setDepartdesc(String departdesc) {
		this.departdesc = departdesc;
	}

	public Date getDepartdate() {
		return departdate;
	}

	public void setDepartdate(Date departdate) {
		this.departdate = departdate;
	}

	public String getOfficedesc() {
		return this.officedesc;
	}

	public void setOfficedesc(String officedesc) {
		this.officedesc = officedesc;
	}

	public Date getOfficedate() {
		return this.officedate;
	}

	public void setOfficedate(Date officedate) {
		this.officedate = officedate;
	}

}