package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSPromiseTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSPromiseTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String pname;
	private Integer pid;
	private Date pdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSPromiseTab() {
	}

	/** minimal constructor */
	public AbstractSPromiseTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSPromiseTab(Integer id, Integer version, String pname,
			Integer pid, Date pdate) {
		this.id = id;
		this.version = version;
		this.pname = pname;
		this.pid = pid;
		this.pdate = pdate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Date getPdate() {
		return this.pdate;
	}

	public void setPdate(Date pdate) {
		this.pdate = pdate;
	}

}