package com.manage.borrowmedium.model.original;

import java.util.Date;

/**
 * AbstractSBorrowmediumTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSBorrowmediumTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Date borrowdate;
	private Integer mediumtype;
	private Integer mclassified;
	private String scode;
	private String devicecode;
	private Integer dclassified;
	private String ulimite;
	private String usesign;
	private Integer uid;
	private Date receivedate;
	private String checkdesc;
	private String cname;
	private Integer cid;
	private String username;
	private Integer userid;
	private String mark;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSBorrowmediumTab() {
	}

	/** minimal constructor */
	public AbstractSBorrowmediumTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSBorrowmediumTab(Integer id, Integer version,
			Date borrowdate, Integer mediumtype, Integer mclassified,
			String scode, String devicecode, Integer dclassified,
			String ulimite, String usesign, Integer uid, Date receivedate,
			String checkdesc, String cname, Integer cid,String username,Integer userid,String mark) {
		this.id = id;
		this.version = version;
		this.borrowdate = borrowdate;
		this.mediumtype = mediumtype;
		this.mclassified = mclassified;
		this.scode = scode;
		this.devicecode = devicecode;
		this.dclassified = dclassified;
		this.ulimite = ulimite;
		this.usesign = usesign;
		this.uid = uid;
		this.receivedate = receivedate;
		this.checkdesc = checkdesc;
		this.cname = cname;
		this.cid = cid;
		this.username = username;
		this.userid = userid;
		this.mark = mark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Date getBorrowdate() {
		return this.borrowdate;
	}

	public void setBorrowdate(Date borrowdate) {
		this.borrowdate = borrowdate;
	}

	public Integer getMediumtype() {
		return this.mediumtype;
	}

	public void setMediumtype(Integer mediumtype) {
		this.mediumtype = mediumtype;
	}

	

	public String getScode() {
		return this.scode;
	}

	public void setScode(String scode) {
		this.scode = scode;
	}

	public String getDevicecode() {
		return this.devicecode;
	}

	public void setDevicecode(String devicecode) {
		this.devicecode = devicecode;
	}

	

	public Integer getMclassified() {
		return mclassified;
	}

	public void setMclassified(Integer mclassified) {
		this.mclassified = mclassified;
	}

	public Integer getDclassified() {
		return dclassified;
	}

	public void setDclassified(Integer dclassified) {
		this.dclassified = dclassified;
	}

	public String getUlimite() {
		return ulimite;
	}

	public void setUlimite(String ulimite) {
		this.ulimite = ulimite;
	}

	public String getUsesign() {
		return this.usesign;
	}

	public void setUsesign(String usesign) {
		this.usesign = usesign;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Date getReceivedate() {
		return this.receivedate;
	}

	public void setReceivedate(Date receivedate) {
		this.receivedate = receivedate;
	}

	public String getCheckdesc() {
		return this.checkdesc;
	}

	public void setCheckdesc(String checkdesc) {
		this.checkdesc = checkdesc;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

}