package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSMeetsecrecyTab;

/**
 * SMeetsecrecyTab generated by MyEclipse Persistence Tools
 */
public class SMeetsecrecyTab extends AbstractSMeetsecrecyTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SMeetsecrecyTab() {
	}

	/** minimal constructor */
	public SMeetsecrecyTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SMeetsecrecyTab(Integer id, Integer version, String meetname,
			String orgid, String orgname, Date meetdate, String classification,
			String meetplace, String bmname, String meetcontent,
			String cborgopinion, String cbleader, Date cbleaderdate,
			Integer cbleaderid, String sofficedesc, String sofficesign,
			Integer sofficeid, Date sofficedate, String yleaderopinion,
			String yleader, Integer yleaderid, Date yleaderdate) {
		super(id, version, meetname, orgid, orgname, meetdate, classification,
				meetplace, bmname, meetcontent, cborgopinion, cbleader,
				cbleaderdate, cbleaderid, sofficedesc, sofficesign, sofficeid,
				sofficedate, yleaderopinion, yleader, yleaderid, yleaderdate);
	}

}
