package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAInternetaccountTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAInternetaccountTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String applicant;
	private Integer applicantid;
	private String deptname;
	private Integer deptid;
	private String userlist;
	private String linkman;
	private String cellphone;
	private String openreason;
	private String revokereason;
	private String applydeptopinion;
	private String applydeptsign;
	private Integer applydeptsignid;
	private Date applydeptsigndate;
	private String dutyofficer;
	private Integer dutyofficerid;
	private Date dutyofficerdate;
	private Integer isfinish;
	private String operatrecord;
	private String recorder;
	private Integer recorderid;
	private Date recorddate;

	// Constructors

	/** default constructor */
	public AbstractAInternetaccountTab() {
	}

	/** minimal constructor */
	public AbstractAInternetaccountTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAInternetaccountTab(Integer id, Integer version,
			String applicant, Integer applicantid, String deptname,
			Integer deptid, String userlist, String linkman, String cellphone,
			String openreason, String revokereason, String applydeptopinion,
			String applydeptsign, Integer applydeptsignid,
			Date applydeptsigndate, String dutyofficer, Integer dutyofficerid,
			Date dutyofficerdate, Integer isfinish, String operatrecord,
			String recorder, Integer recorderid, Date recorddate) {
		this.id = id;
		this.version = version;
		this.applicant = applicant;
		this.applicantid = applicantid;
		this.deptname = deptname;
		this.deptid = deptid;
		this.userlist = userlist;
		this.linkman = linkman;
		this.cellphone = cellphone;
		this.openreason = openreason;
		this.revokereason = revokereason;
		this.applydeptopinion = applydeptopinion;
		this.applydeptsign = applydeptsign;
		this.applydeptsignid = applydeptsignid;
		this.applydeptsigndate = applydeptsigndate;
		this.dutyofficer = dutyofficer;
		this.dutyofficerid = dutyofficerid;
		this.dutyofficerdate = dutyofficerdate;
		this.isfinish = isfinish;
		this.operatrecord = operatrecord;
		this.recorder = recorder;
		this.recorderid = recorderid;
		this.recorddate = recorddate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public Integer getApplicantid() {
		return this.applicantid;
	}

	public void setApplicantid(Integer applicantid) {
		this.applicantid = applicantid;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public String getUserlist() {
		return this.userlist;
	}

	public void setUserlist(String userlist) {
		this.userlist = userlist;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getOpenreason() {
		return this.openreason;
	}

	public void setOpenreason(String openreason) {
		this.openreason = openreason;
	}

	public String getRevokereason() {
		return this.revokereason;
	}

	public void setRevokereason(String revokereason) {
		this.revokereason = revokereason;
	}

	public String getApplydeptopinion() {
		return this.applydeptopinion;
	}

	public void setApplydeptopinion(String applydeptopinion) {
		this.applydeptopinion = applydeptopinion;
	}

	public String getApplydeptsign() {
		return this.applydeptsign;
	}

	public void setApplydeptsign(String applydeptsign) {
		this.applydeptsign = applydeptsign;
	}

	public Integer getApplydeptsignid() {
		return this.applydeptsignid;
	}

	public void setApplydeptsignid(Integer applydeptsignid) {
		this.applydeptsignid = applydeptsignid;
	}

	public Date getApplydeptsigndate() {
		return this.applydeptsigndate;
	}

	public void setApplydeptsigndate(Date applydeptsigndate) {
		this.applydeptsigndate = applydeptsigndate;
	}

	public String getDutyofficer() {
		return this.dutyofficer;
	}

	public void setDutyofficer(String dutyofficer) {
		this.dutyofficer = dutyofficer;
	}

	public Integer getDutyofficerid() {
		return this.dutyofficerid;
	}

	public void setDutyofficerid(Integer dutyofficerid) {
		this.dutyofficerid = dutyofficerid;
	}

	public Date getDutyofficerdate() {
		return this.dutyofficerdate;
	}

	public void setDutyofficerdate(Date dutyofficerdate) {
		this.dutyofficerdate = dutyofficerdate;
	}

	public Integer getIsfinish() {
		return this.isfinish;
	}

	public void setIsfinish(Integer isfinish) {
		this.isfinish = isfinish;
	}

	public String getOperatrecord() {
		return this.operatrecord;
	}

	public void setOperatrecord(String operatrecord) {
		this.operatrecord = operatrecord;
	}

	public String getRecorder() {
		return this.recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

	public Integer getRecorderid() {
		return this.recorderid;
	}

	public void setRecorderid(Integer recorderid) {
		this.recorderid = recorderid;
	}

	public Date getRecorddate() {
		return this.recorddate;
	}

	public void setRecorddate(Date recorddate) {
		this.recorddate = recorddate;
	}

}