package com.manage.interview.model;

import com.manage.filmingactivity.model.original.AbstractFilmingActivity;
import com.manage.interview.model.original.AbstractInterview;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class Interview extends AbstractInterview {

}
