package com.manage.pantchrecord.model;

import com.manage.pantchrecord.model.original.AbstractPantchRecord;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class PantchRecord extends AbstractPantchRecord {

}
