package com.manage.changemedium.model.original;

/**
 * AbstractSChangemediumInfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSChangemediumInfoTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String mtype;
	private String specifications;
	private String bcorgname;
	private String bcorgid;
	private String bcdepository;
	private String bcclassification;
	private String bcscode;
	private String acorgname;
	private String acorgid;
	private String acdepository;
	private String acclassification;
	private String acscode;
	private String changereason;
	private Integer cid;

	// Constructors

	/** default constructor */
	public AbstractSChangemediumInfoTab() {
	}

	/** minimal constructor */
	public AbstractSChangemediumInfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSChangemediumInfoTab(Integer id, Integer version,
			String mtype, String specifications,
			String bcorgname, String bcorgid, String bcdepository,
			String bcclassification, String bcscode, String acorgname,
			String acorgid, String acdepository, String acclassification,
			String acscode, String changereason, Integer cid) {
		this.id = id;
		this.version = version;
		this.mtype = mtype;
		this.specifications = specifications;
		this.bcorgname = bcorgname;
		this.bcorgid = bcorgid;
		this.bcdepository = bcdepository;
		this.bcclassification = bcclassification;
		this.bcscode = bcscode;
		this.acorgname = acorgname;
		this.acorgid = acorgid;
		this.acdepository = acdepository;
		this.acclassification = acclassification;
		this.acscode = acscode;
		this.changereason = changereason;
		this.cid = cid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}


	public String getMtype() {
		return this.mtype;
	}

	public void setMtype(String mtype) {
		this.mtype = mtype;
	}

	public String getSpecifications() {
		return this.specifications;
	}

	public void setSpecifications(String specifications) {
		this.specifications = specifications;
	}

	public String getBcorgname() {
		return this.bcorgname;
	}

	public void setBcorgname(String bcorgname) {
		this.bcorgname = bcorgname;
	}

	public String getBcorgid() {
		return this.bcorgid;
	}

	public void setBcorgid(String bcorgid) {
		this.bcorgid = bcorgid;
	}

	public String getBcdepository() {
		return this.bcdepository;
	}

	public void setBcdepository(String bcdepository) {
		this.bcdepository = bcdepository;
	}

	public String getBcclassification() {
		return this.bcclassification;
	}

	public void setBcclassification(String bcclassification) {
		this.bcclassification = bcclassification;
	}

	public String getBcscode() {
		return this.bcscode;
	}

	public void setBcscode(String bcscode) {
		this.bcscode = bcscode;
	}

	public String getAcorgname() {
		return this.acorgname;
	}

	public void setAcorgname(String acorgname) {
		this.acorgname = acorgname;
	}

	public String getAcorgid() {
		return this.acorgid;
	}

	public void setAcorgid(String acorgid) {
		this.acorgid = acorgid;
	}

	public String getAcdepository() {
		return this.acdepository;
	}

	public void setAcdepository(String acdepository) {
		this.acdepository = acdepository;
	}

	public String getAcclassification() {
		return this.acclassification;
	}

	public void setAcclassification(String acclassification) {
		this.acclassification = acclassification;
	}

	public String getAcscode() {
		return this.acscode;
	}

	public void setAcscode(String acscode) {
		this.acscode = acscode;
	}

	public String getChangereason() {
		return this.changereason;
	}

	public void setChangereason(String changereason) {
		this.changereason = changereason;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

}