package com.manage.temp.model.original;

/**
 * AbstractSStoragemediumInfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSStoragemediumInfoTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer eid;
	private Integer qmediumtype;
	private String qspecifications;
	private String qclassification;
	private Integer qnum;
	private Integer qcerttype;
	private String qusrange;

	// Constructors

	/** default constructor */
	public AbstractSStoragemediumInfoTab() {
	}

	/** minimal constructor */
	public AbstractSStoragemediumInfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSStoragemediumInfoTab(Integer id, Integer version,
			Integer eid, Integer qmediumtype, String qspecifications,
			String qclassification, Integer qnum, Integer qcerttype,
			String qusrange) {
		this.id = id;
		this.version = version;
		this.eid = eid;
		this.qmediumtype = qmediumtype;
		this.qspecifications = qspecifications;
		this.qclassification = qclassification;
		this.qnum = qnum;
		this.qcerttype = qcerttype;
		this.qusrange = qusrange;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Integer getQmediumtype() {
		return this.qmediumtype;
	}

	public void setQmediumtype(Integer qmediumtype) {
		this.qmediumtype = qmediumtype;
	}

	public String getQspecifications() {
		return this.qspecifications;
	}

	public void setQspecifications(String qspecifications) {
		this.qspecifications = qspecifications;
	}

	public String getQclassification() {
		return this.qclassification;
	}

	public void setQclassification(String qclassification) {
		this.qclassification = qclassification;
	}

	public Integer getQnum() {
		return this.qnum;
	}

	public void setQnum(Integer qnum) {
		this.qnum = qnum;
	}

	public Integer getQcerttype() {
		return this.qcerttype;
	}

	public void setQcerttype(Integer qcerttype) {
		this.qcerttype = qcerttype;
	}

	public String getQusrange() {
		return this.qusrange;
	}

	public void setQusrange(String qusrange) {
		this.qusrange = qusrange;
	}

}