package com.manage.classifiedrecord.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.classifiedrecord.model.original.AbstractSClassifiedcopySupervisionTab;

/**
 * SClassifiedcopySupervisionTab generated by MyEclipse Persistence Tools
 */
public class SClassifiedcopySupervisionTab extends
		AbstractSClassifiedcopySupervisionTab implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SClassifiedcopySupervisionTab() {
	}

	/** minimal constructor */
	public SClassifiedcopySupervisionTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SClassifiedcopySupervisionTab(Integer id, Integer version,
			String cuname, String orgid, String orgname, Date cdate,
			String caddress, String cname, String bmname, Integer isapproval,
			Integer isdcopy, Integer issignsec, Integer isconrequire,
			String note, Integer isback, Integer bcopies, Integer ismark,
			Integer printnum, Integer renum, Integer iscountrecycle,
			String handling, Integer isdelete, String supervisor,
			String departmentsign, Integer departmentid, Date departmentdate,
			String officedesc, String officesign, Integer officeid,
			Date officedate,String username,Integer userid) {
		super(id, version, cuname, orgid, orgname, cdate, caddress, cname,
				bmname, isapproval, isdcopy, issignsec, isconrequire, note,
				isback, bcopies, ismark, printnum, renum, iscountrecycle,
				handling, isdelete, supervisor, departmentsign, departmentid,
				departmentdate, officedesc, officesign, officeid, officedate,username,userid);
	}

}
