package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAVideomeetingTab;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class AVideomeetingTab extends AbstractAVideomeetingTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AVideomeetingTab() {
	}

	/** minimal constructor */
	public AVideomeetingTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AVideomeetingTab(Integer id, Integer version, String meetingname,
			String applyorgname, String applyorgid, String applicant,
			Integer applicantid, String cellphone, Integer meetingtype,
			String meetingplace, String meetingagenda, String jingqu,
			String jingwai, Date meetingtime, Date jointdebugtime,
			Integer isppt, Integer meetingmode, String speakplace,
			String deptopinion, String deptsign, String deptid,
			Date deptsigndate) {
		super(id, version, meetingname, applyorgname, applyorgid, applicant,
				applicantid, cellphone, meetingtype, meetingplace,
				meetingagenda, jingqu, jingwai, meetingtime, jointdebugtime,
				isppt, meetingmode, speakplace, deptopinion, deptsign, deptid,
				deptsigndate);
	}

}
