package com.manage.videomeeting.model;

import com.manage.videomeeting.model.original.AbstractVideoMeeting;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class VideoMeeting extends AbstractVideoMeeting {

}
