package com.manage.empseccheck.model;

import com.manage.empseccheck.model.original.AbstractEmpSecCheck;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class EmpSecCheck extends AbstractEmpSecCheck {

}
