package com.manage.borrowmedium.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.borrowmedium.model.original.AbstractSBorrowmediumTab;

/**
 * SBorrowmediumTab generated by MyEclipse Persistence Tools
 */
public class SBorrowmediumTab extends AbstractSBorrowmediumTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SBorrowmediumTab() {
	}

	/** minimal constructor */
	public SBorrowmediumTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SBorrowmediumTab(Integer id, Integer version, Date borrowdate,
			Integer mediumtype, Integer mclassified, String scode,
			String devicecode, Integer dclassified, String ulimite,
			String usesign, Integer uid, Date receivedate, String checkdesc,
			String cname, Integer cid,String username,Integer userid,String mark) {
		super(id, version, borrowdate, mediumtype, mclassified, scode,
				devicecode, dclassified, ulimite, usesign, uid, receivedate,
				checkdesc, cname, cid,username,userid,mark);
	}

}
