package com.manage.secretonline.model.original;

import java.util.Date;

/**
 * AbstractSSecretonlineTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSSecretonlineTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String orgname;
	private String orgid;
	private String uname;
	private String sresponsible;
	private String models;
	private String licensenum;
	private String rsign;
	private Integer rid;
	private Date rdate;
	private String dsign;
	private Integer did;
	private Date ddate;
	private String note;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSSecretonlineTab() {
	}

	/** minimal constructor */
	public AbstractSSecretonlineTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSSecretonlineTab(Integer id, Integer version,
			String orgname, String orgid, String uname, String sresponsible,
			String models, String licensenum, String rsign, Integer rid,
			Date rdate, String dsign, Integer did, Date ddate, String note,String username,Integer userid) {
		this.id = id;
		this.version = version;
		this.orgname = orgname;
		this.orgid = orgid;
		this.uname = uname;
		this.sresponsible = sresponsible;
		this.models = models;
		this.licensenum = licensenum;
		this.rsign = rsign;
		this.rid = rid;
		this.rdate = rdate;
		this.dsign = dsign;
		this.did = did;
		this.ddate = ddate;
		this.note = note;
		this.username = username;
		this.userid = userid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getSresponsible() {
		return this.sresponsible;
	}

	public void setSresponsible(String sresponsible) {
		this.sresponsible = sresponsible;
	}

	public String getModels() {
		return this.models;
	}

	public void setModels(String models) {
		this.models = models;
	}

	public String getLicensenum() {
		return this.licensenum;
	}

	public void setLicensenum(String licensenum) {
		this.licensenum = licensenum;
	}

	public String getRsign() {
		return this.rsign;
	}

	public void setRsign(String rsign) {
		this.rsign = rsign;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Date getRdate() {
		return this.rdate;
	}

	public void setRdate(Date rdate) {
		this.rdate = rdate;
	}

	public String getDsign() {
		return this.dsign;
	}

	public void setDsign(String dsign) {
		this.dsign = dsign;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public Date getDdate() {
		return this.ddate;
	}

	public void setDdate(Date ddate) {
		this.ddate = ddate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}