package com.manage.changeinternet.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.changeinternet.model.original.AbstractSChangeinternetTab;

/**
 * SChangeinternetTab generated by MyEclipse Persistence Tools
 */
public class SChangeinternetTab extends AbstractSChangeinternetTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SChangeinternetTab() {
	}

	/** minimal constructor */
	public SChangeinternetTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SChangeinternetTab(Integer id, Integer version, String orgname,
			String orgid,Date cdate,String depdesc, Date depdate, String mdepdesc, Date mdepdate,String username,Integer userid) {
		super(id, version, orgname, orgid,cdate,  depdesc,
				depdate, mdepdesc, mdepdate,username,userid);
	}

}
