package com.manage.changeinternet.model;

import com.manage.changeinternet.model.original.AbstractSChangeinternetInfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SChangeinternetInfoTab generated by MyEclipse Persistence Tools
 */
public class SChangeinternetInfoTab extends AbstractSChangeinternetInfoTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SChangeinternetInfoTab() {
	}

	/** minimal constructor */
	public SChangeinternetInfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SChangeinternetInfoTab(Integer id, Integer version, Integer cid,
			String licensenum, String bcorgname, String bcorgid,
			String bcsresponsible, String bcserialnum, String haddress,
			String acorgname, String acorgid, String acsresponsible,
			String acserialnum, String achaddress, String changereason) {
		super(id, version, cid, licensenum, bcorgname, bcorgid, bcsresponsible,
				bcserialnum, haddress, acorgname, acorgid, acsresponsible,
				acserialnum, achaddress, changereason);
	}

}
