package com.manage.quartersubsidies.model.original;

/**
 * AbstractSQuartersubsidiesInfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSQuartersubsidiesInfoTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer qid;
	private String name;
	private String classification;
	private Double yfmoney;
	private Double brmoney;
	private Double sfmoney;
	private String moneybdreason;
	private Integer isperform;
	private String remark;

	// Constructors

	/** default constructor */
	public AbstractSQuartersubsidiesInfoTab() {
	}

	/** minimal constructor */
	public AbstractSQuartersubsidiesInfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSQuartersubsidiesInfoTab(Integer id, Integer version,
			Integer qid, String name, String classification, Double yfmoney,
			Double brmoney, Double sfmoney, String moneybdreason,
			Integer isperform, String remark) {
		this.id = id;
		this.version = version;
		this.qid = qid;
		this.name = name;
		this.classification = classification;
		this.yfmoney = yfmoney;
		this.brmoney = brmoney;
		this.sfmoney = sfmoney;
		this.moneybdreason = moneybdreason;
		this.isperform = isperform;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public Double getYfmoney() {
		return this.yfmoney;
	}

	public void setYfmoney(Double yfmoney) {
		this.yfmoney = yfmoney;
	}

	public Double getBrmoney() {
		return this.brmoney;
	}

	public void setBrmoney(Double brmoney) {
		this.brmoney = brmoney;
	}

	public Double getSfmoney() {
		return this.sfmoney;
	}

	public void setSfmoney(Double sfmoney) {
		this.sfmoney = sfmoney;
	}

	public String getMoneybdreason() {
		return this.moneybdreason;
	}

	public void setMoneybdreason(String moneybdreason) {
		this.moneybdreason = moneybdreason;
	}

	public Integer getIsperform() {
		return this.isperform;
	}

	public void setIsperform(Integer isperform) {
		this.isperform = isperform;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}