package com.manage.divulgesecret.model;

import com.manage.divulgesecret.model.original.AbstractDivulgeSecret;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class DivulgeSecret extends AbstractDivulgeSecret {

}
