package com.manage.subsidiesdetainper.model;

import com.manage.subsidiesdetainper.model.original.AbstractSubsidiesDetainper;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class SubsidiesDetainper extends AbstractSubsidiesDetainper {

}
