package com.manage.carrypartmedium.model.original;

import java.util.Date;

/**
 * AbstractSCarrypartmediumTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSCarrypartmediumTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String code;
	private String orgname;
	private String orgid;
	private String agent;
	private String location;
	private Date returndate;
	private Date applydate;
	private Integer mclassifition;
	private String scode;
	private String yt;
	private String information;
	private String imaxclassification;
	private String usign;
	private Integer uid;
	private Date udate;
	private String departmentdesc;
	private Date departmentdate;
	private String recheckcase;
	private Date recheckdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSCarrypartmediumTab() {
	}

	/** minimal constructor */
	public AbstractSCarrypartmediumTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSCarrypartmediumTab(Integer id, Integer version,
			String code, String orgname, String orgid, String agent,
			String location, Date returndate, Date applydate,
			Integer mclassifition, String scode, String yt,
			String information, String imaxclassification, String usign,
			Integer uid, Date udate, String departmentdesc,
			Date departmentdate, String recheckcase, Date recheckdate,String username,Integer userid) {
		this.id = id;
		this.version = version;
		this.code = code;
		this.orgname = orgname;
		this.orgid = orgid;
		this.agent = agent;
		this.location = location;
		this.returndate = returndate;
		this.applydate = applydate;
		this.mclassifition = mclassifition;
		this.scode = scode;
		this.yt = yt;
		this.information = information;
		this.imaxclassification = imaxclassification;
		this.usign = usign;
		this.uid = uid;
		this.udate = udate;
		this.departmentdesc = departmentdesc;
		this.departmentdate = departmentdate;
		this.recheckcase = recheckcase;
		this.recheckdate = recheckdate;
		this.username = username;
		this.userid = userid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getReturndate() {
		return this.returndate;
	}

	public void setReturndate(Date returndate) {
		this.returndate = returndate;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public Integer getMclassifition() {
		return this.mclassifition;
	}

	public void setMclassifition(Integer mclassifition) {
		this.mclassifition = mclassifition;
	}

	public String getScode() {
		return this.scode;
	}

	public void setScode(String scode) {
		this.scode = scode;
	}

	public String getYt() {
		return yt;
	}

	public void setYt(String yt) {
		this.yt = yt;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	public String getImaxclassification() {
		return this.imaxclassification;
	}

	public void setImaxclassification(String imaxclassification) {
		this.imaxclassification = imaxclassification;
	}

	public String getUsign() {
		return this.usign;
	}

	public void setUsign(String usign) {
		this.usign = usign;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Date getUdate() {
		return this.udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	public String getDepartmentdesc() {
		return this.departmentdesc;
	}

	public void setDepartmentdesc(String departmentdesc) {
		this.departmentdesc = departmentdesc;
	}

	public Date getDepartmentdate() {
		return this.departmentdate;
	}

	public void setDepartmentdate(Date departmentdate) {
		this.departmentdate = departmentdate;
	}

	public String getRecheckcase() {
		return this.recheckcase;
	}

	public void setRecheckcase(String recheckcase) {
		this.recheckcase = recheckcase;
	}

	public Date getRecheckdate() {
		return this.recheckdate;
	}

	public void setRecheckdate(Date recheckdate) {
		this.recheckdate = recheckdate;
	}

}