package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAFerrycentreTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAFerrycentreTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String applydept;
	private Integer applydeptid;
	private Integer security;
	private String linkman;
	private String cellphone;
	private String createplace;
	private Date applydate;
	private String ferryer;
	private Integer ferryersecurity;
	private String applyreason;
	private String applydeptopinion;
	private String applydeptsign;
	private Integer applydeptsignid;
	private Date applydeptsigndate;
	private String securityopinion;
	private String securitysign;
	private Integer securityid;
	private Date securitysigndate;
	private String infordeptopinion;
	private String infordeptsign;
	private Integer infordeptsignid;
	private Date infordeptsigndate;
	private String trancondition;
	private String transign;
	private Integer transignid;
	private Date transigndate;

	// Constructors

	/** default constructor */
	public AbstractAFerrycentreTab() {
	}

	/** minimal constructor */
	public AbstractAFerrycentreTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAFerrycentreTab(Integer id, Integer version,
			String applydept, Integer applydeptid, Integer security,
			String linkman, String cellphone, String createplace,
			Date applydate, String ferryer, Integer ferryersecurity,
			String applyreason, String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String securityopinion, String securitysign, Integer securityid,
			Date securitysigndate, String infordeptopinion,
			String infordeptsign, Integer infordeptsignid,
			Date infordeptsigndate, String trancondition, String transign,
			Integer transignid, Date transigndate) {
		this.id = id;
		this.version = version;
		this.applydept = applydept;
		this.applydeptid = applydeptid;
		this.security = security;
		this.linkman = linkman;
		this.cellphone = cellphone;
		this.createplace = createplace;
		this.applydate = applydate;
		this.ferryer = ferryer;
		this.ferryersecurity = ferryersecurity;
		this.applyreason = applyreason;
		this.applydeptopinion = applydeptopinion;
		this.applydeptsign = applydeptsign;
		this.applydeptsignid = applydeptsignid;
		this.applydeptsigndate = applydeptsigndate;
		this.securityopinion = securityopinion;
		this.securitysign = securitysign;
		this.securityid = securityid;
		this.securitysigndate = securitysigndate;
		this.infordeptopinion = infordeptopinion;
		this.infordeptsign = infordeptsign;
		this.infordeptsignid = infordeptsignid;
		this.infordeptsigndate = infordeptsigndate;
		this.trancondition = trancondition;
		this.transign = transign;
		this.transignid = transignid;
		this.transigndate = transigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getApplydept() {
		return this.applydept;
	}

	public void setApplydept(String applydept) {
		this.applydept = applydept;
	}

	public Integer getApplydeptid() {
		return this.applydeptid;
	}

	public void setApplydeptid(Integer applydeptid) {
		this.applydeptid = applydeptid;
	}

	public Integer getSecurity() {
		return this.security;
	}

	public void setSecurity(Integer security) {
		this.security = security;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getCreateplace() {
		return this.createplace;
	}

	public void setCreateplace(String createplace) {
		this.createplace = createplace;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getFerryer() {
		return this.ferryer;
	}

	public void setFerryer(String ferryer) {
		this.ferryer = ferryer;
	}

	public Integer getFerryersecurity() {
		return this.ferryersecurity;
	}

	public void setFerryersecurity(Integer ferryersecurity) {
		this.ferryersecurity = ferryersecurity;
	}

	public String getApplyreason() {
		return this.applyreason;
	}

	public void setApplyreason(String applyreason) {
		this.applyreason = applyreason;
	}

	public String getApplydeptopinion() {
		return this.applydeptopinion;
	}

	public void setApplydeptopinion(String applydeptopinion) {
		this.applydeptopinion = applydeptopinion;
	}

	public String getApplydeptsign() {
		return this.applydeptsign;
	}

	public void setApplydeptsign(String applydeptsign) {
		this.applydeptsign = applydeptsign;
	}

	public Integer getApplydeptsignid() {
		return this.applydeptsignid;
	}

	public void setApplydeptsignid(Integer applydeptsignid) {
		this.applydeptsignid = applydeptsignid;
	}

	public Date getApplydeptsigndate() {
		return this.applydeptsigndate;
	}

	public void setApplydeptsigndate(Date applydeptsigndate) {
		this.applydeptsigndate = applydeptsigndate;
	}

	public String getSecurityopinion() {
		return this.securityopinion;
	}

	public void setSecurityopinion(String securityopinion) {
		this.securityopinion = securityopinion;
	}

	public String getSecuritysign() {
		return this.securitysign;
	}

	public void setSecuritysign(String securitysign) {
		this.securitysign = securitysign;
	}

	public Integer getSecurityid() {
		return this.securityid;
	}

	public void setSecurityid(Integer securityid) {
		this.securityid = securityid;
	}

	public Date getSecuritysigndate() {
		return this.securitysigndate;
	}

	public void setSecuritysigndate(Date securitysigndate) {
		this.securitysigndate = securitysigndate;
	}

	public String getInfordeptopinion() {
		return this.infordeptopinion;
	}

	public void setInfordeptopinion(String infordeptopinion) {
		this.infordeptopinion = infordeptopinion;
	}

	public String getInfordeptsign() {
		return this.infordeptsign;
	}

	public void setInfordeptsign(String infordeptsign) {
		this.infordeptsign = infordeptsign;
	}

	public Integer getInfordeptsignid() {
		return this.infordeptsignid;
	}

	public void setInfordeptsignid(Integer infordeptsignid) {
		this.infordeptsignid = infordeptsignid;
	}

	public Date getInfordeptsigndate() {
		return this.infordeptsigndate;
	}

	public void setInfordeptsigndate(Date infordeptsigndate) {
		this.infordeptsigndate = infordeptsigndate;
	}

	public String getTrancondition() {
		return this.trancondition;
	}

	public void setTrancondition(String trancondition) {
		this.trancondition = trancondition;
	}

	public String getTransign() {
		return this.transign;
	}

	public void setTransign(String transign) {
		this.transign = transign;
	}

	public Integer getTransignid() {
		return this.transignid;
	}

	public void setTransignid(Integer transignid) {
		this.transignid = transignid;
	}

	public Date getTransigndate() {
		return this.transigndate;
	}

	public void setTransigndate(Date transigndate) {
		this.transigndate = transigndate;
	}

}