package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSQuartersubsidiesInfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SQuartersubsidiesInfoTab generated by MyEclipse Persistence Tools
 */
public class SQuartersubsidiesInfoTab extends AbstractSQuartersubsidiesInfoTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SQuartersubsidiesInfoTab() {
	}

	/** minimal constructor */
	public SQuartersubsidiesInfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SQuartersubsidiesInfoTab(Integer id, Integer version, Integer qid,
			String name, String classification, Double yfmoney, Double brmoney,
			Double sfmoney, String moneybdreason, Integer isperform,
			String remark) {
		super(id, version, qid, name, classification, yfmoney, brmoney,
				sfmoney, moneybdreason, isperform, remark);
	}

}
