package com.manage.examclassification.model.original;

import java.util.Date;

/**
 * AbstractSExamClassificationTab generated by MyEclipse Persistence Tools
 */

public  class AbstractSExamClassificationTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String ecname;
	private Integer sex;
	private Integer age;
	private String oriname;
	private String orgid;
	private String position;
	private String oposition;
	private String oclassification;
	private Integer optype;
	private String leadershipsign;
	private Integer leaderid;
	private Date leadersigndate;
	private Integer dptype;
	private String departmentsign;
	private Integer departmentid;
	private Date departmentdate;
	private Integer sptype;
	private String sofficesign;
	private Date sofficesigndate;
	private Integer sofficeid;
	private Integer scptype;
	private String scomsign;
	private Date scomsigndate;
	private Integer scomid;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSExamClassificationTab() {
	}

	/** minimal constructor */
	public AbstractSExamClassificationTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSExamClassificationTab(Integer id, Integer version,
			String ecname, Integer sex, Integer age, String oriname,
			String orgid, String position, String oposition,
			String oclassification, Integer otype, String leadershipsign,
			Integer leaderid, Date leadersigndate, Integer dptype,
			String departmentsign, Integer departmentid, Date departmentdate,
			Integer sptype, String sofficesign, Date sofficesigndate,
			Integer sofficeid, Integer scptype, String scomsign,
			Date scomsigndate, Integer scomid,String username,Integer userid) {
		this.id = id;
		this.version = version;
		this.ecname = ecname;
		this.sex = sex;
		this.age = age;
		this.oriname = oriname;
		this.orgid = orgid;
		this.position = position;
		this.oposition = oposition;
		this.oclassification = oclassification;
		this.optype = optype;
		this.leadershipsign = leadershipsign;
		this.leaderid = leaderid;
		this.leadersigndate = leadersigndate;
		this.dptype = dptype;
		this.departmentsign = departmentsign;
		this.departmentid = departmentid;
		this.departmentdate = departmentdate;
		this.sptype = sptype;
		this.sofficesign = sofficesign;
		this.sofficesigndate = sofficesigndate;
		this.sofficeid = sofficeid;
		this.scptype = scptype;
		this.scomsign = scomsign;
		this.scomsigndate = scomsigndate;
		this.scomid = scomid;
		this.username = username;
		this.userid = userid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getEcname() {
		return this.ecname;
	}

	public void setEcname(String ecname) {
		this.ecname = ecname;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getOriname() {
		return this.oriname;
	}

	public void setOriname(String oriname) {
		this.oriname = oriname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getOposition() {
		return this.oposition;
	}

	public void setOposition(String oposition) {
		this.oposition = oposition;
	}

	
	public String getOclassification() {
		return oclassification;
	}

	public void setOclassification(String oclassification) {
		this.oclassification = oclassification;
	}


	public String getLeadershipsign() {
		return this.leadershipsign;
	}

	public void setLeadershipsign(String leadershipsign) {
		this.leadershipsign = leadershipsign;
	}

	public Integer getLeaderid() {
		return this.leaderid;
	}

	public void setLeaderid(Integer leaderid) {
		this.leaderid = leaderid;
	}

	public Date getLeadersigndate() {
		return this.leadersigndate;
	}

	public void setLeadersigndate(Date leadersigndate) {
		this.leadersigndate = leadersigndate;
	}


	public String getDepartmentsign() {
		return this.departmentsign;
	}

	public void setDepartmentsign(String departmentsign) {
		this.departmentsign = departmentsign;
	}

	public Integer getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public Date getDepartmentdate() {
		return this.departmentdate;
	}

	public void setDepartmentdate(Date departmentdate) {
		this.departmentdate = departmentdate;
	}


	public String getSofficesign() {
		return this.sofficesign;
	}

	public void setSofficesign(String sofficesign) {
		this.sofficesign = sofficesign;
	}

	public Date getSofficesigndate() {
		return this.sofficesigndate;
	}

	public void setSofficesigndate(Date sofficesigndate) {
		this.sofficesigndate = sofficesigndate;
	}

	public Integer getSofficeid() {
		return this.sofficeid;
	}

	public void setSofficeid(Integer sofficeid) {
		this.sofficeid = sofficeid;
	}


	public String getScomsign() {
		return this.scomsign;
	}

	public void setScomsign(String scomsign) {
		this.scomsign = scomsign;
	}

	public Date getScomsigndate() {
		return this.scomsigndate;
	}

	public void setScomsigndate(Date scomsigndate) {
		this.scomsigndate = scomsigndate;
	}

	public Integer getScomid() {
		return this.scomid;
	}

	public void setScomid(Integer scomid) {
		this.scomid = scomid;
	}

	public Integer getOptype() {
		return optype;
	}

	public void setOptype(Integer optype) {
		this.optype = optype;
	}

	public Integer getDptype() {
		return dptype;
	}

	public void setDptype(Integer dptype) {
		this.dptype = dptype;
	}

	public Integer getSptype() {
		return sptype;
	}

	public void setSptype(Integer sptype) {
		this.sptype = sptype;
	}

	public Integer getScptype() {
		return scptype;
	}

	public void setScptype(Integer scptype) {
		this.scptype = scptype;
	}


}