package com.manage.conagreementyb.model;

import com.manage.conagreementyb.model.original.AbstractConAgreementyb;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class ConAgreementyb extends AbstractConAgreementyb {

}
