package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractADeviceiosysTab;

/**
 * ADeviceiosysTab generated by MyEclipse Persistence Tools
 */
public class ADeviceiosysTab extends AbstractADeviceiosysTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ADeviceiosysTab() {
	}

	/** minimal constructor */
	public ADeviceiosysTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ADeviceiosysTab(Integer id, Integer version, String applicant,
			Integer applicantid, String cellphone, Date appliydate,
			Integer applicanttype, String applicantelse, Integer type,
			Integer applicantsecurity, String orgname, String orgid,
			Integer devicetype, String deviceelse, String deviceindex,
			String hardpanserialnum, Integer devicesecurity,
			String storageplace, String insysname, String outsysname,
			Integer insysreason, String inreasonelse, Integer outsysreason,
			String outreasonelse, String applydeptopinion,
			String applydeptsign, Integer applydeptsignid,
			Date applydeptsigndate, String infordeptopinion,
			String infordeptsign, Integer infordeptsignid,
			Date infordeptsigndate, String devprincipalsign,
			Integer devprincipalid, Date devprincipalsigndate,
			String devrecipientsign, Integer devrecipientid,
			Date devrecipientsigndate, Integer isclearinformation,
			Integer isremovefirmware, Integer istransferdevice,
			String operatorsign, Integer operatorid, Date operatorsigndate,
			String storeinforecipient, Integer storeinforecipientid,
			String allocationip, String closeip, Integer switchboard,
			String switchboardname, String switchboardsign,
			Integer switchboardsignid, Date switchboarddate, Integer isoa,
			String oaoperatorsign, Integer oaoperatorid, Date oaoperatordate,
			String domainemail, String domainoperator,
			Integer domainoperatorid, Date domaindate, Integer isupdate,
			Integer isinform, Integer isrecord, String recordorsign,
			Integer recordorid, String managersign, Integer managerid,
			Date managersigndate) {
		super(id, version, applicant, applicantid, cellphone, appliydate,
				applicanttype, applicantelse, type, applicantsecurity, orgname,
				orgid, devicetype, deviceelse, deviceindex, hardpanserialnum,
				devicesecurity, storageplace, insysname, outsysname,
				insysreason, inreasonelse, outsysreason, outreasonelse,
				applydeptopinion, applydeptsign, applydeptsignid,
				applydeptsigndate, infordeptopinion, infordeptsign,
				infordeptsignid, infordeptsigndate, devprincipalsign,
				devprincipalid, devprincipalsigndate, devrecipientsign,
				devrecipientid, devrecipientsigndate, isclearinformation,
				isremovefirmware, istransferdevice, operatorsign, operatorid,
				operatorsigndate, storeinforecipient, storeinforecipientid,
				allocationip, closeip, switchboard, switchboardname,
				switchboardsign, switchboardsignid, switchboarddate, isoa,
				oaoperatorsign, oaoperatorid, oaoperatordate, domainemail,
				domainoperator, domainoperatorid, domaindate, isupdate,
				isinform, isrecord, recordorsign, recordorid, managersign,
				managerid, managersigndate);
	}

}
