package com.manage.temp.model.original;

/**
 * AbstractSClassifieddestroyInfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSClassifieddestroyInfoTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer cdid;
	private String filename;
	private String productunit;
	private Integer carriertype;
	private String code;
	private String classification;
	private Integer pages;
	private Integer copies;
	private Integer depositoryid;
	private String depository;

	// Constructors

	/** default constructor */
	public AbstractSClassifieddestroyInfoTab() {
	}

	/** minimal constructor */
	public AbstractSClassifieddestroyInfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSClassifieddestroyInfoTab(Integer id, Integer version,
			Integer cdid, String filename, String productunit,
			Integer carriertype, String code, String classification,
			Integer pages, Integer copies, Integer depositoryid,
			String depository) {
		this.id = id;
		this.version = version;
		this.cdid = cdid;
		this.filename = filename;
		this.productunit = productunit;
		this.carriertype = carriertype;
		this.code = code;
		this.classification = classification;
		this.pages = pages;
		this.copies = copies;
		this.depositoryid = depositoryid;
		this.depository = depository;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getCdid() {
		return this.cdid;
	}

	public void setCdid(Integer cdid) {
		this.cdid = cdid;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getProductunit() {
		return this.productunit;
	}

	public void setProductunit(String productunit) {
		this.productunit = productunit;
	}

	public Integer getCarriertype() {
		return this.carriertype;
	}

	public void setCarriertype(Integer carriertype) {
		this.carriertype = carriertype;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public Integer getPages() {
		return this.pages;
	}

	public void setPages(Integer pages) {
		this.pages = pages;
	}

	public Integer getCopies() {
		return this.copies;
	}

	public void setCopies(Integer copies) {
		this.copies = copies;
	}

	public Integer getDepositoryid() {
		return this.depositoryid;
	}

	public void setDepositoryid(Integer depositoryid) {
		this.depositoryid = depositoryid;
	}

	public String getDepository() {
		return this.depository;
	}

	public void setDepository(String depository) {
		this.depository = depository;
	}

}