package com.manage.temp.model.original;

/**
 * AbstractSSecpersonnelTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSSecpersonnelTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer sid;
	private String orgname;
	private String orgid;
	private String name;

	// Constructors

	/** default constructor */
	public AbstractSSecpersonnelTab() {
	}

	/** minimal constructor */
	public AbstractSSecpersonnelTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSSecpersonnelTab(Integer id, Integer version, Integer sid,
			String orgname, String orgid, String name) {
		this.id = id;
		this.version = version;
		this.sid = sid;
		this.orgname = orgname;
		this.orgid = orgid;
		this.name = name;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}