package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSPromiseTab;

/**
 * SPromiseTab generated by MyEclipse Persistence Tools
 */
public class SPromiseTab extends AbstractSPromiseTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SPromiseTab() {
	}

	/** minimal constructor */
	public SPromiseTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SPromiseTab(Integer id, Integer version, String pname, Integer pid,
			Date pdate) {
		super(id, version, pname, pid, pdate);
	}

}
