package com.manage.smediumborrow.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.smediumborrow.model.original.AbstractSSmediumborrowTab;

/**
 * SSmediumborrowTab generated by MyEclipse Persistence Tools
 */
public class SSmediumborrowTab extends AbstractSSmediumborrowTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SSmediumborrowTab() {
	}

	/** minimal constructor */
	public SSmediumborrowTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SSmediumborrowTab(Integer id, Integer version, String scode,
			String orgname, String orgid, String bname, Integer bid,
			String borrowreason, String mcode, Integer mclassifition,
			Date usedate, String dcode, String information,
			String imaxclassified, String departmentdesc, Date departmentdate,
			String officedesc, Date officedate, String cleardesc,
			Date cleardate, Date applydate,String username,Integer userid,String mark) {
		super(id, version, scode, orgname, orgid, bname, bid, borrowreason,
				mcode, mclassifition, usedate, dcode, information,
				imaxclassified, departmentdesc, departmentdate, officedesc,
				officedate, cleardesc, cleardate, applydate,username,userid,mark);
	}

}
