package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSMeetsecrecyrecordTab;

/**
 * SMeetsecrecyrecordTab generated by MyEclipse Persistence Tools
 */
public class SMeetsecrecyrecordTab extends AbstractSMeetsecrecyrecordTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SMeetsecrecyrecordTab() {
	}

	/** minimal constructor */
	public SMeetsecrecyrecordTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SMeetsecrecyrecordTab(Integer id, Integer version, String meetname,
			String orgid, String orgname, Date meetdate, String classification,
			String meetplace, String meetcontent, String meeters,
			Integer issecuritywork, String sworkremark, Integer istelshield,
			String telshieldremark, Integer isstoretel, String storetelremark,
			Integer scheck, String scheckremark, Integer isdeclares,
			String declareremark, Integer issignin, String signinremark,
			Integer iswiffi, String wiffiremark, Integer istape,
			String taperemark, String taper, String videor,
			Integer issecurityfile, Integer total, Integer giveout,
			Integer takeback, String takebacker, Integer isguard,
			String guardremark, String bmname, Integer bmnameid,
			Date bmsigndate, String sofficedesc, String sofficesign,
			Integer sofficeid, Date sofficedate) {
		super(id, version, meetname, orgid, orgname, meetdate, classification,
				meetplace, meetcontent, meeters, issecuritywork, sworkremark,
				istelshield, telshieldremark, isstoretel, storetelremark,
				scheck, scheckremark, isdeclares, declareremark, issignin,
				signinremark, iswiffi, wiffiremark, istape, taperemark, taper,
				videor, issecurityfile, total, giveout, takeback, takebacker,
				isguard, guardremark, bmname, bmnameid, bmsigndate,
				sofficedesc, sofficesign, sofficeid, sofficedate);
	}

}
