package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAAppsysnetinTab;

/**
 * AAppsysnetinTab generated by MyEclipse Persistence Tools
 */
public class AAppsysnetinTab extends AbstractAAppsysnetinTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AAppsysnetinTab() {
	}

	/** minimal constructor */
	public AAppsysnetinTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AAppsysnetinTab(Integer id, Integer version, String sysname,
			String projectprincipal, String executivedept,
			Integer executivedeptid, String deptprincipal,
			String sysdevelopdept, String developor, String developdeptzizhi,
			Integer security, String accesspoint, String applicationrange,
			String functionsketch, String projectdata, String environment,
			String securitypolicy, String setupdept, String setupdeptsign,
			Integer setuporid, Date setupordate, String securityopinion,
			String securitysign, Integer securityid, Date securitysigndate,
			String infordeptopinion, String infordeptsign,
			Integer infordeptsignid, Date infordeptsigndate) {
		super(id, version, sysname, projectprincipal, executivedept,
				executivedeptid, deptprincipal, sysdevelopdept, developor,
				developdeptzizhi, security, accesspoint, applicationrange,
				functionsketch, projectdata, environment, securitypolicy,
				setupdept, setupdeptsign, setuporid, setupordate,
				securityopinion, securitysign, securityid, securitysigndate,
				infordeptopinion, infordeptsign, infordeptsignid,
				infordeptsigndate);
	}

}
