package com.manage.temp.model;

import com.manage.temp.model.original.AbstractADeviceinfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * ADeviceinfoTab generated by MyEclipse Persistence Tools
 */
public class ADeviceinfoTab extends AbstractADeviceinfoTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ADeviceinfoTab() {
	}

	/** minimal constructor */
	public ADeviceinfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ADeviceinfoTab(Integer id, Integer version, Integer did,
			String device, String devversion, Integer number, String producer,
			Double budget) {
		super(id, version, did, device, devversion, number, producer, budget);
	}

}
