package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractADevicepurchaseTab;

/**
 * ADevicepurchaseTab generated by MyEclipse Persistence Tools
 */
public class ADevicepurchaseTab extends AbstractADevicepurchaseTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ADevicepurchaseTab() {
	}

	/** minimal constructor */
	public ADevicepurchaseTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ADevicepurchaseTab(Integer id, Integer version, String applydept,
			Integer applydeptid, Date applydate,
			String purchasereason, String deptopinion, String deptsign,
			Integer deptsignid, Date signdate) {
		super(id, version, applydept, applydeptid, applydate,purchasereason,
				deptopinion, deptsign, deptsignid, signdate);
	}

}
