package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractANotsecretpcoutTab;

/**
 * ANotsecretpcoutTab generated by MyEclipse Persistence Tools
 */
public class ANotsecretpcoutTab extends AbstractANotsecretpcoutTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ANotsecretpcoutTab() {
	}

	/** minimal constructor */
	public ANotsecretpcoutTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ANotsecretpcoutTab(Integer id, Integer version, String deptname,
			Integer deptid, String borrower, Integer borrowerid,
			String outplace, String devicenum, String diskfrom,
			String mediumnum, Integer issecret, String borrowreason,
			String borrowersign, Date borrowersigndate,
			String deptleaderopinion, String deptleadersign,
			Integer deptleaderid, Date leadersigndate, String devtransfer,
			String receivesign, Date receivesigndate, String returncondition,
			String checkersign, Integer checkerid, Date checkersigndate,
			String devmanager, Integer devmanagerid, Date devmansigndate,
			String securityopinion, String securitysign, Integer securityid,
			Date securitysigndate) {
		super(id, version, deptname, deptid, borrower, borrowerid, outplace,
				devicenum, diskfrom, mediumnum, issecret, borrowreason,
				borrowersign, borrowersigndate, deptleaderopinion,
				deptleadersign, deptleaderid, leadersigndate, devtransfer,
				receivesign, receivesigndate, returncondition, checkersign,
				checkerid, checkersigndate, devmanager, devmanagerid,
				devmansigndate, securityopinion, securitysign, securityid,
				securitysigndate);
	}

}
