package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAPantchrecordTab;

/**
 * APantchrecordTab generated by MyEclipse Persistence Tools
 */
public class APantchrecordTab extends AbstractAPantchrecordTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public APantchrecordTab() {
	}

	/** minimal constructor */
	public APantchrecordTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public APantchrecordTab(Integer id, Integer version, Date checkdate,
			String checkplace, String checkcondition, String checker,
			Integer checkerid, String remark) {
		super(id, version, checkdate, checkplace, checkcondition, checker,
				checkerid, remark);
	}

}
