package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractASecretpcoutTab;

/**
 * ASecretpcoutTab generated by MyEclipse Persistence Tools
 */
public class ASecretpcoutTab extends AbstractASecretpcoutTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ASecretpcoutTab() {
	}

	/** minimal constructor */
	public ASecretpcoutTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ASecretpcoutTab(Integer id, Integer version, String deptname,
			Integer deptid, String user, String outplace, String devicenum,
			Integer devicesecurity, Integer iscontentsecret, String diskfrom,
			String mediumnum, Integer mediumsecurity, String impboxnum,
			Integer impboxsecurity, String borrowreason, String applyopenport,
			String applyinstallsoft, String usersign, Integer userid,
			Date usersigndate, String deptleaderopinion, String deptleadersign,
			Integer deptleaderid, Date leadersigndate, Integer isupdate,
			String updateversion, String openport, String installsoft,
			String operator1, Integer operatorid1, Date operatordate1,
			String receiver, Integer receiverid, Date receiverdate,
			String checkcondition, String transfersign, Integer transferid,
			String checkersign, Integer checkerid, Date checkersigndate,
			String portcondition, String operator2, Integer operatorid2,
			Date operatordate2, String securityopinion, String securitysign,
			Integer securityid, Date securitysigndate) {
		super(id, version, deptname, deptid, user, outplace, devicenum,
				devicesecurity, iscontentsecret, diskfrom, mediumnum,
				mediumsecurity, impboxnum, impboxsecurity, borrowreason,
				applyopenport, applyinstallsoft, usersign, userid,
				usersigndate, deptleaderopinion, deptleadersign, deptleaderid,
				leadersigndate, isupdate, updateversion, openport, installsoft,
				operator1, operatorid1, operatordate1, receiver, receiverid,
				receiverdate, checkcondition, transfersign, transferid,
				checkersign, checkerid, checkersigndate, portcondition,
				operator2, operatorid2, operatordate2, securityopinion,
				securitysign, securityid, securitysigndate);
	}

}
