package com.manage.temp.model;

import com.manage.temp.model.original.AbstractASyspermissioninfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * ASyspermissioninfoTab generated by MyEclipse Persistence Tools
 */
public class ASyspermissioninfoTab extends AbstractASyspermissioninfoTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ASyspermissioninfoTab() {
	}

	/** minimal constructor */
	public ASyspermissioninfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ASyspermissioninfoTab(Integer id, Integer version, Integer aid,
			String appsysname, String nowuserright, String afteruserright) {
		super(id, version, aid, appsysname, nowuserright, afteruserright);
	}

}
