package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractATelltalerecordTab;

/**
 * ATelltalerecordTab generated by MyEclipse Persistence Tools
 */
public class ATelltalerecordTab extends AbstractATelltalerecordTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ATelltalerecordTab() {
	}

	/** minimal constructor */
	public ATelltalerecordTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ATelltalerecordTab(Integer id, Integer version, Integer eventtype,
			Date happendate, String happenreason, String effectrange,
			String measures, String result, String informant,
			Integer informantid, String checker, Integer checkerid) {
		super(id, version, eventtype, happendate, happenreason, effectrange,
				measures, result, informant, informantid, checker, checkerid);
	}

}
