package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSClassifieddestroyTab;

// Generated by MyEclipse Persistence Tools

/**
 * SClassifieddestroyTab generated by MyEclipse Persistence Tools
 */
public class SClassifieddestroyTab extends AbstractSClassifieddestroyTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SClassifieddestroyTab() {
	}

	/** minimal constructor */
	public SClassifieddestroyTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SClassifieddestroyTab(Integer id, Integer version, String orgid,
			String orgname, String dcode,Integer total, String destroyname,
			Integer destroyid, String approvename, Integer approveid,
			String receivename, Integer receiveid) {
		super(id, version, orgid, orgname, dcode,total, destroyname, destroyid, approvename,
				approveid, receivename, receiveid);
	}

}
