package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSDetainstandardTab;

// Generated by MyEclipse Persistence Tools

/**
 * SDetainstandardTab generated by MyEclipse Persistence Tools
 */
public class SDetainstandardTab extends AbstractSDetainstandardTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SDetainstandardTab() {
	}

	/** minimal constructor */
	public SDetainstandardTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SDetainstandardTab(Integer id, Integer version, String truancy,
			String selfcheck, String nopass, String abroad, String leaks,
			String retaliation, String destructionequip, String refusecheck,
			String randomdense, String mrandomdense, String distributionscope,
			String transforclassified, String borrowing, String intensivelogo,
			String carryout, String jmcarryout, String printzl,
			String confidentiality, String storecarrier, String kconfidential,
			String keepjm, String bmbsybg, String xhdj, String xhgrq,
			String syhysb, String confregist, String xhzlwj, String gbsj,
			String videos, String inforprocess, String formatting,
			String dellog, String bmbs, String cysmdj, String aqbmcp,
			String maintenance, String azcc, String wbsb, String fsfunction,
			String storeinfor, String conmp, String dmjmedium, String usegmj,
			String middleconver, String isolatesocket, String carrymedium,
			String bmjcmedium, String checkinfor, String clsw,
			String grconmedium, String classifiedequip, String noclogo,
			String wirelesscon, String mprocess, String uwire,
			String ucommunication, String mobileinto, String umobile,
			String mobilelx, String faxcopy, String deliveryinfor,
			String receiveinterview, String wbmzg, String wqbmxy, String jsyq,
			String jdjc, String wsjd, String wfbmjl, String wjcr,
			String zlwjsp, String kdcgfw, String ayzc, String qkbss,
			String cssmhd) {
		super(id, version, truancy, selfcheck, nopass, abroad, leaks,
				retaliation, destructionequip, refusecheck, randomdense,
				mrandomdense, distributionscope, transforclassified, borrowing,
				intensivelogo, carryout, jmcarryout, printzl, confidentiality,
				storecarrier, kconfidential, keepjm, bmbsybg, xhdj, xhgrq,
				syhysb, confregist, xhzlwj, gbsj, videos, inforprocess,
				formatting, dellog, bmbs, cysmdj, aqbmcp, maintenance, azcc,
				wbsb, fsfunction, storeinfor, conmp, dmjmedium, usegmj,
				middleconver, isolatesocket, carrymedium, bmjcmedium,
				checkinfor, clsw, grconmedium, classifiedequip, noclogo,
				wirelesscon, mprocess, uwire, ucommunication, mobileinto,
				umobile, mobilelx, faxcopy, deliveryinfor, receiveinterview,
				wbmzg, wqbmxy, jsyq, jdjc, wsjd, wfbmjl, wjcr, zlwjsp, kdcgfw,
				ayzc, qkbss, cssmhd);
	}

}
