package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSDivulgesecretTab;

/**
 * SDivulgesecretTab generated by MyEclipse Persistence Tools
 */
public class SDivulgesecretTab extends AbstractSDivulgesecretTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SDivulgesecretTab() {
	}

	/** minimal constructor */
	public SDivulgesecretTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SDivulgesecretTab(Integer id, Integer version, String deptname,
			Integer deptid, Date finddate, String findplace, String finder,
			String finderposition, String briefproc, String party,
			String partyposition, Date happendate, String happenplace,
			String divulgetype, Integer divulgesec, String briefcondition,
			String harm, String workcondition, String measures,
			String deptopinion, String deptleadersign, Integer deptleaderid,
			Date leadersigndate, String sofficedesc, String sofficesign,
			Integer sofficeid, Date sofficedate) {
		super(id, version, deptname, deptid, finddate, findplace, finder,
				finderposition, briefproc, party, partyposition, happendate,
				happenplace, divulgetype, divulgesec, briefcondition, harm,
				workcondition, measures, deptopinion, deptleadersign,
				deptleaderid, leadersigndate, sofficedesc, sofficesign,
				sofficeid, sofficedate);
	}

}
