package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSEmpseccheckTab;

/**
 * SEmpseccheckTab generated by MyEclipse Persistence Tools
 */
public class SEmpseccheckTab extends AbstractSEmpseccheckTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SEmpseccheckTab() {
	}

	/** minimal constructor */
	public SEmpseccheckTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SEmpseccheckTab(Integer id, Integer version, String confidentiality,
			String education, String setpwd, String maintenance,
			String atinternet, String cymj, String classifiedsecret,
			String matnternet, String savepwdark, String perprocedure,
			String onlineregist, String handleaffairs, String smedia,
			String inforpublish, String timelyrepel, String ttbcsd, String rsd,
			String recordtz, String kconfidentiality, String phandleaffairs,
			String pconmedium, String pclassified, String ransforieinfor,
			String abroad, String cleartable, String otherinfor,
			String rectification, Date cdate, String cname, Integer cid) {
		super(id, version, confidentiality, education, setpwd, maintenance,
				atinternet, cymj, classifiedsecret, matnternet, savepwdark,
				perprocedure, onlineregist, handleaffairs, smedia,
				inforpublish, timelyrepel, ttbcsd, rsd, recordtz,
				kconfidentiality, phandleaffairs, pconmedium, pclassified,
				ransforieinfor, abroad, cleartable, otherinfor, rectification,
				cdate, cname, cid);
	}

}
