package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSForeignguestsinfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SForeignguestsinfoTab generated by MyEclipse Persistence Tools
 */
public class SForeignguestsinfoTab extends AbstractSForeignguestsinfoTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SForeignguestsinfoTab() {
	}

	/** minimal constructor */
	public SForeignguestsinfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SForeignguestsinfoTab(Integer id, Integer version, Integer oaid,
			String cname, String ename, String nationality, String passportno,
			String duties, Integer comenum, String remark) {
		super(id, version, oaid, cname, ename, nationality, passportno, duties,
				comenum, remark);
	}

}
