package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSOpenapplyTab;

/**
 * SOpenapplyTab generated by MyEclipse Persistence Tools
 */
public class SOpenapplyTab extends AbstractSOpenapplyTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SOpenapplyTab() {
	}

	/** minimal constructor */
	public SOpenapplyTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SOpenapplyTab(Integer id, Integer version, String deptname,
			Integer deptid, Date formdate, String teamname, String invitedept,
			String purpose, Date lfdate, String linkman, String linktel,
			String cellphone,
			String cryptosecurity, String rewsopinion, String rebmopinion,
			String respopinion, String gswsopinion, String gsbmopinion,
			String gsspopinion, String groupcompany) {
		super(id, version, deptname, deptid, formdate, teamname, invitedept,
				purpose, lfdate, linkman, linktel, cellphone,
				cryptosecurity, rewsopinion, rebmopinion, respopinion,
				gswsopinion, gsbmopinion, gsspopinion, groupcompany);
	}

}
