package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSQuartersubsidiesTab;

/**
 * SQuartersubsidiesTab generated by MyEclipse Persistence Tools
 */
public class SQuartersubsidiesTab extends AbstractSQuartersubsidiesTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SQuartersubsidiesTab() {
	}

	/** minimal constructor */
	public SQuartersubsidiesTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SQuartersubsidiesTab(Integer id, Integer version, String orgname,
			String orgid,  Double sftotalamount,
			String departmentdesc, Date departmentdate, String sofficedesc,
			Integer sofficeid, Date sofficedate) {
		super(id, version, orgname, orgid, 
				sftotalamount, departmentdesc, departmentdate, sofficedesc,
				sofficeid, sofficedate);
	}

}
