package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSSecalertrecordTab;

/**
 * SSecalertrecordTab generated by MyEclipse Persistence Tools
 */
public class SSecalertrecordTab extends AbstractSSecalertrecordTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SSecalertrecordTab() {
	}

	/** minimal constructor */
	public SSecalertrecordTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SSecalertrecordTab(Integer id, Integer version, Date begindate,
			Date enddate, String activityname, String cborgopinion,
			String cbleader, Date cbleaderdate, Integer cbleaderid,
			String securityopinion, String securitysign, Integer securityid,
			Date securitysigndate) {
		super(id, version, begindate, enddate, activityname, cborgopinion, cbleader, cbleaderdate,
				cbleaderid, securityopinion, securitysign, securityid,
				securitysigndate);
	}

}
