package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSStoragemediumInfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SStoragemediumInfoTab generated by MyEclipse Persistence Tools
 */
public class SStoragemediumInfoTab extends AbstractSStoragemediumInfoTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SStoragemediumInfoTab() {
	}

	/** minimal constructor */
	public SStoragemediumInfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SStoragemediumInfoTab(Integer id, Integer version, Integer eid,
			Integer qmediumtype, String qspecifications,
			String qclassification, Integer qnum, Integer qcerttype,
			String qusrange) {
		super(id, version, eid, qmediumtype, qspecifications, qclassification,
				qnum, qcerttype, qusrange);
	}

}
