package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSSubsidiesdetainTab;

/**
 * SSubsidiesdetainTab generated by MyEclipse Persistence Tools
 */
public class SSubsidiesdetainTab extends AbstractSSubsidiesdetainTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SSubsidiesdetainTab() {
	}

	/** minimal constructor */
	public SSubsidiesdetainTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SSubsidiesdetainTab(Integer id, Integer version, String code,
			Date noticedate, String orgid, String orgname, String name,
			String detaindesc, String detainsign, Integer dsid, Date signdate,
			Double deductamount, Date detainstartdate, Date detainenddate,
			String promoter, Integer promoterid, Date promoterdate) {
		super(id, version, code, noticedate, orgid, orgname, name, detaindesc,
				detainsign, dsid, signdate, deductamount, detainstartdate,
				detainenddate, promoter, promoterid, promoterdate);
	}

}
