package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSSubsidiesdetainperTab;

/**
 * SSubsidiesdetainperTab generated by MyEclipse Persistence Tools
 */
public class SSubsidiesdetainperTab extends AbstractSSubsidiesdetainperTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SSubsidiesdetainperTab() {
	}

	/** minimal constructor */
	public SSubsidiesdetainperTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SSubsidiesdetainperTab(Integer id, Integer version, String pcode,
			Date pnoticedate, String orgname, String orgid, String pname,
			String pdetaindesc, String officesign, Integer officeid,
			Date signdate) {
		super(id, version, pcode, pnoticedate, orgname, orgid, pname,
				pdetaindesc, officesign, officeid, signdate);
	}

}
