package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSTochinasTab;

/**
 * STochinasTab generated by MyEclipse Persistence Tools
 */
public class STochinasTab extends AbstractSTochinasTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public STochinasTab() {
	}

	/** minimal constructor */
	public STochinasTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public STochinasTab(Integer id, Integer version, String num, Date formdate,
			String deptname, Integer deptsecrity, String country,
			String foreigdept, Integer foreigners, Date begindate,
			Date enddate, String superdept, String examinenum,
			String exchplace, String touchpart, String plansmeasur,
			String bmname, String cellphone, String reason,
			String formdept, String former, Integer formerid, String formertel) {
		super(id, version, num, formdate, deptname, deptsecrity, country,
				foreigdept, foreigners, begindate, enddate, superdept,
				examinenum, exchplace, touchpart, plansmeasur, bmname,
				cellphone, reason,  formdept,
				former, formerid, formertel);
	}

}
