package com.manage.equalification.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.equalification.model.original.AbstractSStudyworkTab;

/**
 * SStudyworkTab generated by MyEclipse Persistence Tools
 */
public class SStudyworkTab extends AbstractSStudyworkTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SStudyworkTab() {
	}

	/** minimal constructor */
	public SStudyworkTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SStudyworkTab(Integer id, Integer version, Integer eqid,
			Date wstartdate, Date wenddate, String workunit, String jobs,
			String position, String zmname) {
		super(id, version, eqid, wstartdate, wenddate, workunit, jobs,
				position, zmname);
	}

}
