package com.manage.ferrycentre.model;

import com.manage.ferrycentre.model.original.AbstractFerryCentre;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class FerryCentre extends AbstractFerryCentre {

}
