package com.manage.smediumborrow.model.original;

import java.util.Date;

/**
 * AbstractSSmediumborrowTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSSmediumborrowTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String scode;
	private String orgname;
	private String orgid;
	private String bname;
	private Integer bid;
	private String borrowreason;
	private String mcode;
	private Integer mclassifition;
	private Date usedate;
	private String dcode;
	private String information;
	private String imaxclassified;
	private String departmentdesc;
	private Date departmentdate;
	private String officedesc;
	private Date officedate;
	private String cleardesc;
	private Date cleardate;
	private Date applydate;
	private String username;
	private Integer userid;
	private String mark;

	// Constructors

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSSmediumborrowTab() {
	}

	/** minimal constructor */
	public AbstractSSmediumborrowTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSSmediumborrowTab(Integer id, Integer version, String scode,
			String orgname, String orgid, String bname, Integer bid,
			String borrowreason, String mcode, Integer mclassifition,
			Date usedate, String dcode, String information,
			String imaxclassified, String departmentdesc, Date departmentdate,
			String officedesc, Date officedate, String cleardesc,
			Date cleardate, Date applydate,String username,Integer userid,String mark) {
		this.id = id;
		this.version = version;
		this.scode = scode;
		this.orgname = orgname;
		this.orgid = orgid;
		this.bname = bname;
		this.bid = bid;
		this.borrowreason = borrowreason;
		this.mcode = mcode;
		this.mclassifition = mclassifition;
		this.usedate = usedate;
		this.dcode = dcode;
		this.information = information;
		this.imaxclassified = imaxclassified;
		this.departmentdesc = departmentdesc;
		this.departmentdate = departmentdate;
		this.officedesc = officedesc;
		this.officedate = officedate;
		this.cleardesc = cleardesc;
		this.cleardate = cleardate;
		this.applydate = applydate;
		this.username = username;
		this.userid = userid;
		this.mark = mark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getScode() {
		return this.scode;
	}

	public void setScode(String scode) {
		this.scode = scode;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getBname() {
		return this.bname;
	}

	public void setBname(String bname) {
		this.bname = bname;
	}

	public Integer getBid() {
		return this.bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	public String getBorrowreason() {
		return this.borrowreason;
	}

	public void setBorrowreason(String borrowreason) {
		this.borrowreason = borrowreason;
	}

	public String getMcode() {
		return this.mcode;
	}

	public void setMcode(String mcode) {
		this.mcode = mcode;
	}

	public Integer getMclassifition() {
		return this.mclassifition;
	}

	public void setMclassifition(Integer mclassifition) {
		this.mclassifition = mclassifition;
	}

	public Date getUsedate() {
		return this.usedate;
	}

	public void setUsedate(Date usedate) {
		this.usedate = usedate;
	}

	public String getDcode() {
		return this.dcode;
	}

	public void setDcode(String dcode) {
		this.dcode = dcode;
	}

	public String getInformation() {
		return this.information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	public String getImaxclassified() {
		return this.imaxclassified;
	}

	public void setImaxclassified(String imaxclassified) {
		this.imaxclassified = imaxclassified;
	}

	public String getDepartmentdesc() {
		return this.departmentdesc;
	}

	public void setDepartmentdesc(String departmentdesc) {
		this.departmentdesc = departmentdesc;
	}

	public Date getDepartmentdate() {
		return this.departmentdate;
	}

	public void setDepartmentdate(Date departmentdate) {
		this.departmentdate = departmentdate;
	}

	public String getOfficedesc() {
		return this.officedesc;
	}

	public void setOfficedesc(String officedesc) {
		this.officedesc = officedesc;
	}

	public Date getOfficedate() {
		return this.officedate;
	}

	public void setOfficedate(Date officedate) {
		this.officedate = officedate;
	}

	public String getCleardesc() {
		return this.cleardesc;
	}

	public void setCleardesc(String cleardesc) {
		this.cleardesc = cleardesc;
	}

	public Date getCleardate() {
		return this.cleardate;
	}

	public void setCleardate(Date cleardate) {
		this.cleardate = cleardate;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

}