package com.manage.classifiedcopy.model;

import com.manage.classifiedcopy.model.original.AbstractSCarriercontentTab;

// Generated by MyEclipse Persistence Tools

/**
 * SCarriercontentTab generated by MyEclipse Persistence Tools
 */
public class SCarriercontentTab extends AbstractSCarriercontentTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SCarriercontentTab() {
	}

	/** minimal constructor */
	public SCarriercontentTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SCarriercontentTab(Integer id, Integer version, Integer cid,
			String contents, Integer fs, Integer zys, Integer classification,
			String zyh) {
		super(id, version, cid, contents, fs, zys, classification, zyh);
	}

}
