package com.manage.securityedu.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.securityedu.model.original.AbstractSSecurityeduTab;

/**
 * SSecurityeduTab generated by MyEclipse Persistence Tools
 */
public class SSecurityeduTab extends AbstractSSecurityeduTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SSecurityeduTab() {
	}

	/** minimal constructor */
	public SSecurityeduTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SSecurityeduTab(Integer id, Integer version, String orgname,
			String orgid, String name, Integer classification,
			String educationdesc, String sign, Date signdate, String rname,
			Integer reid, Date redate,String username,Integer userid) {
		super(id, version, orgname, orgid, name, classification, educationdesc,
				sign, signdate, rname, reid, redate,username,userid);
	}

}
