package com.manage.applykeypart.model.original;

/**
 * AbstractSMigrantsioTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSMigrantsioTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer aid;
	private String name;
	private String jobs;
	private String workunit;

	// Constructors

	/** default constructor */
	public AbstractSMigrantsioTab() {
	}

	/** minimal constructor */
	public AbstractSMigrantsioTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSMigrantsioTab(Integer id, Integer version, Integer aid,
			String name, String jobs, String workunit) {
		this.id = id;
		this.version = version;
		this.aid = aid;
		this.name = name;
		this.jobs = jobs;
		this.workunit = workunit;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJobs() {
		return this.jobs;
	}

	public void setJobs(String jobs) {
		this.jobs = jobs;
	}

	public String getWorkunit() {
		return this.workunit;
	}

	public void setWorkunit(String workunit) {
		this.workunit = workunit;
	}

}