package com.manage.subsidiesdetain.model;

import com.manage.subsidiesdetain.model.original.AbstractSubsidiesDetain;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class SubsidiesDetain extends AbstractSubsidiesDetain {

}
