package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAAlterusbkeyTab;

/**
 * AAlterusbkeyTab generated by MyEclipse Persistence Tools
 */
public class AAlterusbkeyTab extends AbstractAAlterusbkeyTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AAlterusbkeyTab() {
	}

	/** minimal constructor */
	public AAlterusbkeyTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AAlterusbkeyTab(Integer id, Integer version, String name,
			String position, String deptname, Integer deptid, Integer security,
			String workplace, String cellphone, Integer alterreason,
			String definitereason, String applicantsign, Integer applicantid,
			Date applydate, String deptopinion, String deptsign,
			Integer deptsignid, Date deptsigndate, String securityopinion,
			String securitysign, Integer securityid, Date securitysigndate,
			String infordeptopinion, String infordeptsign,
			Integer infordeptsignid, Date infordeptsigndate,
			String trancondition, String transign, Integer transignid,
			Date transigndate) {
		super(id, version, name, position, deptname, deptid, security,
				workplace, cellphone, alterreason, definitereason,
				applicantsign, applicantid, applydate, deptopinion, deptsign,
				deptsignid, deptsigndate, securityopinion, securitysign,
				securityid, securitysigndate, infordeptopinion, infordeptsign,
				infordeptsignid, infordeptsigndate, trancondition, transign,
				transignid, transigndate);
	}

}
