package com.manage.classifiedrecord.model.original;

import java.util.Date;

/**
 * AbstractSClassifiedcopySupervisionTab generated by MyEclipse Persistence
 * Tools
 */

public abstract class AbstractSClassifiedcopySupervisionTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String cuname;
	private String orgid;
	private String orgname;
	private Date cdate;
	private String caddress;
	private String cname;
	private String bmname;
	private Integer isapproval;
	private Integer isdcopy;
	private Integer issignsec;
	private Integer isconrequire;
	private String note;
	private Integer isback;
	private Integer bcopies;
	private Integer ismark;
	private Integer printnum;
	private Integer renum;
	private Integer iscountrecycle;
	private String handling;
	private Integer isdelete;
	private String supervisor;
	private String departmentsign;
	private Integer departmentid;
	private Date departmentdate;
	private String officedesc;
	private String officesign;
	private Integer officeid;
	private Date officedate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSClassifiedcopySupervisionTab() {
	}

	/** minimal constructor */
	public AbstractSClassifiedcopySupervisionTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSClassifiedcopySupervisionTab(Integer id, Integer version,
			String cuname, String orgid, String orgname, Date cdate,
			String caddress, String cname, String bmname, Integer isapproval,
			Integer isdcopy, Integer issignsec, Integer isconrequire,
			String note, Integer isback, Integer bcopies, Integer ismark,
			Integer printnum, Integer renum, Integer iscountrecycle,
			String handling, Integer isdelete, String supervisor,
			String departmentsign, Integer departmentid, Date departmentdate,
			String officedesc, String officesign, Integer officeid,
			Date officedate,String username,Integer userid) {
		this.id = id;
		this.version = version;
		this.cuname = cuname;
		this.orgid = orgid;
		this.orgname = orgname;
		this.cdate = cdate;
		this.caddress = caddress;
		this.cname = cname;
		this.bmname = bmname;
		this.isapproval = isapproval;
		this.isdcopy = isdcopy;
		this.issignsec = issignsec;
		this.isconrequire = isconrequire;
		this.note = note;
		this.isback = isback;
		this.bcopies = bcopies;
		this.ismark = ismark;
		this.printnum = printnum;
		this.renum = renum;
		this.iscountrecycle = iscountrecycle;
		this.handling = handling;
		this.isdelete = isdelete;
		this.supervisor = supervisor;
		this.departmentsign = departmentsign;
		this.departmentid = departmentid;
		this.departmentdate = departmentdate;
		this.officedesc = officedesc;
		this.officesign = officesign;
		this.officeid = officeid;
		this.officedate = officedate;
		this.username = username;
		this.userid = userid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCuname() {
		return this.cuname;
	}

	public void setCuname(String cuname) {
		this.cuname = cuname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public String getCaddress() {
		return this.caddress;
	}

	public void setCaddress(String caddress) {
		this.caddress = caddress;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getBmname() {
		return this.bmname;
	}

	public void setBmname(String bmname) {
		this.bmname = bmname;
	}

	public Integer getIsapproval() {
		return this.isapproval;
	}

	public void setIsapproval(Integer isapproval) {
		this.isapproval = isapproval;
	}

	public Integer getIsdcopy() {
		return this.isdcopy;
	}

	public void setIsdcopy(Integer isdcopy) {
		this.isdcopy = isdcopy;
	}

	public Integer getIssignsec() {
		return this.issignsec;
	}

	public void setIssignsec(Integer issignsec) {
		this.issignsec = issignsec;
	}

	public Integer getIsconrequire() {
		return this.isconrequire;
	}

	public void setIsconrequire(Integer isconrequire) {
		this.isconrequire = isconrequire;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getIsback() {
		return this.isback;
	}

	public void setIsback(Integer isback) {
		this.isback = isback;
	}

	public Integer getBcopies() {
		return this.bcopies;
	}

	public void setBcopies(Integer bcopies) {
		this.bcopies = bcopies;
	}

	public Integer getIsmark() {
		return this.ismark;
	}

	public void setIsmark(Integer ismark) {
		this.ismark = ismark;
	}

	public Integer getPrintnum() {
		return this.printnum;
	}

	public void setPrintnum(Integer printnum) {
		this.printnum = printnum;
	}

	public Integer getRenum() {
		return this.renum;
	}

	public void setRenum(Integer renum) {
		this.renum = renum;
	}

	public Integer getIscountrecycle() {
		return this.iscountrecycle;
	}

	public void setIscountrecycle(Integer iscountrecycle) {
		this.iscountrecycle = iscountrecycle;
	}

	public String getHandling() {
		return this.handling;
	}

	public void setHandling(String handling) {
		this.handling = handling;
	}

	public Integer getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	public String getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(String supervisor) {
		this.supervisor = supervisor;
	}

	public String getDepartmentsign() {
		return this.departmentsign;
	}

	public void setDepartmentsign(String departmentsign) {
		this.departmentsign = departmentsign;
	}

	public Integer getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public Date getDepartmentdate() {
		return this.departmentdate;
	}

	public void setDepartmentdate(Date departmentdate) {
		this.departmentdate = departmentdate;
	}

	public String getOfficedesc() {
		return this.officedesc;
	}

	public void setOfficedesc(String officedesc) {
		this.officedesc = officedesc;
	}

	public String getOfficesign() {
		return this.officesign;
	}

	public void setOfficesign(String officesign) {
		this.officesign = officesign;
	}

	public Integer getOfficeid() {
		return this.officeid;
	}

	public void setOfficeid(Integer officeid) {
		this.officeid = officeid;
	}

	public Date getOfficedate() {
		return this.officedate;
	}

	public void setOfficedate(Date officedate) {
		this.officedate = officedate;
	}

}