package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractASysconfigalterTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractASysconfigalterTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String applicant;
	private Integer applicantid;
	private Date applydate;
	private String devorsysname;
	private String alterreason;
	private String contentanalyze;
	private String infordeptopinion;
	private String infordeptsign;
	private Integer infordeptsignid;
	private Date infordeptsigndate;
	private String securityopinion;
	private String securitysign;
	private Integer securityid;
	private Date securitysigndate;
	private String resultanalyze;
	private String operatorsign;
	private Integer operatorid;
	private Date operatorsigndate;

	// Constructors

	/** default constructor */
	public AbstractASysconfigalterTab() {
	}

	/** minimal constructor */
	public AbstractASysconfigalterTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractASysconfigalterTab(Integer id, Integer version,
			String applicant, Integer applicantid, Date applydate,
			String devorsysname, String alterreason, String contentanalyze,
			String infordeptopinion, String infordeptsign,
			Integer infordeptsignid, Date infordeptsigndate,
			String securityopinion, String securitysign, Integer securityid,
			Date securitysigndate, String resultanalyze, String operatorsign,
			Integer operatorid, Date operatorsigndate) {
		this.id = id;
		this.version = version;
		this.applicant = applicant;
		this.applicantid = applicantid;
		this.applydate = applydate;
		this.devorsysname = devorsysname;
		this.alterreason = alterreason;
		this.contentanalyze = contentanalyze;
		this.infordeptopinion = infordeptopinion;
		this.infordeptsign = infordeptsign;
		this.infordeptsignid = infordeptsignid;
		this.infordeptsigndate = infordeptsigndate;
		this.securityopinion = securityopinion;
		this.securitysign = securitysign;
		this.securityid = securityid;
		this.securitysigndate = securitysigndate;
		this.resultanalyze = resultanalyze;
		this.operatorsign = operatorsign;
		this.operatorid = operatorid;
		this.operatorsigndate = operatorsigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public Integer getApplicantid() {
		return this.applicantid;
	}

	public void setApplicantid(Integer applicantid) {
		this.applicantid = applicantid;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getDevorsysname() {
		return this.devorsysname;
	}

	public void setDevorsysname(String devorsysname) {
		this.devorsysname = devorsysname;
	}

	public String getAlterreason() {
		return this.alterreason;
	}

	public void setAlterreason(String alterreason) {
		this.alterreason = alterreason;
	}

	public String getContentanalyze() {
		return this.contentanalyze;
	}

	public void setContentanalyze(String contentanalyze) {
		this.contentanalyze = contentanalyze;
	}

	public String getInfordeptopinion() {
		return this.infordeptopinion;
	}

	public void setInfordeptopinion(String infordeptopinion) {
		this.infordeptopinion = infordeptopinion;
	}

	public String getInfordeptsign() {
		return this.infordeptsign;
	}

	public void setInfordeptsign(String infordeptsign) {
		this.infordeptsign = infordeptsign;
	}

	public Integer getInfordeptsignid() {
		return this.infordeptsignid;
	}

	public void setInfordeptsignid(Integer infordeptsignid) {
		this.infordeptsignid = infordeptsignid;
	}

	public Date getInfordeptsigndate() {
		return this.infordeptsigndate;
	}

	public void setInfordeptsigndate(Date infordeptsigndate) {
		this.infordeptsigndate = infordeptsigndate;
	}

	public String getSecurityopinion() {
		return this.securityopinion;
	}

	public void setSecurityopinion(String securityopinion) {
		this.securityopinion = securityopinion;
	}

	public String getSecuritysign() {
		return this.securitysign;
	}

	public void setSecuritysign(String securitysign) {
		this.securitysign = securitysign;
	}

	public Integer getSecurityid() {
		return this.securityid;
	}

	public void setSecurityid(Integer securityid) {
		this.securityid = securityid;
	}

	public Date getSecuritysigndate() {
		return this.securitysigndate;
	}

	public void setSecuritysigndate(Date securitysigndate) {
		this.securitysigndate = securitysigndate;
	}

	public String getResultanalyze() {
		return this.resultanalyze;
	}

	public void setResultanalyze(String resultanalyze) {
		this.resultanalyze = resultanalyze;
	}

	public String getOperatorsign() {
		return this.operatorsign;
	}

	public void setOperatorsign(String operatorsign) {
		this.operatorsign = operatorsign;
	}

	public Integer getOperatorid() {
		return this.operatorid;
	}

	public void setOperatorid(Integer operatorid) {
		this.operatorid = operatorid;
	}

	public Date getOperatorsigndate() {
		return this.operatorsigndate;
	}

	public void setOperatorsigndate(Date operatorsigndate) {
		this.operatorsigndate = operatorsigndate;
	}

}