package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSSecalertrecordTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSSecalertrecordTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Date begindate;
	private Date enddate;
	private String activityname;
	private String cborgopinion;
	private String cbleader;
	private Date cbleaderdate;
	private Integer cbleaderid;
	private String securityopinion;
	private String securitysign;
	private Integer securityid;
	private Date securitysigndate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSSecalertrecordTab() {
	}

	/** minimal constructor */
	public AbstractSSecalertrecordTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSSecalertrecordTab(Integer id, Integer version,
			Date begindate, Date enddate, String activityname,
			String cborgopinion, String cbleader, Date cbleaderdate,
			Integer cbleaderid, String securityopinion, String securitysign,
			Integer securityid, Date securitysigndate) {
		this.id = id;
		this.version = version;
		this.begindate = begindate;
		this.enddate = enddate;
		this.activityname = activityname;
		this.cborgopinion = cborgopinion;
		this.cbleader = cbleader;
		this.cbleaderdate = cbleaderdate;
		this.cbleaderid = cbleaderid;
		this.securityopinion = securityopinion;
		this.securitysign = securitysign;
		this.securityid = securityid;
		this.securitysigndate = securitysigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Date getBegindate() {
		return this.begindate;
	}

	public void setBegindate(Date begindate) {
		this.begindate = begindate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public String getActivityname() {
		return this.activityname;
	}

	public void setActivityname(String activityname) {
		this.activityname = activityname;
	}


	public String getCborgopinion() {
		return this.cborgopinion;
	}

	public void setCborgopinion(String cborgopinion) {
		this.cborgopinion = cborgopinion;
	}

	public String getCbleader() {
		return this.cbleader;
	}

	public void setCbleader(String cbleader) {
		this.cbleader = cbleader;
	}

	public Date getCbleaderdate() {
		return this.cbleaderdate;
	}

	public void setCbleaderdate(Date cbleaderdate) {
		this.cbleaderdate = cbleaderdate;
	}

	public Integer getCbleaderid() {
		return this.cbleaderid;
	}

	public void setCbleaderid(Integer cbleaderid) {
		this.cbleaderid = cbleaderid;
	}

	public String getSecurityopinion() {
		return this.securityopinion;
	}

	public void setSecurityopinion(String securityopinion) {
		this.securityopinion = securityopinion;
	}

	public String getSecuritysign() {
		return this.securitysign;
	}

	public void setSecuritysign(String securitysign) {
		this.securitysign = securitysign;
	}

	public Integer getSecurityid() {
		return this.securityid;
	}

	public void setSecurityid(Integer securityid) {
		this.securityid = securityid;
	}

	public Date getSecuritysigndate() {
		return this.securitysigndate;
	}

	public void setSecuritysigndate(Date securitysigndate) {
		this.securitysigndate = securitysigndate;
	}

}