package com.manage.vregist.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.vregist.model.original.AbstractSVregistTab;

/**
 * SVregistTab generated by MyEclipse Persistence Tools
 */
public class SVregistTab extends AbstractSVregistTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SVregistTab() {
	}

	/** minimal constructor */
	public SVregistTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SVregistTab(Integer id, Integer version, String partname,
			String roomcode, Date recordstartdate, Date recordenddate,String username,Integer userid) {
		super(id, version, partname, roomcode, recordstartdate, recordenddate,username,userid);
	}

}
