package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSOpeninfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SOpeninfoTab generated by MyEclipse Persistence Tools
 */
public class SOpeninfoTab extends AbstractSOpeninfoTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SOpeninfoTab() {
	}

	/** minimal constructor */
	public SOpeninfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SOpeninfoTab(Integer id, Integer version, Integer oaid,
			String partnum, String major, String species, String device,
			String purpose) {
		super(id, version, oaid, partnum, major, species, device, purpose);
	}

}
