package com.manage.conagreement.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.conagreement.model.original.AbstractSConagreementTab;

/**
 * SConagreementTab generated by MyEclipse Persistence Tools
 */
public class SConagreementTab extends AbstractSConagreementTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SConagreementTab() {
	}

	/** minimal constructor */
	public SConagreementTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SConagreementTab(Integer id, Integer version, String jfname,
			String yfname, String jfsign, Integer jfid, String yfsign,
			Integer yfid, Date jfdate, Date yfdate,String username,Integer userid) {
		super(id, version, jfname, yfname, jfsign, jfid, yfsign, yfid, jfdate,
				yfdate,username,userid);
	}

}
