package com.manage.classifiedtz.model;

import com.manage.classifiedtz.model.original.AbstractSClassifiedtzInfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SClassifiedtzInfoTab generated by MyEclipse Persistence Tools
 */
public class SClassifiedtzInfoTab extends AbstractSClassifiedtzInfoTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SClassifiedtzInfoTab() {
	}

	/** minimal constructor */
	public SClassifiedtzInfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SClassifiedtzInfoTab(Integer id, Integer version, Integer ctzid,
			String filename, String productunit, Integer carriertype,
			String code, String classification, Integer pages, Integer copies,
			String usrange, String note) {
		super(id, version, ctzid, filename, productunit, carriertype, code,
				classification, pages, copies, usrange, note);
	}

}
