package com.manage.informationpublish.model;

import com.manage.informationpublish.model.original.AbstractInformationPublish;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class InformationPublish extends AbstractInformationPublish {

}
