package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSCooperationcheckTab;

/**
 * SCooperationcheckTab generated by MyEclipse Persistence Tools
 */
public class SCooperationcheckTab extends AbstractSCooperationcheckTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SCooperationcheckTab() {
	}

	/** minimal constructor */
	public SCooperationcheckTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SCooperationcheckTab(Integer id, Integer version, String deptname,
			String enterprisepro, String legalpers, String supedept,
			String mailaddress, String postcode, String cellphone, String fax,
			String securitydept, String bmtel, Integer checktype,
			Integer deptbelong, String belongelse, Date begindate,
			Date enddate, Integer isorgperfect, Integer isauthorclear,
			Integer issysclear, Integer ishavesys, Integer isflowclear,
			Integer issecident, Integer isstrictcheck, Integer issecedu,
			Integer issigndoc, Integer isprocright, Integer isstandard,
			Integer isaccordgd, Integer ismeasure, Integer isconfdept,
			Integer isdeptperfect, Integer iseffeaction, Integer isisolation,
			Integer isdutyclear, Integer iscontrol, Integer isfoxcontrol,
			Integer issecwork, Integer iskeep, Integer isszcopy,
			Integer isusecarrier, Integer iscorrect, Integer ishappen,
			String checkcondition, String orgsign, Integer orgsignid,
			Date orgdate, String xzdeptprom, String fgleader,
			Integer fgleaderid, Date fgsigndate, String checkopinion,
			String deptleader, Integer deptleaderid, Date leaderdate) {
		super(id, version, deptname, enterprisepro, legalpers, supedept,
				mailaddress, postcode, cellphone, fax, securitydept, bmtel,
				checktype, deptbelong, belongelse, begindate, enddate,
				isorgperfect, isauthorclear, issysclear, ishavesys,
				isflowclear, issecident, isstrictcheck, issecedu, issigndoc,
				isprocright, isstandard, isaccordgd, ismeasure, isconfdept,
				isdeptperfect, iseffeaction, isisolation, isdutyclear,
				iscontrol, isfoxcontrol, issecwork, iskeep, isszcopy,
				isusecarrier, iscorrect, ishappen, checkcondition, orgsign,
				orgsignid, orgdate, xzdeptprom, fgleader, fgleaderid,
				fgsigndate, checkopinion, deptleader, deptleaderid, leaderdate);
	}

}
