package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAInternetaccountTab;

/**
 * AInternetaccountTab generated by MyEclipse Persistence Tools
 */
public class AInternetaccountTab extends AbstractAInternetaccountTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AInternetaccountTab() {
	}

	/** minimal constructor */
	public AInternetaccountTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AInternetaccountTab(Integer id, Integer version, String applicant,
			Integer applicantid, String deptname, Integer deptid,
			String userlist, String linkman, String cellphone,
			String openreason, String revokereason, String applydeptopinion,
			String applydeptsign, Integer applydeptsignid,
			Date applydeptsigndate, String dutyofficer, Integer dutyofficerid,
			Date dutyofficerdate, Integer isfinish, String operatrecord,
			String recorder, Integer recorderid, Date recorddate) {
		super(id, version, applicant, applicantid, deptname, deptid, userlist,
				linkman, cellphone, openreason, revokereason, applydeptopinion,
				applydeptsign, applydeptsignid, applydeptsigndate, dutyofficer,
				dutyofficerid, dutyofficerdate, isfinish, operatrecord,
				recorder, recorderid, recorddate);
	}

}
