package com.manage.deviceinfo.model;

import com.manage.deviceinfo.model.original.AbstractDeviceInfo;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class DeviceInfo extends AbstractDeviceInfo {

}
