package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAEmailexamineTab;

/**
 * AEmailexamineTab generated by MyEclipse Persistence Tools
 */
public class AEmailexamineTab extends AbstractAEmailexamineTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AEmailexamineTab() {
	}

	/** minimal constructor */
	public AEmailexamineTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AEmailexamineTab(Integer id, Integer version, String deptname,
			Integer deptid, String applicant, Integer applicantid,
			String offices, Integer officesid, String linktype,
			String openreason, String revokereason, String applydeptopinion,
			String applydeptsign, Integer applydeptsignid,
			Date applydeptsigndate, String archivesdept, String archivessign,
			Integer archivesid, Date archivesdate, String operatrecord,
			String webmaster, Integer webmasterid, Date webmasterdate) {
		super(id, version, deptname, deptid, applicant, applicantid, offices,
				officesid, linktype, openreason, revokereason,
				applydeptopinion, applydeptsign, applydeptsignid,
				applydeptsigndate, archivesdept, archivessign, archivesid,
				archivesdate, operatrecord, webmaster, webmasterid,
				webmasterdate);
	}

}
