package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSForeignersvisitTab;

/**
 * SForeignersvisitTab generated by MyEclipse Persistence Tools
 */
public class SForeignersvisitTab extends AbstractSForeignersvisitTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SForeignersvisitTab() {
	}

	/** minimal constructor */
	public SForeignersvisitTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SForeignersvisitTab(Integer id, Integer version, String orgname,
			String orgid, String shead, String purpose, String personarea,
			String location, Date vdate, Integer isshoot,
			String confidentiality, String depdesc, String depsign,
			Integer depid, Date depdate, String officedesc, String officesign,
			Integer officeid, Date officedate) {
		super(id, version, orgname, orgid, shead, purpose, personarea,
				location, vdate, isshoot, confidentiality, depdesc, depsign,
				depid, depdate, officedesc, officesign, officeid, officedate);
	}

}
