package com.manage.confidentiality.model;

import com.manage.confidentiality.model.original.AbstractConfidentiality;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class Confidentiality extends AbstractConfidentiality {

}
