package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAOasysalterTab;

/**
 * AOasysalterTab generated by MyEclipse Persistence Tools
 */
public class AOasysalterTab extends AbstractAOasysalterTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AOasysalterTab() {
	}

	/** minimal constructor */
	public AOasysalterTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AOasysalterTab(Integer id, Integer version, Date formdate,
			String agent, String cellphone, String deptalter,
			String chushialter, String typeelse, String askfor,
			String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String officeopinion, String officesign, Integer officesignid,
			Date officesigndate, String investopinion, String investsign,
			Integer investsignid, Date investsigndate, String trancondition,
			String transign, Integer transignid, Date transigndate) {
		super(id, version, formdate, agent, cellphone, deptalter, chushialter,
				typeelse, askfor, applydeptopinion, applydeptsign,
				applydeptsignid, applydeptsigndate, officeopinion, officesign,
				officesignid, officesigndate, investopinion, investsign,
				investsignid, investsigndate, trancondition, transign,
				transignid, transigndate);
	}

}
