package com.manage.meetsecrecy.model;

import com.manage.meetsecrecy.model.original.AbstractMeetSecrecy;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class MeetSecrecy extends AbstractMeetSecrecy {

}
