package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSSecpersonnelTab;

// Generated by MyEclipse Persistence Tools

/**
 * SSecpersonnelTab generated by MyEclipse Persistence Tools
 */
public class SSecpersonnelTab extends AbstractSSecpersonnelTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SSecpersonnelTab() {
	}

	/** minimal constructor */
	public SSecpersonnelTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SSecpersonnelTab(Integer id, Integer version, Integer sid,
			String orgname, String orgid, String name) {
		super(id, version, sid, orgname, orgid, name);
	}

}
