package com.manage.user.model.original;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import com.base.framework.model.BaseObject;
import com.manage.user.model.User;

/**
 * UlmsUser generated by MyEclipse Persistence Tools
 */

public class UserAbstract extends BaseObject implements java.io.Serializable {

	// Fields

	protected Integer id;
	protected  Integer version;
	protected String name;
	protected String nickname;
	protected String realname;
	protected String password;
	protected Integer sex;
	protected Date birthday;
	protected String mail;
	protected String card;
	protected String phone;
	protected String cellphone;
	protected Integer diploma;
	protected Integer clan;
	protected String workunit;
	protected String address;
	protected String postcode;
	protected String headpicpath;
	protected Date workdate;
	protected Date createdate;
	protected Date updatedate;
	protected Date lastlogindate;
	protected Date accountoverdate;
	protected Date studyoverduedate;
	protected Integer isbathcard;
	protected String bathcardnum;
	protected String description;
	protected Integer isopen;
	protected String pwdquestion;
	protected String pwdanswer;
	protected Integer orgId;
	protected String orgName;
	protected Integer isgroup;
	protected Integer isManager;
	protected String roleNames;
	protected String importinfo;
	protected String importinfo1;

	// Constructors

	public String getImportinfo1() {
		return importinfo1;
	}

	public void setImportinfo1(String importinfo1) {
		this.importinfo1 = importinfo1;
	}

	public String getImportinfo() {
		return importinfo;
	}

	public void setImportinfo(String importinfo) {
		this.importinfo = importinfo;
	}

	/** default constructor */
	/*
	public UserAbstract() {
	}

	/** minimal constructor 
	public UserAbstract(String name, String nickname, String realname,
			String password, Date createdate, Date updatedate, Long isopen,
			Org org) {
		this.name = name;
		this.nickname = nickname;
		this.realname = realname;
		this.password = password;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.isopen = isopen;
		this.org = org;
	}

	/** full constructor 
	public UserAbstract(String name, String nickname, String realname,
			String password, Long sex, Date birthday, String mail,
			String card, String phone, String cellphone, Long diploma,
			Long clan, String workunit, String address, String postcode,
			String headpicpath, Date workdate, Date createdate,
			Date updatedate, Date lastlogindate, Date accountoverdate,
			Date studyoverduedate, Long isbathcard, Long bathcardnum,
			String description, Long isopen, Long pwdquestion,
			String pwdanswer, Integer version, Org org) {
		this.name = name;
		this.nickname = nickname;
		this.realname = realname;
		this.password = password;
		this.sex = sex;
		this.birthday = birthday;
		this.mail = mail;
		this.card = card;
		this.phone = phone;
		this.cellphone = cellphone;
		this.diploma = diploma;
		this.clan = clan;
		this.workunit = workunit;
		this.address = address;
		this.postcode = postcode;
		this.headpicpath = headpicpath;
		this.workdate = workdate;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.lastlogindate = lastlogindate;
		this.accountoverdate = accountoverdate;
		this.studyoverduedate = studyoverduedate;
		this.isbathcard = isbathcard;
		this.bathcardnum = bathcardnum;
		this.description = description;
		this.isopen = isopen;
		this.pwdquestion = pwdquestion;
		this.pwdanswer = pwdanswer;
		this.version = version;
		this.org = org;
	}
	*/
	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public Integer getDiploma() {
		return this.diploma;
	}

	public void setDiploma(Integer diploma) {
		this.diploma = diploma;
	}

	public Integer getClan() {
		return this.clan;
	}

	public void setClan(Integer clan) {
		this.clan = clan;
	}

	public String getWorkunit() {
		return this.workunit;
	}

	public void setWorkunit(String workunit) {
		this.workunit = workunit;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getHeadpicpath() {
		return this.headpicpath;
	}

	public void setHeadpicpath(String headpicpath) {
		this.headpicpath = headpicpath;
	}

	public Date getWorkdate() {
		return this.workdate;
	}

	public void setWorkdate(Date workdate) {
		this.workdate = workdate;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public Date getLastlogindate() {
		return this.lastlogindate;
	}

	public void setLastlogindate(Date lastlogindate) {
		this.lastlogindate = lastlogindate;
	}

	public Date getAccountoverdate() {
		return this.accountoverdate;
	}

	public void setAccountoverdate(Date accountoverdate) {
		this.accountoverdate = accountoverdate;
	}

	public Date getStudyoverduedate() {
		return this.studyoverduedate;
	}

	public void setStudyoverduedate(Date studyoverduedate) {
		this.studyoverduedate = studyoverduedate;
	}

	public Integer getIsbathcard() {
		return this.isbathcard;
	}

	public void setIsbathcard(Integer isbathcard) {
		this.isbathcard = isbathcard;
	}

	public String getBathcardnum() {
		return this.bathcardnum;
	}

	public void setBathcardnum(String bathcardnum) {
		this.bathcardnum = bathcardnum;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getIsopen() {
		return this.isopen;
	}

	public void setIsopen(Integer isopen) {
		this.isopen = isopen;
	}

	public String getPwdquestion() {
		return this.pwdquestion;
	}

	public void setPwdquestion(String pwdquestion) {
		this.pwdquestion = pwdquestion;
	}

	public String getPwdanswer() {
		return this.pwdanswer;
	}

	public void setPwdanswer(String pwdanswer) {
		this.pwdanswer = pwdanswer;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Override
	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof User) ) return false;
		User castOther = ( User ) other; 
		 
		return  ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) );
	}

	@Override
	public Serializable getPrimarykey() {
		return id;
	}

	@Override
	public int hashCode() {
		HashCodeBuilder hcb = new HashCodeBuilder(17, 37);
        hcb.append(getId());

        return hcb.toHashCode();
	}
	
	@Override
	public String toString() {
		ToStringBuilder tsb = new ToStringBuilder(ToStringStyle.DEFAULT_STYLE);
		tsb.append("id", id);
		tsb.append("name",name);
		return tsb.toString();
	}

	public Integer getOrgId() {
		return orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public Integer getIsgroup() {
		return isgroup;
	}

	public void setIsgroup(Integer isgroup) {
		this.isgroup = isgroup;
	}

	public Integer getIsManager() {
		return isManager;
	}

	public void setIsManager(Integer isManager) {
		this.isManager = isManager;
	}

	public String getRoleNames() {
		return roleNames;
	}

	public void setRoleNames(String roleNames) {
		this.roleNames = roleNames;
	}

 

}