package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractADevicemaintainTab;

/**
 * ADevicemaintainTab generated by MyEclipse Persistence Tools
 */
public class ADevicemaintainTab extends AbstractADevicemaintainTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ADevicemaintainTab() {
	}

	/** minimal constructor */
	public ADevicemaintainTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ADevicemaintainTab(Integer id, Integer version, String devprincipal,
			Integer devprincipalid, String orgname, String orgid,
			String devicename, String deviceindex, Integer devicesecurity,
			String faultdescribe, String devprincipalsign,
			Date devprincipaldate, String diagnosecase, String diagnosesign,
			Integer diagnoseid, Date diagnosedate, String applydeptopinion,
			String applydeptsign, Integer applydeptsignid,
			Date applydeptsigndate, String infordeptopinion,
			String infordeptsign, Integer infordeptsignid,
			Date infordeptsigndate, String hardpanserialnum, String mac,
			String faultreason, String maintainplace, String processmethod,
			String maintainresult, Date resysdate, String maintainsign,
			Integer maintainid, Date maintainsigndate, String accompansign,
			Date accompansigndate, String ohardpanserialnum,
			String transfersign, Integer transferid, String recipientsign,
			Integer recipientid, Date recipientsigndate, Integer isupdate,
			String managersign, Integer managerid, Date managersigndate) {
		super(id, version, devprincipal, devprincipalid, orgname, orgid,
				devicename, deviceindex, devicesecurity, faultdescribe,
				devprincipalsign, devprincipaldate, diagnosecase, diagnosesign,
				diagnoseid, diagnosedate, applydeptopinion, applydeptsign,
				applydeptsignid, applydeptsigndate, infordeptopinion,
				infordeptsign, infordeptsignid, infordeptsigndate,
				hardpanserialnum, mac, faultreason, maintainplace,
				processmethod, maintainresult, resysdate, maintainsign,
				maintainid, maintainsigndate, accompansign, accompansigndate,
				ohardpanserialnum, transfersign, transferid, recipientsign,
				recipientid, recipientsigndate, isupdate, managersign,
				managerid, managersigndate);
	}

}
