package com.manage.classifiedtz.model.original;

import java.util.Date;

/**
 * AbstractSClassifiedtzTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSClassifiedtzTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String orgid;
	private String orgname;
	private Date registdate;
	private String depsign;
	private Integer depositoryid;
	private Date depositorydate;
	private String approvesign;
	private Integer approveid;
	private Date approvedate;
	private String note;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSClassifiedtzTab() {
	}

	/** minimal constructor */
	public AbstractSClassifiedtzTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSClassifiedtzTab(Integer id, Integer version, String orgid,
			String orgname, Date registdate,String depsign, Integer depositoryid,
			Date depositorydate, String approvesign, Integer approveid,
			Date approvedate, String note,String username,Integer userid) {
		this.id = id;
		this.version = version;
		this.orgid = orgid;
		this.orgname = orgname;
		this.registdate = registdate;
		this.depsign = depsign;
		this.depositoryid = depositoryid;
		this.depositorydate = depositorydate;
		this.approvesign = approvesign;
		this.approveid = approveid;
		this.approvedate = approvedate;
		this.note = note;
		this.username = username;
		this.userid = userid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Date getRegistdate() {
		return this.registdate;
	}

	public void setRegistdate(Date registdate) {
		this.registdate = registdate;
	}


	public String getDepsign() {
		return this.depsign;
	}

	public void setDepsign(String depsign) {
		this.depsign = depsign;
	}

	public Integer getDepositoryid() {
		return this.depositoryid;
	}

	public void setDepositoryid(Integer depositoryid) {
		this.depositoryid = depositoryid;
	}

	public Date getDepositorydate() {
		return this.depositorydate;
	}

	public void setDepositorydate(Date depositorydate) {
		this.depositorydate = depositorydate;
	}

	public String getApprovesign() {
		return this.approvesign;
	}

	public void setApprovesign(String approvesign) {
		this.approvesign = approvesign;
	}

	public Integer getApproveid() {
		return this.approveid;
	}

	public void setApproveid(Integer approveid) {
		this.approveid = approveid;
	}

	public Date getApprovedate() {
		return this.approvedate;
	}

	public void setApprovedate(Date approvedate) {
		this.approvedate = approvedate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}