package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSMeetsecrecyTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSMeetsecrecyTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String meetname;
	private String orgid;
	private String orgname;
	private Date meetdate;
	private String classification;
	private String meetplace;
	private String bmname;
	private String meetcontent;
	private String cborgopinion;
	private String cbleader;
	private Date cbleaderdate;
	private Integer cbleaderid;
	private String sofficedesc;
	private String sofficesign;
	private Integer sofficeid;
	private Date sofficedate;
	private String yleaderopinion;
	private String yleader;
	private Integer yleaderid;
	private Date yleaderdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSMeetsecrecyTab() {
	}

	/** minimal constructor */
	public AbstractSMeetsecrecyTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSMeetsecrecyTab(Integer id, Integer version,
			String meetname, String orgid, String orgname, Date meetdate,
			String classification, String meetplace, String bmname,
			String meetcontent, String cborgopinion, String cbleader,
			Date cbleaderdate, Integer cbleaderid, String sofficedesc,
			String sofficesign, Integer sofficeid, Date sofficedate,
			String yleaderopinion, String yleader, Integer yleaderid,
			Date yleaderdate) {
		this.id = id;
		this.version = version;
		this.meetname = meetname;
		this.orgid = orgid;
		this.orgname = orgname;
		this.meetdate = meetdate;
		this.classification = classification;
		this.meetplace = meetplace;
		this.bmname = bmname;
		this.meetcontent = meetcontent;
		this.cborgopinion = cborgopinion;
		this.cbleader = cbleader;
		this.cbleaderdate = cbleaderdate;
		this.cbleaderid = cbleaderid;
		this.sofficedesc = sofficedesc;
		this.sofficesign = sofficesign;
		this.sofficeid = sofficeid;
		this.sofficedate = sofficedate;
		this.yleaderopinion = yleaderopinion;
		this.yleader = yleader;
		this.yleaderid = yleaderid;
		this.yleaderdate = yleaderdate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getMeetname() {
		return this.meetname;
	}

	public void setMeetname(String meetname) {
		this.meetname = meetname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Date getMeetdate() {
		return this.meetdate;
	}

	public void setMeetdate(Date meetdate) {
		this.meetdate = meetdate;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public String getMeetplace() {
		return this.meetplace;
	}

	public void setMeetplace(String meetplace) {
		this.meetplace = meetplace;
	}

	public String getBmname() {
		return this.bmname;
	}

	public void setBmname(String bmname) {
		this.bmname = bmname;
	}

	public String getMeetcontent() {
		return this.meetcontent;
	}

	public void setMeetcontent(String meetcontent) {
		this.meetcontent = meetcontent;
	}

	public String getCborgopinion() {
		return this.cborgopinion;
	}

	public void setCborgopinion(String cborgopinion) {
		this.cborgopinion = cborgopinion;
	}

	public String getCbleader() {
		return this.cbleader;
	}

	public void setCbleader(String cbleader) {
		this.cbleader = cbleader;
	}

	public Date getCbleaderdate() {
		return this.cbleaderdate;
	}

	public void setCbleaderdate(Date cbleaderdate) {
		this.cbleaderdate = cbleaderdate;
	}

	public Integer getCbleaderid() {
		return this.cbleaderid;
	}

	public void setCbleaderid(Integer cbleaderid) {
		this.cbleaderid = cbleaderid;
	}

	public String getSofficedesc() {
		return this.sofficedesc;
	}

	public void setSofficedesc(String sofficedesc) {
		this.sofficedesc = sofficedesc;
	}

	public String getSofficesign() {
		return this.sofficesign;
	}

	public void setSofficesign(String sofficesign) {
		this.sofficesign = sofficesign;
	}

	public Integer getSofficeid() {
		return this.sofficeid;
	}

	public void setSofficeid(Integer sofficeid) {
		this.sofficeid = sofficeid;
	}

	public Date getSofficedate() {
		return this.sofficedate;
	}

	public void setSofficedate(Date sofficedate) {
		this.sofficedate = sofficedate;
	}

	public String getYleaderopinion() {
		return this.yleaderopinion;
	}

	public void setYleaderopinion(String yleaderopinion) {
		this.yleaderopinion = yleaderopinion;
	}

	public String getYleader() {
		return this.yleader;
	}

	public void setYleader(String yleader) {
		this.yleader = yleader;
	}

	public Integer getYleaderid() {
		return this.yleaderid;
	}

	public void setYleaderid(Integer yleaderid) {
		this.yleaderid = yleaderid;
	}

	public Date getYleaderdate() {
		return this.yleaderdate;
	}

	public void setYleaderdate(Date yleaderdate) {
		this.yleaderdate = yleaderdate;
	}

}