package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSMeetsecrecyrecordTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSMeetsecrecyrecordTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String meetname;
	private String orgid;
	private String orgname;
	private Date meetdate;
	private String classification;
	private String meetplace;
	private String meetcontent;
	private String meeters;
	private Integer issecuritywork;
	private String sworkremark;
	private Integer istelshield;
	private String telshieldremark;
	private Integer isstoretel;
	private String storetelremark;
	private Integer scheck;
	private String scheckremark;
	private Integer isdeclares;
	private String declareremark;
	private Integer issignin;
	private String signinremark;
	private Integer iswiffi;
	private String wiffiremark;
	private Integer istape;
	private String taperemark;
	private String taper;
	private String videor;
	private Integer issecurityfile;
	private Integer total;
	private Integer giveout;
	private Integer takeback;
	private String takebacker;
	private Integer isguard;
	private String guardremark;
	private String bmname;
	private Integer bmnameid;
	private Date bmsigndate;
	private String sofficedesc;
	private String sofficesign;
	private Integer sofficeid;
	private Date sofficedate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSMeetsecrecyrecordTab() {
	}

	/** minimal constructor */
	public AbstractSMeetsecrecyrecordTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSMeetsecrecyrecordTab(Integer id, Integer version,
			String meetname, String orgid, String orgname, Date meetdate,
			String classification, String meetplace, String meetcontent,
			String meeters, Integer issecuritywork, String sworkremark,
			Integer istelshield, String telshieldremark, Integer isstoretel,
			String storetelremark, Integer scheck, String scheckremark,
			Integer isdeclares, String declareremark, Integer issignin,
			String signinremark, Integer iswiffi, String wiffiremark,
			Integer istape, String taperemark, String taper, String videor,
			Integer issecurityfile, Integer total, Integer giveout,
			Integer takeback, String takebacker, Integer isguard,
			String guardremark, String bmname, Integer bmnameid,
			Date bmsigndate, String sofficedesc, String sofficesign,
			Integer sofficeid, Date sofficedate) {
		this.id = id;
		this.version = version;
		this.meetname = meetname;
		this.orgid = orgid;
		this.orgname = orgname;
		this.meetdate = meetdate;
		this.classification = classification;
		this.meetplace = meetplace;
		this.meetcontent = meetcontent;
		this.meeters = meeters;
		this.issecuritywork = issecuritywork;
		this.sworkremark = sworkremark;
		this.istelshield = istelshield;
		this.telshieldremark = telshieldremark;
		this.isstoretel = isstoretel;
		this.storetelremark = storetelremark;
		this.scheck = scheck;
		this.scheckremark = scheckremark;
		this.isdeclares = isdeclares;
		this.declareremark = declareremark;
		this.issignin = issignin;
		this.signinremark = signinremark;
		this.iswiffi = iswiffi;
		this.wiffiremark = wiffiremark;
		this.istape = istape;
		this.taperemark = taperemark;
		this.taper = taper;
		this.videor = videor;
		this.issecurityfile = issecurityfile;
		this.total = total;
		this.giveout = giveout;
		this.takeback = takeback;
		this.takebacker = takebacker;
		this.isguard = isguard;
		this.guardremark = guardremark;
		this.bmname = bmname;
		this.bmnameid = bmnameid;
		this.bmsigndate = bmsigndate;
		this.sofficedesc = sofficedesc;
		this.sofficesign = sofficesign;
		this.sofficeid = sofficeid;
		this.sofficedate = sofficedate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getMeetname() {
		return this.meetname;
	}

	public void setMeetname(String meetname) {
		this.meetname = meetname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public Date getMeetdate() {
		return this.meetdate;
	}

	public void setMeetdate(Date meetdate) {
		this.meetdate = meetdate;
	}

	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public String getMeetplace() {
		return this.meetplace;
	}

	public void setMeetplace(String meetplace) {
		this.meetplace = meetplace;
	}

	public String getMeetcontent() {
		return this.meetcontent;
	}

	public void setMeetcontent(String meetcontent) {
		this.meetcontent = meetcontent;
	}

	public String getMeeters() {
		return this.meeters;
	}

	public void setMeeters(String meeters) {
		this.meeters = meeters;
	}

	public Integer getIssecuritywork() {
		return this.issecuritywork;
	}

	public void setIssecuritywork(Integer issecuritywork) {
		this.issecuritywork = issecuritywork;
	}

	public String getSworkremark() {
		return this.sworkremark;
	}

	public void setSworkremark(String sworkremark) {
		this.sworkremark = sworkremark;
	}

	public Integer getIstelshield() {
		return this.istelshield;
	}

	public void setIstelshield(Integer istelshield) {
		this.istelshield = istelshield;
	}

	public String getTelshieldremark() {
		return this.telshieldremark;
	}

	public void setTelshieldremark(String telshieldremark) {
		this.telshieldremark = telshieldremark;
	}

	public Integer getIsstoretel() {
		return this.isstoretel;
	}

	public void setIsstoretel(Integer isstoretel) {
		this.isstoretel = isstoretel;
	}

	public String getStoretelremark() {
		return this.storetelremark;
	}

	public void setStoretelremark(String storetelremark) {
		this.storetelremark = storetelremark;
	}

	public Integer getScheck() {
		return this.scheck;
	}

	public void setScheck(Integer scheck) {
		this.scheck = scheck;
	}

	public String getScheckremark() {
		return this.scheckremark;
	}

	public void setScheckremark(String scheckremark) {
		this.scheckremark = scheckremark;
	}

	public Integer getIsdeclares() {
		return this.isdeclares;
	}

	public void setIsdeclares(Integer isdeclares) {
		this.isdeclares = isdeclares;
	}

	public String getDeclareremark() {
		return this.declareremark;
	}

	public void setDeclareremark(String declareremark) {
		this.declareremark = declareremark;
	}

	public Integer getIssignin() {
		return this.issignin;
	}

	public void setIssignin(Integer issignin) {
		this.issignin = issignin;
	}

	public String getSigninremark() {
		return this.signinremark;
	}

	public void setSigninremark(String signinremark) {
		this.signinremark = signinremark;
	}

	public Integer getIswiffi() {
		return this.iswiffi;
	}

	public void setIswiffi(Integer iswiffi) {
		this.iswiffi = iswiffi;
	}

	public String getWiffiremark() {
		return this.wiffiremark;
	}

	public void setWiffiremark(String wiffiremark) {
		this.wiffiremark = wiffiremark;
	}

	public Integer getIstape() {
		return this.istape;
	}

	public void setIstape(Integer istape) {
		this.istape = istape;
	}

	public String getTaperemark() {
		return this.taperemark;
	}

	public void setTaperemark(String taperemark) {
		this.taperemark = taperemark;
	}

	public String getTaper() {
		return this.taper;
	}

	public void setTaper(String taper) {
		this.taper = taper;
	}

	public String getVideor() {
		return this.videor;
	}

	public void setVideor(String videor) {
		this.videor = videor;
	}

	public Integer getIssecurityfile() {
		return this.issecurityfile;
	}

	public void setIssecurityfile(Integer issecurityfile) {
		this.issecurityfile = issecurityfile;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public Integer getGiveout() {
		return this.giveout;
	}

	public void setGiveout(Integer giveout) {
		this.giveout = giveout;
	}

	public Integer getTakeback() {
		return this.takeback;
	}

	public void setTakeback(Integer takeback) {
		this.takeback = takeback;
	}

	public String getTakebacker() {
		return this.takebacker;
	}

	public void setTakebacker(String takebacker) {
		this.takebacker = takebacker;
	}

	public Integer getIsguard() {
		return this.isguard;
	}

	public void setIsguard(Integer isguard) {
		this.isguard = isguard;
	}

	public String getGuardremark() {
		return this.guardremark;
	}

	public void setGuardremark(String guardremark) {
		this.guardremark = guardremark;
	}

	public String getBmname() {
		return this.bmname;
	}

	public void setBmname(String bmname) {
		this.bmname = bmname;
	}

	public Integer getBmnameid() {
		return this.bmnameid;
	}

	public void setBmnameid(Integer bmnameid) {
		this.bmnameid = bmnameid;
	}

	public Date getBmsigndate() {
		return this.bmsigndate;
	}

	public void setBmsigndate(Date bmsigndate) {
		this.bmsigndate = bmsigndate;
	}

	public String getSofficedesc() {
		return this.sofficedesc;
	}

	public void setSofficedesc(String sofficedesc) {
		this.sofficedesc = sofficedesc;
	}

	public String getSofficesign() {
		return this.sofficesign;
	}

	public void setSofficesign(String sofficesign) {
		this.sofficesign = sofficesign;
	}

	public Integer getSofficeid() {
		return this.sofficeid;
	}

	public void setSofficeid(Integer sofficeid) {
		this.sofficeid = sofficeid;
	}

	public Date getSofficedate() {
		return this.sofficedate;
	}

	public void setSofficedate(Date sofficedate) {
		this.sofficedate = sofficedate;
	}

}