package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSConfidentialityTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSConfidentialityTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String partya;
	private String partyb;
	private String paname;
	private String pbname;
	private Integer paid;
	private Integer pbid;
	private Date padate;
	private Date pbdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSConfidentialityTab() {
	}

	/** minimal constructor */
	public AbstractSConfidentialityTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSConfidentialityTab(Integer id, Integer version,
			String partya, String partyb, String paname, String pbname,
			Integer paid, Integer pbid, Date padate, Date pbdate) {
		this.id = id;
		this.version = version;
		this.partya = partya;
		this.partyb = partyb;
		this.paname = paname;
		this.pbname = pbname;
		this.paid = paid;
		this.pbid = pbid;
		this.padate = padate;
		this.pbdate = pbdate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getPartya() {
		return this.partya;
	}

	public void setPartya(String partya) {
		this.partya = partya;
	}

	public String getPartyb() {
		return this.partyb;
	}

	public void setPartyb(String partyb) {
		this.partyb = partyb;
	}

	public String getPaname() {
		return this.paname;
	}

	public void setPaname(String paname) {
		this.paname = paname;
	}

	public String getPbname() {
		return this.pbname;
	}

	public void setPbname(String pbname) {
		this.pbname = pbname;
	}

	public Integer getPaid() {
		return this.paid;
	}

	public void setPaid(Integer paid) {
		this.paid = paid;
	}

	public Integer getPbid() {
		return this.pbid;
	}

	public void setPbid(Integer pbid) {
		this.pbid = pbid;
	}

	public Date getPadate() {
		return this.padate;
	}

	public void setPadate(Date padate) {
		this.padate = padate;
	}

	public Date getPbdate() {
		return this.pbdate;
	}

	public void setPbdate(Date pbdate) {
		this.pbdate = pbdate;
	}

}