package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAInformationpublishTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAInformationpublishTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String applydept;
	private Integer applydeptid;
	private String applicant;
	private Integer applicantid;
	private String publishcontent;
	private Date applydate;
	private String applydeptopinion;
	private String applydeptsign;
	private Integer applydeptsignid;
	private Date applydeptsigndate;
	private String securityopinion;
	private String securitysign;
	private Integer securityid;
	private Date securitysigndate;
	private String bonddeptopinion;
	private String bonddeptsign;
	private Integer bondsignid;
	private Date bondsigndate;
	private String leader;
	private String leadersign;
	private Integer leaderid;
	private Date leadersignid;
	private String infordeptopinion;
	private String infordeptsign;
	private Integer infordeptsignid;
	private Date infordeptsigndate;

	// Constructors

	/** default constructor */
	public AbstractAInformationpublishTab() {
	}

	/** minimal constructor */
	public AbstractAInformationpublishTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAInformationpublishTab(Integer id, Integer version,
			String applydept, Integer applydeptid, String applicant,
			Integer applicantid, String publishcontent, Date applydate,
			String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String securityopinion, String securitysign, Integer securityid,
			Date securitysigndate, String bonddeptopinion, String bonddeptsign,
			Integer bondsignid, Date bondsigndate, String leader,
			String leadersign, Integer leaderid, Date leadersignid,
			String infordeptopinion, String infordeptsign,
			Integer infordeptsignid, Date infordeptsigndate) {
		this.id = id;
		this.version = version;
		this.applydept = applydept;
		this.applydeptid = applydeptid;
		this.applicant = applicant;
		this.applicantid = applicantid;
		this.publishcontent = publishcontent;
		this.applydate = applydate;
		this.applydeptopinion = applydeptopinion;
		this.applydeptsign = applydeptsign;
		this.applydeptsignid = applydeptsignid;
		this.applydeptsigndate = applydeptsigndate;
		this.securityopinion = securityopinion;
		this.securitysign = securitysign;
		this.securityid = securityid;
		this.securitysigndate = securitysigndate;
		this.bonddeptopinion = bonddeptopinion;
		this.bonddeptsign = bonddeptsign;
		this.bondsignid = bondsignid;
		this.bondsigndate = bondsigndate;
		this.leader = leader;
		this.leadersign = leadersign;
		this.leaderid = leaderid;
		this.leadersignid = leadersignid;
		this.infordeptopinion = infordeptopinion;
		this.infordeptsign = infordeptsign;
		this.infordeptsignid = infordeptsignid;
		this.infordeptsigndate = infordeptsigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getApplydept() {
		return this.applydept;
	}

	public void setApplydept(String applydept) {
		this.applydept = applydept;
	}

	public Integer getApplydeptid() {
		return this.applydeptid;
	}

	public void setApplydeptid(Integer applydeptid) {
		this.applydeptid = applydeptid;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public Integer getApplicantid() {
		return this.applicantid;
	}

	public void setApplicantid(Integer applicantid) {
		this.applicantid = applicantid;
	}

	public String getPublishcontent() {
		return this.publishcontent;
	}

	public void setPublishcontent(String publishcontent) {
		this.publishcontent = publishcontent;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getApplydeptopinion() {
		return this.applydeptopinion;
	}

	public void setApplydeptopinion(String applydeptopinion) {
		this.applydeptopinion = applydeptopinion;
	}

	public String getApplydeptsign() {
		return this.applydeptsign;
	}

	public void setApplydeptsign(String applydeptsign) {
		this.applydeptsign = applydeptsign;
	}

	public Integer getApplydeptsignid() {
		return this.applydeptsignid;
	}

	public void setApplydeptsignid(Integer applydeptsignid) {
		this.applydeptsignid = applydeptsignid;
	}

	public Date getApplydeptsigndate() {
		return this.applydeptsigndate;
	}

	public void setApplydeptsigndate(Date applydeptsigndate) {
		this.applydeptsigndate = applydeptsigndate;
	}

	public String getSecurityopinion() {
		return this.securityopinion;
	}

	public void setSecurityopinion(String securityopinion) {
		this.securityopinion = securityopinion;
	}

	public String getSecuritysign() {
		return this.securitysign;
	}

	public void setSecuritysign(String securitysign) {
		this.securitysign = securitysign;
	}

	public Integer getSecurityid() {
		return this.securityid;
	}

	public void setSecurityid(Integer securityid) {
		this.securityid = securityid;
	}

	public Date getSecuritysigndate() {
		return this.securitysigndate;
	}

	public void setSecuritysigndate(Date securitysigndate) {
		this.securitysigndate = securitysigndate;
	}

	public String getBonddeptopinion() {
		return this.bonddeptopinion;
	}

	public void setBonddeptopinion(String bonddeptopinion) {
		this.bonddeptopinion = bonddeptopinion;
	}

	public String getBonddeptsign() {
		return this.bonddeptsign;
	}

	public void setBonddeptsign(String bonddeptsign) {
		this.bonddeptsign = bonddeptsign;
	}

	public Integer getBondsignid() {
		return this.bondsignid;
	}

	public void setBondsignid(Integer bondsignid) {
		this.bondsignid = bondsignid;
	}

	public Date getBondsigndate() {
		return this.bondsigndate;
	}

	public void setBondsigndate(Date bondsigndate) {
		this.bondsigndate = bondsigndate;
	}

	public String getLeader() {
		return this.leader;
	}

	public void setLeader(String leader) {
		this.leader = leader;
	}

	public String getLeadersign() {
		return this.leadersign;
	}

	public void setLeadersign(String leadersign) {
		this.leadersign = leadersign;
	}

	public Integer getLeaderid() {
		return this.leaderid;
	}

	public void setLeaderid(Integer leaderid) {
		this.leaderid = leaderid;
	}

	public Date getLeadersignid() {
		return this.leadersignid;
	}

	public void setLeadersignid(Date leadersignid) {
		this.leadersignid = leadersignid;
	}

	public String getInfordeptopinion() {
		return this.infordeptopinion;
	}

	public void setInfordeptopinion(String infordeptopinion) {
		this.infordeptopinion = infordeptopinion;
	}

	public String getInfordeptsign() {
		return this.infordeptsign;
	}

	public void setInfordeptsign(String infordeptsign) {
		this.infordeptsign = infordeptsign;
	}

	public Integer getInfordeptsignid() {
		return this.infordeptsignid;
	}

	public void setInfordeptsignid(Integer infordeptsignid) {
		this.infordeptsignid = infordeptsignid;
	}

	public Date getInfordeptsigndate() {
		return this.infordeptsigndate;
	}

	public void setInfordeptsigndate(Date infordeptsigndate) {
		this.infordeptsigndate = infordeptsigndate;
	}

}