package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAAlterusbkeyTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAAlterusbkeyTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String name;
	private String position;
	private String deptname;
	private Integer deptid;
	private Integer security;
	private String workplace;
	private String cellphone;
	private Integer alterreason;
	private String definitereason;
	private String applicantsign;
	private Integer applicantid;
	private Date applydate;
	private String deptopinion;
	private String deptsign;
	private Integer deptsignid;
	private Date deptsigndate;
	private String securityopinion;
	private String securitysign;
	private Integer securityid;
	private Date securitysigndate;
	private String infordeptopinion;
	private String infordeptsign;
	private Integer infordeptsignid;
	private Date infordeptsigndate;
	private String trancondition;
	private String transign;
	private Integer transignid;
	private Date transigndate;

	// Constructors

	/** default constructor */
	public AbstractAAlterusbkeyTab() {
	}

	/** minimal constructor */
	public AbstractAAlterusbkeyTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAAlterusbkeyTab(Integer id, Integer version, String name,
			String position, String deptname, Integer deptid, Integer security,
			String workplace, String cellphone, Integer alterreason,
			String definitereason, String applicantsign, Integer applicantid,
			Date applydate, String deptopinion, String deptsign,
			Integer deptsignid, Date deptsigndate, String securityopinion,
			String securitysign, Integer securityid, Date securitysigndate,
			String infordeptopinion, String infordeptsign,
			Integer infordeptsignid, Date infordeptsigndate,
			String trancondition, String transign, Integer transignid,
			Date transigndate) {
		this.id = id;
		this.version = version;
		this.name = name;
		this.position = position;
		this.deptname = deptname;
		this.deptid = deptid;
		this.security = security;
		this.workplace = workplace;
		this.cellphone = cellphone;
		this.alterreason = alterreason;
		this.definitereason = definitereason;
		this.applicantsign = applicantsign;
		this.applicantid = applicantid;
		this.applydate = applydate;
		this.deptopinion = deptopinion;
		this.deptsign = deptsign;
		this.deptsignid = deptsignid;
		this.deptsigndate = deptsigndate;
		this.securityopinion = securityopinion;
		this.securitysign = securitysign;
		this.securityid = securityid;
		this.securitysigndate = securitysigndate;
		this.infordeptopinion = infordeptopinion;
		this.infordeptsign = infordeptsign;
		this.infordeptsignid = infordeptsignid;
		this.infordeptsigndate = infordeptsigndate;
		this.trancondition = trancondition;
		this.transign = transign;
		this.transignid = transignid;
		this.transigndate = transigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public Integer getSecurity() {
		return this.security;
	}

	public void setSecurity(Integer security) {
		this.security = security;
	}

	public String getWorkplace() {
		return this.workplace;
	}

	public void setWorkplace(String workplace) {
		this.workplace = workplace;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public Integer getAlterreason() {
		return this.alterreason;
	}

	public void setAlterreason(Integer alterreason) {
		this.alterreason = alterreason;
	}

	public String getDefinitereason() {
		return this.definitereason;
	}

	public void setDefinitereason(String definitereason) {
		this.definitereason = definitereason;
	}

	public String getApplicantsign() {
		return this.applicantsign;
	}

	public void setApplicantsign(String applicantsign) {
		this.applicantsign = applicantsign;
	}

	public Integer getApplicantid() {
		return this.applicantid;
	}

	public void setApplicantid(Integer applicantid) {
		this.applicantid = applicantid;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getDeptopinion() {
		return this.deptopinion;
	}

	public void setDeptopinion(String deptopinion) {
		this.deptopinion = deptopinion;
	}

	public String getDeptsign() {
		return this.deptsign;
	}

	public void setDeptsign(String deptsign) {
		this.deptsign = deptsign;
	}

	public Integer getDeptsignid() {
		return this.deptsignid;
	}

	public void setDeptsignid(Integer deptsignid) {
		this.deptsignid = deptsignid;
	}

	public Date getDeptsigndate() {
		return this.deptsigndate;
	}

	public void setDeptsigndate(Date deptsigndate) {
		this.deptsigndate = deptsigndate;
	}

	public String getSecurityopinion() {
		return this.securityopinion;
	}

	public void setSecurityopinion(String securityopinion) {
		this.securityopinion = securityopinion;
	}

	public String getSecuritysign() {
		return this.securitysign;
	}

	public void setSecuritysign(String securitysign) {
		this.securitysign = securitysign;
	}

	public Integer getSecurityid() {
		return this.securityid;
	}

	public void setSecurityid(Integer securityid) {
		this.securityid = securityid;
	}

	public Date getSecuritysigndate() {
		return this.securitysigndate;
	}

	public void setSecuritysigndate(Date securitysigndate) {
		this.securitysigndate = securitysigndate;
	}

	public String getInfordeptopinion() {
		return this.infordeptopinion;
	}

	public void setInfordeptopinion(String infordeptopinion) {
		this.infordeptopinion = infordeptopinion;
	}

	public String getInfordeptsign() {
		return this.infordeptsign;
	}

	public void setInfordeptsign(String infordeptsign) {
		this.infordeptsign = infordeptsign;
	}

	public Integer getInfordeptsignid() {
		return this.infordeptsignid;
	}

	public void setInfordeptsignid(Integer infordeptsignid) {
		this.infordeptsignid = infordeptsignid;
	}

	public Date getInfordeptsigndate() {
		return this.infordeptsigndate;
	}

	public void setInfordeptsigndate(Date infordeptsigndate) {
		this.infordeptsigndate = infordeptsigndate;
	}

	public String getTrancondition() {
		return this.trancondition;
	}

	public void setTrancondition(String trancondition) {
		this.trancondition = trancondition;
	}

	public String getTransign() {
		return this.transign;
	}

	public void setTransign(String transign) {
		this.transign = transign;
	}

	public Integer getTransignid() {
		return this.transignid;
	}

	public void setTransignid(Integer transignid) {
		this.transignid = transignid;
	}

	public Date getTransigndate() {
		return this.transigndate;
	}

	public void setTransigndate(Date transigndate) {
		this.transigndate = transigndate;
	}

}