package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSApplykeypartTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSApplykeypartTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer iototal;
	private String partname;
	private String acofficials;
	private String enterreason;
	private Date enterdate;
	private Date stopdate;
	private String departmentdesc;
	private String departmentsign;
	private Integer departmentid;
	private Date depdate;
	private String partheaddesc;
	private String partheadsign;
	private Integer pdepartmentid;
	private Date partheaddate;
	private Integer isregist;
	private Integer isstorage;
	private Integer isdeviceentry;
	private String otherrecord;
	private String acofficialssign;
	private Integer acfficialsid;
	private Date acofficialsdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSApplykeypartTab() {
	}

	/** minimal constructor */
	public AbstractSApplykeypartTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSApplykeypartTab(Integer id, Integer version,
			Integer iototal, 
			String partname, String acofficials, String enterreason,
			Date enterdate, Date stopdate, String departmentdesc,
			String departmentsign, Integer departmentid, Date depdate,
			String partheaddesc, String partheadsign, Integer pdepartmentid,
			Date partheaddate, Integer isregist, Integer isstorage,
			Integer isdeviceentry, String otherrecord, String acofficialssign,
			Integer acfficialsid, Date acofficialsdate) {
		this.id = id;
		this.version = version;
		this.iototal = iototal;
		this.partname = partname;
		this.acofficials = acofficials;
		this.enterreason = enterreason;
		this.enterdate = enterdate;
		this.stopdate = stopdate;
		this.departmentdesc = departmentdesc;
		this.departmentsign = departmentsign;
		this.departmentid = departmentid;
		this.depdate = depdate;
		this.partheaddesc = partheaddesc;
		this.partheadsign = partheadsign;
		this.pdepartmentid = pdepartmentid;
		this.partheaddate = partheaddate;
		this.isregist = isregist;
		this.isstorage = isstorage;
		this.isdeviceentry = isdeviceentry;
		this.otherrecord = otherrecord;
		this.acofficialssign = acofficialssign;
		this.acfficialsid = acfficialsid;
		this.acofficialsdate = acofficialsdate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getIototal() {
		return this.iototal;
	}

	public void setIototal(Integer iototal) {
		this.iototal = iototal;
	}


	public String getPartname() {
		return this.partname;
	}

	public void setPartname(String partname) {
		this.partname = partname;
	}

	public String getAcofficials() {
		return this.acofficials;
	}

	public void setAcofficials(String acofficials) {
		this.acofficials = acofficials;
	}

	public String getEnterreason() {
		return this.enterreason;
	}

	public void setEnterreason(String enterreason) {
		this.enterreason = enterreason;
	}

	public Date getEnterdate() {
		return this.enterdate;
	}

	public void setEnterdate(Date enterdate) {
		this.enterdate = enterdate;
	}

	public Date getStopdate() {
		return this.stopdate;
	}

	public void setStopdate(Date stopdate) {
		this.stopdate = stopdate;
	}

	public String getDepartmentdesc() {
		return this.departmentdesc;
	}

	public void setDepartmentdesc(String departmentdesc) {
		this.departmentdesc = departmentdesc;
	}

	public String getDepartmentsign() {
		return this.departmentsign;
	}

	public void setDepartmentsign(String departmentsign) {
		this.departmentsign = departmentsign;
	}

	public Integer getDepartmentid() {
		return this.departmentid;
	}

	public void setDepartmentid(Integer departmentid) {
		this.departmentid = departmentid;
	}

	public Date getDepdate() {
		return this.depdate;
	}

	public void setDepdate(Date depdate) {
		this.depdate = depdate;
	}

	public String getPartheaddesc() {
		return this.partheaddesc;
	}

	public void setPartheaddesc(String partheaddesc) {
		this.partheaddesc = partheaddesc;
	}

	public String getPartheadsign() {
		return this.partheadsign;
	}

	public void setPartheadsign(String partheadsign) {
		this.partheadsign = partheadsign;
	}

	public Integer getPdepartmentid() {
		return this.pdepartmentid;
	}

	public void setPdepartmentid(Integer pdepartmentid) {
		this.pdepartmentid = pdepartmentid;
	}

	public Date getPartheaddate() {
		return this.partheaddate;
	}

	public void setPartheaddate(Date partheaddate) {
		this.partheaddate = partheaddate;
	}

	public Integer getIsregist() {
		return this.isregist;
	}

	public void setIsregist(Integer isregist) {
		this.isregist = isregist;
	}

	public Integer getIsstorage() {
		return this.isstorage;
	}

	public void setIsstorage(Integer isstorage) {
		this.isstorage = isstorage;
	}

	public Integer getIsdeviceentry() {
		return this.isdeviceentry;
	}

	public void setIsdeviceentry(Integer isdeviceentry) {
		this.isdeviceentry = isdeviceentry;
	}

	public String getOtherrecord() {
		return this.otherrecord;
	}

	public void setOtherrecord(String otherrecord) {
		this.otherrecord = otherrecord;
	}

	public String getAcofficialssign() {
		return this.acofficialssign;
	}

	public void setAcofficialssign(String acofficialssign) {
		this.acofficialssign = acofficialssign;
	}

	public Integer getAcfficialsid() {
		return this.acfficialsid;
	}

	public void setAcfficialsid(Integer acfficialsid) {
		this.acfficialsid = acfficialsid;
	}

	public Date getAcofficialsdate() {
		return this.acofficialsdate;
	}

	public void setAcofficialsdate(Date acofficialsdate) {
		this.acofficialsdate = acofficialsdate;
	}

}