package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractASendoutmaintainTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractASendoutmaintainTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String applicant;
	private Integer applicantid;
	private String devprincipal;
	private Integer devprincipalid;
	private Integer maintaintype;
	private String deviceindex;
	private Integer devicesecurity;
	private String outlanderdept;
	private Integer issignsecret1;
	private Integer isaptitude1;
	private String assignaccompan;
	private String sendoutdept;
	private Integer isremovedisk;
	private Integer issignsecret2;
	private Integer isaptitude2;
	private String assignsender;
	private String infordeptopinion;
	private String infordeptsign;
	private Integer infordeptsignid;
	private Date infordeptsigndate;
	private String deviceuser;
	private Integer deviceuserid;
	private Date divuserdate;
	private String senderreceive;
	private Integer senderid;
	private Date senderdate;
	private Date senddate;
	private Date returndate;
	private Integer issignsecret3;
	private String faultreason;
	private String processmethod;
	private String maintainresult;
	private String maintainsign;
	private Date maintainsigndate;
	private String accompansign;
	private Date accompansigndate;
	private Integer accompanid;
	private String receive;
	private Date receivedate;
	private String sendertransfer;
	private Date transferdate;
	private String remark;

	// Constructors

	/** default constructor */
	public AbstractASendoutmaintainTab() {
	}

	/** minimal constructor */
	public AbstractASendoutmaintainTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractASendoutmaintainTab(Integer id, Integer version,
			String applicant, Integer applicantid, String devprincipal,
			Integer devprincipalid, Integer maintaintype, String deviceindex,
			Integer devicesecurity, String outlanderdept,
			Integer issignsecret1, Integer isaptitude1, String assignaccompan,
			String sendoutdept, Integer isremovedisk, Integer issignsecret2,
			Integer isaptitude2, String assignsender, String infordeptopinion,
			String infordeptsign, Integer infordeptsignid,
			Date infordeptsigndate, String deviceuser, Integer deviceuserid,
			Date divuserdate, String senderreceive, Integer senderid,
			Date senderdate, Date senddate, Date returndate,
			Integer issignsecret3, String faultreason, String processmethod,
			String maintainresult, String maintainsign, Date maintainsigndate,
			String accompansign, Date accompansigndate, Integer accompanid,
			String receive, Date receivedate, String sendertransfer,
			Date transferdate, String remark) {
		this.id = id;
		this.version = version;
		this.applicant = applicant;
		this.applicantid = applicantid;
		this.devprincipal = devprincipal;
		this.devprincipalid = devprincipalid;
		this.maintaintype = maintaintype;
		this.deviceindex = deviceindex;
		this.devicesecurity = devicesecurity;
		this.outlanderdept = outlanderdept;
		this.issignsecret1 = issignsecret1;
		this.isaptitude1 = isaptitude1;
		this.assignaccompan = assignaccompan;
		this.sendoutdept = sendoutdept;
		this.isremovedisk = isremovedisk;
		this.issignsecret2 = issignsecret2;
		this.isaptitude2 = isaptitude2;
		this.assignsender = assignsender;
		this.infordeptopinion = infordeptopinion;
		this.infordeptsign = infordeptsign;
		this.infordeptsignid = infordeptsignid;
		this.infordeptsigndate = infordeptsigndate;
		this.deviceuser = deviceuser;
		this.deviceuserid = deviceuserid;
		this.divuserdate = divuserdate;
		this.senderreceive = senderreceive;
		this.senderid = senderid;
		this.senderdate = senderdate;
		this.senddate = senddate;
		this.returndate = returndate;
		this.issignsecret3 = issignsecret3;
		this.faultreason = faultreason;
		this.processmethod = processmethod;
		this.maintainresult = maintainresult;
		this.maintainsign = maintainsign;
		this.maintainsigndate = maintainsigndate;
		this.accompansign = accompansign;
		this.accompansigndate = accompansigndate;
		this.accompanid = accompanid;
		this.receive = receive;
		this.receivedate = receivedate;
		this.sendertransfer = sendertransfer;
		this.transferdate = transferdate;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public Integer getApplicantid() {
		return this.applicantid;
	}

	public void setApplicantid(Integer applicantid) {
		this.applicantid = applicantid;
	}

	public String getDevprincipal() {
		return this.devprincipal;
	}

	public void setDevprincipal(String devprincipal) {
		this.devprincipal = devprincipal;
	}

	public Integer getDevprincipalid() {
		return this.devprincipalid;
	}

	public void setDevprincipalid(Integer devprincipalid) {
		this.devprincipalid = devprincipalid;
	}

	public Integer getMaintaintype() {
		return this.maintaintype;
	}

	public void setMaintaintype(Integer maintaintype) {
		this.maintaintype = maintaintype;
	}

	public String getDeviceindex() {
		return this.deviceindex;
	}

	public void setDeviceindex(String deviceindex) {
		this.deviceindex = deviceindex;
	}

	public Integer getDevicesecurity() {
		return this.devicesecurity;
	}

	public void setDevicesecurity(Integer devicesecurity) {
		this.devicesecurity = devicesecurity;
	}

	public String getOutlanderdept() {
		return this.outlanderdept;
	}

	public void setOutlanderdept(String outlanderdept) {
		this.outlanderdept = outlanderdept;
	}

	public Integer getIssignsecret1() {
		return this.issignsecret1;
	}

	public void setIssignsecret1(Integer issignsecret1) {
		this.issignsecret1 = issignsecret1;
	}

	public Integer getIsaptitude1() {
		return this.isaptitude1;
	}

	public void setIsaptitude1(Integer isaptitude1) {
		this.isaptitude1 = isaptitude1;
	}

	public String getAssignaccompan() {
		return this.assignaccompan;
	}

	public void setAssignaccompan(String assignaccompan) {
		this.assignaccompan = assignaccompan;
	}

	public String getSendoutdept() {
		return this.sendoutdept;
	}

	public void setSendoutdept(String sendoutdept) {
		this.sendoutdept = sendoutdept;
	}

	public Integer getIsremovedisk() {
		return this.isremovedisk;
	}

	public void setIsremovedisk(Integer isremovedisk) {
		this.isremovedisk = isremovedisk;
	}

	public Integer getIssignsecret2() {
		return this.issignsecret2;
	}

	public void setIssignsecret2(Integer issignsecret2) {
		this.issignsecret2 = issignsecret2;
	}

	public Integer getIsaptitude2() {
		return this.isaptitude2;
	}

	public void setIsaptitude2(Integer isaptitude2) {
		this.isaptitude2 = isaptitude2;
	}

	public String getAssignsender() {
		return this.assignsender;
	}

	public void setAssignsender(String assignsender) {
		this.assignsender = assignsender;
	}

	public String getInfordeptopinion() {
		return this.infordeptopinion;
	}

	public void setInfordeptopinion(String infordeptopinion) {
		this.infordeptopinion = infordeptopinion;
	}

	public String getInfordeptsign() {
		return this.infordeptsign;
	}

	public void setInfordeptsign(String infordeptsign) {
		this.infordeptsign = infordeptsign;
	}

	public Integer getInfordeptsignid() {
		return this.infordeptsignid;
	}

	public void setInfordeptsignid(Integer infordeptsignid) {
		this.infordeptsignid = infordeptsignid;
	}

	public Date getInfordeptsigndate() {
		return this.infordeptsigndate;
	}

	public void setInfordeptsigndate(Date infordeptsigndate) {
		this.infordeptsigndate = infordeptsigndate;
	}

	public String getDeviceuser() {
		return this.deviceuser;
	}

	public void setDeviceuser(String deviceuser) {
		this.deviceuser = deviceuser;
	}

	public Integer getDeviceuserid() {
		return this.deviceuserid;
	}

	public void setDeviceuserid(Integer deviceuserid) {
		this.deviceuserid = deviceuserid;
	}

	public Date getDivuserdate() {
		return this.divuserdate;
	}

	public void setDivuserdate(Date divuserdate) {
		this.divuserdate = divuserdate;
	}

	public String getSenderreceive() {
		return this.senderreceive;
	}

	public void setSenderreceive(String senderreceive) {
		this.senderreceive = senderreceive;
	}

	public Integer getSenderid() {
		return this.senderid;
	}

	public void setSenderid(Integer senderid) {
		this.senderid = senderid;
	}

	public Date getSenderdate() {
		return this.senderdate;
	}

	public void setSenderdate(Date senderdate) {
		this.senderdate = senderdate;
	}

	public Date getSenddate() {
		return this.senddate;
	}

	public void setSenddate(Date senddate) {
		this.senddate = senddate;
	}

	public Date getReturndate() {
		return this.returndate;
	}

	public void setReturndate(Date returndate) {
		this.returndate = returndate;
	}

	public Integer getIssignsecret3() {
		return this.issignsecret3;
	}

	public void setIssignsecret3(Integer issignsecret3) {
		this.issignsecret3 = issignsecret3;
	}

	public String getFaultreason() {
		return this.faultreason;
	}

	public void setFaultreason(String faultreason) {
		this.faultreason = faultreason;
	}

	public String getProcessmethod() {
		return this.processmethod;
	}

	public void setProcessmethod(String processmethod) {
		this.processmethod = processmethod;
	}

	public String getMaintainresult() {
		return this.maintainresult;
	}

	public void setMaintainresult(String maintainresult) {
		this.maintainresult = maintainresult;
	}

	public String getMaintainsign() {
		return this.maintainsign;
	}

	public void setMaintainsign(String maintainsign) {
		this.maintainsign = maintainsign;
	}

	public Date getMaintainsigndate() {
		return this.maintainsigndate;
	}

	public void setMaintainsigndate(Date maintainsigndate) {
		this.maintainsigndate = maintainsigndate;
	}

	public String getAccompansign() {
		return this.accompansign;
	}

	public void setAccompansign(String accompansign) {
		this.accompansign = accompansign;
	}

	public Date getAccompansigndate() {
		return this.accompansigndate;
	}

	public void setAccompansigndate(Date accompansigndate) {
		this.accompansigndate = accompansigndate;
	}

	public Integer getAccompanid() {
		return this.accompanid;
	}

	public void setAccompanid(Integer accompanid) {
		this.accompanid = accompanid;
	}

	public String getReceive() {
		return this.receive;
	}

	public void setReceive(String receive) {
		this.receive = receive;
	}

	public Date getReceivedate() {
		return this.receivedate;
	}

	public void setReceivedate(Date receivedate) {
		this.receivedate = receivedate;
	}

	public String getSendertransfer() {
		return this.sendertransfer;
	}

	public void setSendertransfer(String sendertransfer) {
		this.sendertransfer = sendertransfer;
	}

	public Date getTransferdate() {
		return this.transferdate;
	}

	public void setTransferdate(Date transferdate) {
		this.transferdate = transferdate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}