package com.manage.temp.model.original;

/**
 * AbstractSGetmediuminfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSGetmediuminfoTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer eid;
	private Integer rmediumtype;
	private String rspecifications;
	private String rscode;
	private String productcode;
	private Integer rcerttype;
	private String rcerrange;
	private String rsign;
	private Integer rid;

	// Constructors

	/** default constructor */
	public AbstractSGetmediuminfoTab() {
	}

	/** minimal constructor */
	public AbstractSGetmediuminfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSGetmediuminfoTab(Integer id, Integer version, Integer eid,
			Integer rmediumtype, String rspecifications, String rscode,
			String productcode, Integer rcerttype, String rcerrange,
			String rsign, Integer rid) {
		this.id = id;
		this.version = version;
		this.eid = eid;
		this.rmediumtype = rmediumtype;
		this.rspecifications = rspecifications;
		this.rscode = rscode;
		this.productcode = productcode;
		this.rcerttype = rcerttype;
		this.rcerrange = rcerrange;
		this.rsign = rsign;
		this.rid = rid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Integer getRmediumtype() {
		return this.rmediumtype;
	}

	public void setRmediumtype(Integer rmediumtype) {
		this.rmediumtype = rmediumtype;
	}

	public String getRspecifications() {
		return this.rspecifications;
	}

	public void setRspecifications(String rspecifications) {
		this.rspecifications = rspecifications;
	}

	public String getRscode() {
		return this.rscode;
	}

	public void setRscode(String rscode) {
		this.rscode = rscode;
	}

	public String getProductcode() {
		return this.productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

	public Integer getRcerttype() {
		return this.rcerttype;
	}

	public void setRcerttype(Integer rcerttype) {
		this.rcerttype = rcerttype;
	}

	public String getRcerrange() {
		return this.rcerrange;
	}

	public void setRcerrange(String rcerrange) {
		this.rcerrange = rcerrange;
	}

	public String getRsign() {
		return this.rsign;
	}

	public void setRsign(String rsign) {
		this.rsign = rsign;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

}