package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAEmailexamineTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAEmailexamineTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String deptname;
	private Integer deptid;
	private String applicant;
	private Integer applicantid;
	private String offices;
	private Integer officesid;
	private String linktype;
	private String openreason;
	private String revokereason;
	private String applydeptopinion;
	private String applydeptsign;
	private Integer applydeptsignid;
	private Date applydeptsigndate;
	private String archivesdept;
	private String archivessign;
	private Integer archivesid;
	private Date archivesdate;
	private String operatrecord;
	private String webmaster;
	private Integer webmasterid;
	private Date webmasterdate;

	// Constructors

	/** default constructor */
	public AbstractAEmailexamineTab() {
	}

	/** minimal constructor */
	public AbstractAEmailexamineTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAEmailexamineTab(Integer id, Integer version,
			String deptname, Integer deptid, String applicant,
			Integer applicantid, String offices, Integer officesid,
			String linktype, String openreason, String revokereason,
			String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String archivesdept, String archivessign, Integer archivesid,
			Date archivesdate, String operatrecord, String webmaster,
			Integer webmasterid, Date webmasterdate) {
		this.id = id;
		this.version = version;
		this.deptname = deptname;
		this.deptid = deptid;
		this.applicant = applicant;
		this.applicantid = applicantid;
		this.offices = offices;
		this.officesid = officesid;
		this.linktype = linktype;
		this.openreason = openreason;
		this.revokereason = revokereason;
		this.applydeptopinion = applydeptopinion;
		this.applydeptsign = applydeptsign;
		this.applydeptsignid = applydeptsignid;
		this.applydeptsigndate = applydeptsigndate;
		this.archivesdept = archivesdept;
		this.archivessign = archivessign;
		this.archivesid = archivesid;
		this.archivesdate = archivesdate;
		this.operatrecord = operatrecord;
		this.webmaster = webmaster;
		this.webmasterid = webmasterid;
		this.webmasterdate = webmasterdate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public Integer getApplicantid() {
		return this.applicantid;
	}

	public void setApplicantid(Integer applicantid) {
		this.applicantid = applicantid;
	}

	public String getOffices() {
		return this.offices;
	}

	public void setOffices(String offices) {
		this.offices = offices;
	}

	public Integer getOfficesid() {
		return this.officesid;
	}

	public void setOfficesid(Integer officesid) {
		this.officesid = officesid;
	}

	public String getLinktype() {
		return this.linktype;
	}

	public void setLinktype(String linktype) {
		this.linktype = linktype;
	}

	public String getOpenreason() {
		return this.openreason;
	}

	public void setOpenreason(String openreason) {
		this.openreason = openreason;
	}

	public String getRevokereason() {
		return this.revokereason;
	}

	public void setRevokereason(String revokereason) {
		this.revokereason = revokereason;
	}

	public String getApplydeptopinion() {
		return this.applydeptopinion;
	}

	public void setApplydeptopinion(String applydeptopinion) {
		this.applydeptopinion = applydeptopinion;
	}

	public String getApplydeptsign() {
		return this.applydeptsign;
	}

	public void setApplydeptsign(String applydeptsign) {
		this.applydeptsign = applydeptsign;
	}

	public Integer getApplydeptsignid() {
		return this.applydeptsignid;
	}

	public void setApplydeptsignid(Integer applydeptsignid) {
		this.applydeptsignid = applydeptsignid;
	}

	public Date getApplydeptsigndate() {
		return this.applydeptsigndate;
	}

	public void setApplydeptsigndate(Date applydeptsigndate) {
		this.applydeptsigndate = applydeptsigndate;
	}

	public String getArchivesdept() {
		return this.archivesdept;
	}

	public void setArchivesdept(String archivesdept) {
		this.archivesdept = archivesdept;
	}

	public String getArchivessign() {
		return this.archivessign;
	}

	public void setArchivessign(String archivessign) {
		this.archivessign = archivessign;
	}

	public Integer getArchivesid() {
		return this.archivesid;
	}

	public void setArchivesid(Integer archivesid) {
		this.archivesid = archivesid;
	}

	public Date getArchivesdate() {
		return this.archivesdate;
	}

	public void setArchivesdate(Date archivesdate) {
		this.archivesdate = archivesdate;
	}

	public String getOperatrecord() {
		return this.operatrecord;
	}

	public void setOperatrecord(String operatrecord) {
		this.operatrecord = operatrecord;
	}

	public String getWebmaster() {
		return this.webmaster;
	}

	public void setWebmaster(String webmaster) {
		this.webmaster = webmaster;
	}

	public Integer getWebmasterid() {
		return this.webmasterid;
	}

	public void setWebmasterid(Integer webmasterid) {
		this.webmasterid = webmasterid;
	}

	public Date getWebmasterdate() {
		return this.webmasterdate;
	}

	public void setWebmasterdate(Date webmasterdate) {
		this.webmasterdate = webmasterdate;
	}

}