package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSEstoragemediumTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSEstoragemediumTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String mcode;
	private Date applydate;
	private String orgname;
	private String orgid;
	private String depository;
	private Integer depositoryid;
	private String sign;
	private Integer signid;
	private Date signdate;
	private String departmentdesc;
	private String officedesc;
	private String username;
	private Integer userid;
	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSEstoragemediumTab() {
	}

	/** minimal constructor */
	public AbstractSEstoragemediumTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSEstoragemediumTab(Integer id, Integer version,
			String mcode, Date applydate, String orgname, String orgid,
			String depository, Integer depositoryid, Integer qmediumtype,
			String qspecifications, String qclassification, Integer qnum,
			Integer qcerttype, String qusrange, String sign, Integer signid,
			Date signdate, String departmentdesc, String officedesc) {
		this.id = id;
		this.version = version;
		this.mcode = mcode;
		this.applydate = applydate;
		this.orgname = orgname;
		this.orgid = orgid;
		this.depository = depository;
		this.depositoryid = depositoryid;
		this.sign = sign;
		this.signid = signid;
		this.signdate = signdate;
		this.departmentdesc = departmentdesc;
		this.officedesc = officedesc;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getMcode() {
		return this.mcode;
	}

	public void setMcode(String mcode) {
		this.mcode = mcode;
	}

	public Date getApplydate() {
		return this.applydate;
	}

	public void setApplydate(Date applydate) {
		this.applydate = applydate;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getDepository() {
		return this.depository;
	}

	public void setDepository(String depository) {
		this.depository = depository;
	}

	public Integer getDepositoryid() {
		return this.depositoryid;
	}

	public void setDepositoryid(Integer depositoryid) {
		this.depositoryid = depositoryid;
	}


	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public Integer getSignid() {
		return this.signid;
	}

	public void setSignid(Integer signid) {
		this.signid = signid;
	}

	public Date getSigndate() {
		return this.signdate;
	}

	public void setSigndate(Date signdate) {
		this.signdate = signdate;
	}

	public String getDepartmentdesc() {
		return this.departmentdesc;
	}

	public void setDepartmentdesc(String departmentdesc) {
		this.departmentdesc = departmentdesc;
	}

	public String getOfficedesc() {
		return this.officedesc;
	}

	public void setOfficedesc(String officedesc) {
		this.officedesc = officedesc;
	}

}