package com.manage.temp.model.original;

/**
 * AbstractADeviceinfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractADeviceinfoTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer did;
	private String device;
	private String devversion;
	private Integer number;
	private String producer;
	private Double budget;

	// Constructors

	/** default constructor */
	public AbstractADeviceinfoTab() {
	}

	/** minimal constructor */
	public AbstractADeviceinfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractADeviceinfoTab(Integer id, Integer version, Integer did,
			String device, String devversion, Integer number, String producer,
			Double budget) {
		this.id = id;
		this.version = version;
		this.did = did;
		this.device = device;
		this.devversion = devversion;
		this.number = number;
		this.producer = producer;
		this.budget = budget;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getDevversion() {
		return this.devversion;
	}

	public void setDevversion(String devversion) {
		this.devversion = devversion;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getProducer() {
		return this.producer;
	}

	public void setProducer(String producer) {
		this.producer = producer;
	}

	public Double getBudget() {
		return this.budget;
	}

	public void setBudget(Double budget) {
		this.budget = budget;
	}

}