package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractADevicemaintainTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractADevicemaintainTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String devprincipal;
	private Integer devprincipalid;
	private String orgname;
	private String orgid;
	private String devicename;
	private String deviceindex;
	private Integer devicesecurity;
	private String faultdescribe;
	private String devprincipalsign;
	private Date devprincipaldate;
	private String diagnosecase;
	private String diagnosesign;
	private Integer diagnoseid;
	private Date diagnosedate;
	private String applydeptopinion;
	private String applydeptsign;
	private Integer applydeptsignid;
	private Date applydeptsigndate;
	private String infordeptopinion;
	private String infordeptsign;
	private Integer infordeptsignid;
	private Date infordeptsigndate;
	private String hardpanserialnum;
	private String mac;
	private String faultreason;
	private String maintainplace;
	private String processmethod;
	private String maintainresult;
	private Date resysdate;
	private String maintainsign;
	private Integer maintainid;
	private Date maintainsigndate;
	private String accompansign;
	private Date accompansigndate;
	private String ohardpanserialnum;
	private String transfersign;
	private Integer transferid;
	private String recipientsign;
	private Integer recipientid;
	private Date recipientsigndate;
	private Integer isupdate;
	private String managersign;
	private Integer managerid;
	private Date managersigndate;

	// Constructors

	/** default constructor */
	public AbstractADevicemaintainTab() {
	}

	/** minimal constructor */
	public AbstractADevicemaintainTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractADevicemaintainTab(Integer id, Integer version,
			String devprincipal, Integer devprincipalid, String orgname,
			String orgid, String devicename, String deviceindex,
			Integer devicesecurity, String faultdescribe,
			String devprincipalsign, Date devprincipaldate,
			String diagnosecase, String diagnosesign, Integer diagnoseid,
			Date diagnosedate, String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String infordeptopinion, String infordeptsign,
			Integer infordeptsignid, Date infordeptsigndate,
			String hardpanserialnum, String mac, String faultreason,
			String maintainplace, String processmethod, String maintainresult,
			Date resysdate, String maintainsign, Integer maintainid,
			Date maintainsigndate, String accompansign, Date accompansigndate,
			String ohardpanserialnum, String transfersign, Integer transferid,
			String recipientsign, Integer recipientid, Date recipientsigndate,
			Integer isupdate, String managersign, Integer managerid,
			Date managersigndate) {
		this.id = id;
		this.version = version;
		this.devprincipal = devprincipal;
		this.devprincipalid = devprincipalid;
		this.orgname = orgname;
		this.orgid = orgid;
		this.devicename = devicename;
		this.deviceindex = deviceindex;
		this.devicesecurity = devicesecurity;
		this.faultdescribe = faultdescribe;
		this.devprincipalsign = devprincipalsign;
		this.devprincipaldate = devprincipaldate;
		this.diagnosecase = diagnosecase;
		this.diagnosesign = diagnosesign;
		this.diagnoseid = diagnoseid;
		this.diagnosedate = diagnosedate;
		this.applydeptopinion = applydeptopinion;
		this.applydeptsign = applydeptsign;
		this.applydeptsignid = applydeptsignid;
		this.applydeptsigndate = applydeptsigndate;
		this.infordeptopinion = infordeptopinion;
		this.infordeptsign = infordeptsign;
		this.infordeptsignid = infordeptsignid;
		this.infordeptsigndate = infordeptsigndate;
		this.hardpanserialnum = hardpanserialnum;
		this.mac = mac;
		this.faultreason = faultreason;
		this.maintainplace = maintainplace;
		this.processmethod = processmethod;
		this.maintainresult = maintainresult;
		this.resysdate = resysdate;
		this.maintainsign = maintainsign;
		this.maintainid = maintainid;
		this.maintainsigndate = maintainsigndate;
		this.accompansign = accompansign;
		this.accompansigndate = accompansigndate;
		this.ohardpanserialnum = ohardpanserialnum;
		this.transfersign = transfersign;
		this.transferid = transferid;
		this.recipientsign = recipientsign;
		this.recipientid = recipientid;
		this.recipientsigndate = recipientsigndate;
		this.isupdate = isupdate;
		this.managersign = managersign;
		this.managerid = managerid;
		this.managersigndate = managersigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDevprincipal() {
		return this.devprincipal;
	}

	public void setDevprincipal(String devprincipal) {
		this.devprincipal = devprincipal;
	}

	public Integer getDevprincipalid() {
		return this.devprincipalid;
	}

	public void setDevprincipalid(Integer devprincipalid) {
		this.devprincipalid = devprincipalid;
	}

	public String getOrgname() {
		return this.orgname;
	}

	public void setOrgname(String orgname) {
		this.orgname = orgname;
	}

	public String getOrgid() {
		return this.orgid;
	}

	public void setOrgid(String orgid) {
		this.orgid = orgid;
	}

	public String getDevicename() {
		return this.devicename;
	}

	public void setDevicename(String devicename) {
		this.devicename = devicename;
	}

	public String getDeviceindex() {
		return this.deviceindex;
	}

	public void setDeviceindex(String deviceindex) {
		this.deviceindex = deviceindex;
	}

	public Integer getDevicesecurity() {
		return this.devicesecurity;
	}

	public void setDevicesecurity(Integer devicesecurity) {
		this.devicesecurity = devicesecurity;
	}

	public String getFaultdescribe() {
		return this.faultdescribe;
	}

	public void setFaultdescribe(String faultdescribe) {
		this.faultdescribe = faultdescribe;
	}

	public String getDevprincipalsign() {
		return this.devprincipalsign;
	}

	public void setDevprincipalsign(String devprincipalsign) {
		this.devprincipalsign = devprincipalsign;
	}

	public Date getDevprincipaldate() {
		return this.devprincipaldate;
	}

	public void setDevprincipaldate(Date devprincipaldate) {
		this.devprincipaldate = devprincipaldate;
	}

	public String getDiagnosecase() {
		return this.diagnosecase;
	}

	public void setDiagnosecase(String diagnosecase) {
		this.diagnosecase = diagnosecase;
	}

	public String getDiagnosesign() {
		return this.diagnosesign;
	}

	public void setDiagnosesign(String diagnosesign) {
		this.diagnosesign = diagnosesign;
	}

	public Integer getDiagnoseid() {
		return this.diagnoseid;
	}

	public void setDiagnoseid(Integer diagnoseid) {
		this.diagnoseid = diagnoseid;
	}

	public Date getDiagnosedate() {
		return this.diagnosedate;
	}

	public void setDiagnosedate(Date diagnosedate) {
		this.diagnosedate = diagnosedate;
	}

	public String getApplydeptopinion() {
		return this.applydeptopinion;
	}

	public void setApplydeptopinion(String applydeptopinion) {
		this.applydeptopinion = applydeptopinion;
	}

	public String getApplydeptsign() {
		return this.applydeptsign;
	}

	public void setApplydeptsign(String applydeptsign) {
		this.applydeptsign = applydeptsign;
	}

	public Integer getApplydeptsignid() {
		return this.applydeptsignid;
	}

	public void setApplydeptsignid(Integer applydeptsignid) {
		this.applydeptsignid = applydeptsignid;
	}

	public Date getApplydeptsigndate() {
		return this.applydeptsigndate;
	}

	public void setApplydeptsigndate(Date applydeptsigndate) {
		this.applydeptsigndate = applydeptsigndate;
	}

	public String getInfordeptopinion() {
		return this.infordeptopinion;
	}

	public void setInfordeptopinion(String infordeptopinion) {
		this.infordeptopinion = infordeptopinion;
	}

	public String getInfordeptsign() {
		return this.infordeptsign;
	}

	public void setInfordeptsign(String infordeptsign) {
		this.infordeptsign = infordeptsign;
	}

	public Integer getInfordeptsignid() {
		return this.infordeptsignid;
	}

	public void setInfordeptsignid(Integer infordeptsignid) {
		this.infordeptsignid = infordeptsignid;
	}

	public Date getInfordeptsigndate() {
		return this.infordeptsigndate;
	}

	public void setInfordeptsigndate(Date infordeptsigndate) {
		this.infordeptsigndate = infordeptsigndate;
	}

	public String getHardpanserialnum() {
		return this.hardpanserialnum;
	}

	public void setHardpanserialnum(String hardpanserialnum) {
		this.hardpanserialnum = hardpanserialnum;
	}

	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	public String getFaultreason() {
		return this.faultreason;
	}

	public void setFaultreason(String faultreason) {
		this.faultreason = faultreason;
	}

	public String getMaintainplace() {
		return this.maintainplace;
	}

	public void setMaintainplace(String maintainplace) {
		this.maintainplace = maintainplace;
	}

	public String getProcessmethod() {
		return this.processmethod;
	}

	public void setProcessmethod(String processmethod) {
		this.processmethod = processmethod;
	}

	public String getMaintainresult() {
		return this.maintainresult;
	}

	public void setMaintainresult(String maintainresult) {
		this.maintainresult = maintainresult;
	}

	public Date getResysdate() {
		return this.resysdate;
	}

	public void setResysdate(Date resysdate) {
		this.resysdate = resysdate;
	}

	public String getMaintainsign() {
		return this.maintainsign;
	}

	public void setMaintainsign(String maintainsign) {
		this.maintainsign = maintainsign;
	}

	public Integer getMaintainid() {
		return this.maintainid;
	}

	public void setMaintainid(Integer maintainid) {
		this.maintainid = maintainid;
	}

	public Date getMaintainsigndate() {
		return this.maintainsigndate;
	}

	public void setMaintainsigndate(Date maintainsigndate) {
		this.maintainsigndate = maintainsigndate;
	}

	public String getAccompansign() {
		return this.accompansign;
	}

	public void setAccompansign(String accompansign) {
		this.accompansign = accompansign;
	}

	public Date getAccompansigndate() {
		return this.accompansigndate;
	}

	public void setAccompansigndate(Date accompansigndate) {
		this.accompansigndate = accompansigndate;
	}

	public String getOhardpanserialnum() {
		return this.ohardpanserialnum;
	}

	public void setOhardpanserialnum(String ohardpanserialnum) {
		this.ohardpanserialnum = ohardpanserialnum;
	}

	public String getTransfersign() {
		return this.transfersign;
	}

	public void setTransfersign(String transfersign) {
		this.transfersign = transfersign;
	}

	public Integer getTransferid() {
		return this.transferid;
	}

	public void setTransferid(Integer transferid) {
		this.transferid = transferid;
	}

	public String getRecipientsign() {
		return this.recipientsign;
	}

	public void setRecipientsign(String recipientsign) {
		this.recipientsign = recipientsign;
	}

	public Integer getRecipientid() {
		return this.recipientid;
	}

	public void setRecipientid(Integer recipientid) {
		this.recipientid = recipientid;
	}

	public Date getRecipientsigndate() {
		return this.recipientsigndate;
	}

	public void setRecipientsigndate(Date recipientsigndate) {
		this.recipientsigndate = recipientsigndate;
	}

	public Integer getIsupdate() {
		return this.isupdate;
	}

	public void setIsupdate(Integer isupdate) {
		this.isupdate = isupdate;
	}

	public String getManagersign() {
		return this.managersign;
	}

	public void setManagersign(String managersign) {
		this.managersign = managersign;
	}

	public Integer getManagerid() {
		return this.managerid;
	}

	public void setManagerid(Integer managerid) {
		this.managerid = managerid;
	}

	public Date getManagersigndate() {
		return this.managersigndate;
	}

	public void setManagersigndate(Date managersigndate) {
		this.managersigndate = managersigndate;
	}

}