package com.manage.temp.model.original;

/**
 * AbstractSDetainstandardTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSDetainstandardTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String truancy;
	private String selfcheck;
	private String nopass;
	private String abroad;
	private String leaks;
	private String retaliation;
	private String destructionequip;
	private String refusecheck;
	private String randomdense;
	private String mrandomdense;
	private String distributionscope;
	private String transforclassified;
	private String borrowing;
	private String intensivelogo;
	private String carryout;
	private String jmcarryout;
	private String printzl;
	private String confidentiality;
	private String storecarrier;
	private String kconfidential;
	private String keepjm;
	private String bmbsybg;
	private String xhdj;
	private String xhgrq;
	private String syhysb;
	private String confregist;
	private String xhzlwj;
	private String gbsj;
	private String videos;
	private String inforprocess;
	private String formatting;
	private String dellog;
	private String bmbs;
	private String cysmdj;
	private String aqbmcp;
	private String maintenance;
	private String azcc;
	private String wbsb;
	private String fsfunction;
	private String storeinfor;
	private String conmp;
	private String dmjmedium;
	private String usegmj;
	private String middleconver;
	private String isolatesocket;
	private String carrymedium;
	private String bmjcmedium;
	private String checkinfor;
	private String clsw;
	private String grconmedium;
	private String classifiedequip;
	private String noclogo;
	private String wirelesscon;
	private String mprocess;
	private String uwire;
	private String ucommunication;
	private String mobileinto;
	private String umobile;
	private String mobilelx;
	private String faxcopy;
	private String deliveryinfor;
	private String receiveinterview;
	private String wbmzg;
	private String wqbmxy;
	private String jsyq;
	private String jdjc;
	private String wsjd;
	private String wfbmjl;
	private String wjcr;
	private String zlwjsp;
	private String kdcgfw;
	private String ayzc;
	private String qkbss;
	private String cssmhd;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSDetainstandardTab() {
	}

	/** minimal constructor */
	public AbstractSDetainstandardTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSDetainstandardTab(Integer id, Integer version,
			String truancy, String selfcheck, String nopass, String abroad,
			String leaks, String retaliation, String destructionequip,
			String refusecheck, String randomdense, String mrandomdense,
			String distributionscope, String transforclassified,
			String borrowing, String intensivelogo, String carryout,
			String jmcarryout, String printzl, String confidentiality,
			String storecarrier, String kconfidential, String keepjm,
			String bmbsybg, String xhdj, String xhgrq, String syhysb,
			String confregist, String xhzlwj, String gbsj, String videos,
			String inforprocess, String formatting, String dellog, String bmbs,
			String cysmdj, String aqbmcp, String maintenance, String azcc,
			String wbsb, String fsfunction, String storeinfor, String conmp,
			String dmjmedium, String usegmj, String middleconver,
			String isolatesocket, String carrymedium, String bmjcmedium,
			String checkinfor, String clsw, String grconmedium,
			String classifiedequip, String noclogo, String wirelesscon,
			String mprocess, String uwire, String ucommunication,
			String mobileinto, String umobile, String mobilelx, String faxcopy,
			String deliveryinfor, String receiveinterview, String wbmzg,
			String wqbmxy, String jsyq, String jdjc, String wsjd,
			String wfbmjl, String wjcr, String zlwjsp, String kdcgfw,
			String ayzc, String qkbss, String cssmhd) {
		this.id = id;
		this.version = version;
		this.truancy = truancy;
		this.selfcheck = selfcheck;
		this.nopass = nopass;
		this.abroad = abroad;
		this.leaks = leaks;
		this.retaliation = retaliation;
		this.destructionequip = destructionequip;
		this.refusecheck = refusecheck;
		this.randomdense = randomdense;
		this.mrandomdense = mrandomdense;
		this.distributionscope = distributionscope;
		this.transforclassified = transforclassified;
		this.borrowing = borrowing;
		this.intensivelogo = intensivelogo;
		this.carryout = carryout;
		this.jmcarryout = jmcarryout;
		this.printzl = printzl;
		this.confidentiality = confidentiality;
		this.storecarrier = storecarrier;
		this.kconfidential = kconfidential;
		this.keepjm = keepjm;
		this.bmbsybg = bmbsybg;
		this.xhdj = xhdj;
		this.xhgrq = xhgrq;
		this.syhysb = syhysb;
		this.confregist = confregist;
		this.xhzlwj = xhzlwj;
		this.gbsj = gbsj;
		this.videos = videos;
		this.inforprocess = inforprocess;
		this.formatting = formatting;
		this.dellog = dellog;
		this.bmbs = bmbs;
		this.cysmdj = cysmdj;
		this.aqbmcp = aqbmcp;
		this.maintenance = maintenance;
		this.azcc = azcc;
		this.wbsb = wbsb;
		this.fsfunction = fsfunction;
		this.storeinfor = storeinfor;
		this.conmp = conmp;
		this.dmjmedium = dmjmedium;
		this.usegmj = usegmj;
		this.middleconver = middleconver;
		this.isolatesocket = isolatesocket;
		this.carrymedium = carrymedium;
		this.bmjcmedium = bmjcmedium;
		this.checkinfor = checkinfor;
		this.clsw = clsw;
		this.grconmedium = grconmedium;
		this.classifiedequip = classifiedequip;
		this.noclogo = noclogo;
		this.wirelesscon = wirelesscon;
		this.mprocess = mprocess;
		this.uwire = uwire;
		this.ucommunication = ucommunication;
		this.mobileinto = mobileinto;
		this.umobile = umobile;
		this.mobilelx = mobilelx;
		this.faxcopy = faxcopy;
		this.deliveryinfor = deliveryinfor;
		this.receiveinterview = receiveinterview;
		this.wbmzg = wbmzg;
		this.wqbmxy = wqbmxy;
		this.jsyq = jsyq;
		this.jdjc = jdjc;
		this.wsjd = wsjd;
		this.wfbmjl = wfbmjl;
		this.wjcr = wjcr;
		this.zlwjsp = zlwjsp;
		this.kdcgfw = kdcgfw;
		this.ayzc = ayzc;
		this.qkbss = qkbss;
		this.cssmhd = cssmhd;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getTruancy() {
		return this.truancy;
	}

	public void setTruancy(String truancy) {
		this.truancy = truancy;
	}

	public String getSelfcheck() {
		return this.selfcheck;
	}

	public void setSelfcheck(String selfcheck) {
		this.selfcheck = selfcheck;
	}

	public String getNopass() {
		return this.nopass;
	}

	public void setNopass(String nopass) {
		this.nopass = nopass;
	}

	public String getAbroad() {
		return this.abroad;
	}

	public void setAbroad(String abroad) {
		this.abroad = abroad;
	}

	public String getLeaks() {
		return this.leaks;
	}

	public void setLeaks(String leaks) {
		this.leaks = leaks;
	}

	public String getRetaliation() {
		return this.retaliation;
	}

	public void setRetaliation(String retaliation) {
		this.retaliation = retaliation;
	}

	public String getDestructionequip() {
		return this.destructionequip;
	}

	public void setDestructionequip(String destructionequip) {
		this.destructionequip = destructionequip;
	}

	public String getRefusecheck() {
		return this.refusecheck;
	}

	public void setRefusecheck(String refusecheck) {
		this.refusecheck = refusecheck;
	}

	public String getRandomdense() {
		return this.randomdense;
	}

	public void setRandomdense(String randomdense) {
		this.randomdense = randomdense;
	}

	public String getMrandomdense() {
		return this.mrandomdense;
	}

	public void setMrandomdense(String mrandomdense) {
		this.mrandomdense = mrandomdense;
	}

	public String getDistributionscope() {
		return this.distributionscope;
	}

	public void setDistributionscope(String distributionscope) {
		this.distributionscope = distributionscope;
	}

	public String getTransforclassified() {
		return this.transforclassified;
	}

	public void setTransforclassified(String transforclassified) {
		this.transforclassified = transforclassified;
	}

	public String getBorrowing() {
		return this.borrowing;
	}

	public void setBorrowing(String borrowing) {
		this.borrowing = borrowing;
	}

	public String getIntensivelogo() {
		return this.intensivelogo;
	}

	public void setIntensivelogo(String intensivelogo) {
		this.intensivelogo = intensivelogo;
	}

	public String getCarryout() {
		return this.carryout;
	}

	public void setCarryout(String carryout) {
		this.carryout = carryout;
	}

	public String getJmcarryout() {
		return this.jmcarryout;
	}

	public void setJmcarryout(String jmcarryout) {
		this.jmcarryout = jmcarryout;
	}

	public String getPrintzl() {
		return this.printzl;
	}

	public void setPrintzl(String printzl) {
		this.printzl = printzl;
	}

	public String getConfidentiality() {
		return this.confidentiality;
	}

	public void setConfidentiality(String confidentiality) {
		this.confidentiality = confidentiality;
	}

	public String getStorecarrier() {
		return this.storecarrier;
	}

	public void setStorecarrier(String storecarrier) {
		this.storecarrier = storecarrier;
	}

	public String getKconfidential() {
		return this.kconfidential;
	}

	public void setKconfidential(String kconfidential) {
		this.kconfidential = kconfidential;
	}

	public String getKeepjm() {
		return this.keepjm;
	}

	public void setKeepjm(String keepjm) {
		this.keepjm = keepjm;
	}

	public String getBmbsybg() {
		return this.bmbsybg;
	}

	public void setBmbsybg(String bmbsybg) {
		this.bmbsybg = bmbsybg;
	}

	public String getXhdj() {
		return this.xhdj;
	}

	public void setXhdj(String xhdj) {
		this.xhdj = xhdj;
	}

	public String getXhgrq() {
		return this.xhgrq;
	}

	public void setXhgrq(String xhgrq) {
		this.xhgrq = xhgrq;
	}

	public String getSyhysb() {
		return this.syhysb;
	}

	public void setSyhysb(String syhysb) {
		this.syhysb = syhysb;
	}

	public String getConfregist() {
		return this.confregist;
	}

	public void setConfregist(String confregist) {
		this.confregist = confregist;
	}

	public String getXhzlwj() {
		return this.xhzlwj;
	}

	public void setXhzlwj(String xhzlwj) {
		this.xhzlwj = xhzlwj;
	}

	public String getGbsj() {
		return this.gbsj;
	}

	public void setGbsj(String gbsj) {
		this.gbsj = gbsj;
	}

	public String getVideos() {
		return this.videos;
	}

	public void setVideos(String videos) {
		this.videos = videos;
	}

	public String getInforprocess() {
		return this.inforprocess;
	}

	public void setInforprocess(String inforprocess) {
		this.inforprocess = inforprocess;
	}

	public String getFormatting() {
		return this.formatting;
	}

	public void setFormatting(String formatting) {
		this.formatting = formatting;
	}

	public String getDellog() {
		return this.dellog;
	}

	public void setDellog(String dellog) {
		this.dellog = dellog;
	}

	public String getBmbs() {
		return this.bmbs;
	}

	public void setBmbs(String bmbs) {
		this.bmbs = bmbs;
	}

	public String getCysmdj() {
		return this.cysmdj;
	}

	public void setCysmdj(String cysmdj) {
		this.cysmdj = cysmdj;
	}

	public String getAqbmcp() {
		return this.aqbmcp;
	}

	public void setAqbmcp(String aqbmcp) {
		this.aqbmcp = aqbmcp;
	}

	public String getMaintenance() {
		return this.maintenance;
	}

	public void setMaintenance(String maintenance) {
		this.maintenance = maintenance;
	}

	public String getAzcc() {
		return this.azcc;
	}

	public void setAzcc(String azcc) {
		this.azcc = azcc;
	}

	public String getWbsb() {
		return this.wbsb;
	}

	public void setWbsb(String wbsb) {
		this.wbsb = wbsb;
	}

	public String getFsfunction() {
		return this.fsfunction;
	}

	public void setFsfunction(String fsfunction) {
		this.fsfunction = fsfunction;
	}

	public String getStoreinfor() {
		return this.storeinfor;
	}

	public void setStoreinfor(String storeinfor) {
		this.storeinfor = storeinfor;
	}

	public String getConmp() {
		return this.conmp;
	}

	public void setConmp(String conmp) {
		this.conmp = conmp;
	}

	public String getDmjmedium() {
		return this.dmjmedium;
	}

	public void setDmjmedium(String dmjmedium) {
		this.dmjmedium = dmjmedium;
	}

	public String getUsegmj() {
		return this.usegmj;
	}

	public void setUsegmj(String usegmj) {
		this.usegmj = usegmj;
	}

	public String getMiddleconver() {
		return this.middleconver;
	}

	public void setMiddleconver(String middleconver) {
		this.middleconver = middleconver;
	}

	public String getIsolatesocket() {
		return this.isolatesocket;
	}

	public void setIsolatesocket(String isolatesocket) {
		this.isolatesocket = isolatesocket;
	}

	public String getCarrymedium() {
		return this.carrymedium;
	}

	public void setCarrymedium(String carrymedium) {
		this.carrymedium = carrymedium;
	}

	public String getBmjcmedium() {
		return this.bmjcmedium;
	}

	public void setBmjcmedium(String bmjcmedium) {
		this.bmjcmedium = bmjcmedium;
	}

	public String getCheckinfor() {
		return this.checkinfor;
	}

	public void setCheckinfor(String checkinfor) {
		this.checkinfor = checkinfor;
	}

	public String getClsw() {
		return this.clsw;
	}

	public void setClsw(String clsw) {
		this.clsw = clsw;
	}

	public String getGrconmedium() {
		return this.grconmedium;
	}

	public void setGrconmedium(String grconmedium) {
		this.grconmedium = grconmedium;
	}

	public String getClassifiedequip() {
		return this.classifiedequip;
	}

	public void setClassifiedequip(String classifiedequip) {
		this.classifiedequip = classifiedequip;
	}

	public String getNoclogo() {
		return this.noclogo;
	}

	public void setNoclogo(String noclogo) {
		this.noclogo = noclogo;
	}

	public String getWirelesscon() {
		return this.wirelesscon;
	}

	public void setWirelesscon(String wirelesscon) {
		this.wirelesscon = wirelesscon;
	}

	public String getMprocess() {
		return this.mprocess;
	}

	public void setMprocess(String mprocess) {
		this.mprocess = mprocess;
	}

	public String getUwire() {
		return this.uwire;
	}

	public void setUwire(String uwire) {
		this.uwire = uwire;
	}

	public String getUcommunication() {
		return this.ucommunication;
	}

	public void setUcommunication(String ucommunication) {
		this.ucommunication = ucommunication;
	}

	public String getMobileinto() {
		return this.mobileinto;
	}

	public void setMobileinto(String mobileinto) {
		this.mobileinto = mobileinto;
	}

	public String getUmobile() {
		return this.umobile;
	}

	public void setUmobile(String umobile) {
		this.umobile = umobile;
	}

	public String getMobilelx() {
		return this.mobilelx;
	}

	public void setMobilelx(String mobilelx) {
		this.mobilelx = mobilelx;
	}

	public String getFaxcopy() {
		return this.faxcopy;
	}

	public void setFaxcopy(String faxcopy) {
		this.faxcopy = faxcopy;
	}

	public String getDeliveryinfor() {
		return this.deliveryinfor;
	}

	public void setDeliveryinfor(String deliveryinfor) {
		this.deliveryinfor = deliveryinfor;
	}

	public String getReceiveinterview() {
		return this.receiveinterview;
	}

	public void setReceiveinterview(String receiveinterview) {
		this.receiveinterview = receiveinterview;
	}

	public String getWbmzg() {
		return this.wbmzg;
	}

	public void setWbmzg(String wbmzg) {
		this.wbmzg = wbmzg;
	}

	public String getWqbmxy() {
		return this.wqbmxy;
	}

	public void setWqbmxy(String wqbmxy) {
		this.wqbmxy = wqbmxy;
	}

	public String getJsyq() {
		return this.jsyq;
	}

	public void setJsyq(String jsyq) {
		this.jsyq = jsyq;
	}

	public String getJdjc() {
		return this.jdjc;
	}

	public void setJdjc(String jdjc) {
		this.jdjc = jdjc;
	}

	public String getWsjd() {
		return this.wsjd;
	}

	public void setWsjd(String wsjd) {
		this.wsjd = wsjd;
	}

	public String getWfbmjl() {
		return this.wfbmjl;
	}

	public void setWfbmjl(String wfbmjl) {
		this.wfbmjl = wfbmjl;
	}

	public String getWjcr() {
		return this.wjcr;
	}

	public void setWjcr(String wjcr) {
		this.wjcr = wjcr;
	}

	public String getZlwjsp() {
		return this.zlwjsp;
	}

	public void setZlwjsp(String zlwjsp) {
		this.zlwjsp = zlwjsp;
	}

	public String getKdcgfw() {
		return this.kdcgfw;
	}

	public void setKdcgfw(String kdcgfw) {
		this.kdcgfw = kdcgfw;
	}

	public String getAyzc() {
		return this.ayzc;
	}

	public void setAyzc(String ayzc) {
		this.ayzc = ayzc;
	}

	public String getQkbss() {
		return this.qkbss;
	}

	public void setQkbss(String qkbss) {
		this.qkbss = qkbss;
	}

	public String getCssmhd() {
		return this.cssmhd;
	}

	public void setCssmhd(String cssmhd) {
		this.cssmhd = cssmhd;
	}

}