package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSCooperationcheckTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSCooperationcheckTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String deptname;
	private String enterprisepro;
	private String legalpers;
	private String supedept;
	private String mailaddress;
	private String postcode;
	private String cellphone;
	private String fax;
	private String securitydept;
	private String bmtel;
	private Integer checktype;
	private Integer deptbelong;
	private String belongelse;
	private Date begindate;
	private Date enddate;
	private Integer isorgperfect;
	private Integer isauthorclear;
	private Integer issysclear;
	private Integer ishavesys;
	private Integer isflowclear;
	private Integer issecident;
	private Integer isstrictcheck;
	private Integer issecedu;
	private Integer issigndoc;
	private Integer isprocright;
	private Integer isstandard;
	private Integer isaccordgd;
	private Integer ismeasure;
	private Integer isconfdept;
	private Integer isdeptperfect;
	private Integer iseffeaction;
	private Integer isisolation;
	private Integer isdutyclear;
	private Integer iscontrol;
	private Integer isfoxcontrol;
	private Integer issecwork;
	private Integer iskeep;
	private Integer isszcopy;
	private Integer isusecarrier;
	private Integer iscorrect;
	private Integer ishappen;
	private String checkcondition;
	private String orgsign;
	private Integer orgsignid;
	private Date orgdate;
	private String xzdeptprom;
	private String fgleader;
	private Integer fgleaderid;
	private Date fgsigndate;
	private String checkopinion;
	private String deptleader;
	private Integer deptleaderid;
	private Date leaderdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSCooperationcheckTab() {
	}

	/** minimal constructor */
	public AbstractSCooperationcheckTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSCooperationcheckTab(Integer id, Integer version,
			String deptname, String enterprisepro, String legalpers,
			String supedept, String mailaddress, String postcode,
			String cellphone, String fax, String securitydept, String bmtel,
			Integer checktype, Integer deptbelong, String belongelse,
			Date begindate, Date enddate, Integer isorgperfect,
			Integer isauthorclear, Integer issysclear, Integer ishavesys,
			Integer isflowclear, Integer issecident, Integer isstrictcheck,
			Integer issecedu, Integer issigndoc, Integer isprocright,
			Integer isstandard, Integer isaccordgd, Integer ismeasure,
			Integer isconfdept, Integer isdeptperfect, Integer iseffeaction,
			Integer isisolation, Integer isdutyclear, Integer iscontrol,
			Integer isfoxcontrol, Integer issecwork, Integer iskeep,
			Integer isszcopy, Integer isusecarrier, Integer iscorrect,
			Integer ishappen, String checkcondition, String orgsign,
			Integer orgsignid, Date orgdate, String xzdeptprom,
			String fgleader, Integer fgleaderid, Date fgsigndate,
			String checkopinion, String deptleader, Integer deptleaderid,
			Date leaderdate) {
		this.id = id;
		this.version = version;
		this.deptname = deptname;
		this.enterprisepro = enterprisepro;
		this.legalpers = legalpers;
		this.supedept = supedept;
		this.mailaddress = mailaddress;
		this.postcode = postcode;
		this.cellphone = cellphone;
		this.fax = fax;
		this.securitydept = securitydept;
		this.bmtel = bmtel;
		this.checktype = checktype;
		this.deptbelong = deptbelong;
		this.belongelse = belongelse;
		this.begindate = begindate;
		this.enddate = enddate;
		this.isorgperfect = isorgperfect;
		this.isauthorclear = isauthorclear;
		this.issysclear = issysclear;
		this.ishavesys = ishavesys;
		this.isflowclear = isflowclear;
		this.issecident = issecident;
		this.isstrictcheck = isstrictcheck;
		this.issecedu = issecedu;
		this.issigndoc = issigndoc;
		this.isprocright = isprocright;
		this.isstandard = isstandard;
		this.isaccordgd = isaccordgd;
		this.ismeasure = ismeasure;
		this.isconfdept = isconfdept;
		this.isdeptperfect = isdeptperfect;
		this.iseffeaction = iseffeaction;
		this.isisolation = isisolation;
		this.isdutyclear = isdutyclear;
		this.iscontrol = iscontrol;
		this.isfoxcontrol = isfoxcontrol;
		this.issecwork = issecwork;
		this.iskeep = iskeep;
		this.isszcopy = isszcopy;
		this.isusecarrier = isusecarrier;
		this.iscorrect = iscorrect;
		this.ishappen = ishappen;
		this.checkcondition = checkcondition;
		this.orgsign = orgsign;
		this.orgsignid = orgsignid;
		this.orgdate = orgdate;
		this.xzdeptprom = xzdeptprom;
		this.fgleader = fgleader;
		this.fgleaderid = fgleaderid;
		this.fgsigndate = fgsigndate;
		this.checkopinion = checkopinion;
		this.deptleader = deptleader;
		this.deptleaderid = deptleaderid;
		this.leaderdate = leaderdate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public String getEnterprisepro() {
		return this.enterprisepro;
	}

	public void setEnterprisepro(String enterprisepro) {
		this.enterprisepro = enterprisepro;
	}

	public String getLegalpers() {
		return this.legalpers;
	}

	public void setLegalpers(String legalpers) {
		this.legalpers = legalpers;
	}

	public String getSupedept() {
		return this.supedept;
	}

	public void setSupedept(String supedept) {
		this.supedept = supedept;
	}

	public String getMailaddress() {
		return this.mailaddress;
	}

	public void setMailaddress(String mailaddress) {
		this.mailaddress = mailaddress;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getSecuritydept() {
		return this.securitydept;
	}

	public void setSecuritydept(String securitydept) {
		this.securitydept = securitydept;
	}

	public String getBmtel() {
		return this.bmtel;
	}

	public void setBmtel(String bmtel) {
		this.bmtel = bmtel;
	}

	public Integer getChecktype() {
		return this.checktype;
	}

	public void setChecktype(Integer checktype) {
		this.checktype = checktype;
	}

	public Integer getDeptbelong() {
		return this.deptbelong;
	}

	public void setDeptbelong(Integer deptbelong) {
		this.deptbelong = deptbelong;
	}

	public String getBelongelse() {
		return this.belongelse;
	}

	public void setBelongelse(String belongelse) {
		this.belongelse = belongelse;
	}

	public Date getBegindate() {
		return this.begindate;
	}

	public void setBegindate(Date begindate) {
		this.begindate = begindate;
	}

	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	public Integer getIsorgperfect() {
		return this.isorgperfect;
	}

	public void setIsorgperfect(Integer isorgperfect) {
		this.isorgperfect = isorgperfect;
	}

	public Integer getIsauthorclear() {
		return this.isauthorclear;
	}

	public void setIsauthorclear(Integer isauthorclear) {
		this.isauthorclear = isauthorclear;
	}

	public Integer getIssysclear() {
		return this.issysclear;
	}

	public void setIssysclear(Integer issysclear) {
		this.issysclear = issysclear;
	}

	public Integer getIshavesys() {
		return this.ishavesys;
	}

	public void setIshavesys(Integer ishavesys) {
		this.ishavesys = ishavesys;
	}

	public Integer getIsflowclear() {
		return this.isflowclear;
	}

	public void setIsflowclear(Integer isflowclear) {
		this.isflowclear = isflowclear;
	}

	public Integer getIssecident() {
		return this.issecident;
	}

	public void setIssecident(Integer issecident) {
		this.issecident = issecident;
	}

	public Integer getIsstrictcheck() {
		return this.isstrictcheck;
	}

	public void setIsstrictcheck(Integer isstrictcheck) {
		this.isstrictcheck = isstrictcheck;
	}

	public Integer getIssecedu() {
		return this.issecedu;
	}

	public void setIssecedu(Integer issecedu) {
		this.issecedu = issecedu;
	}

	public Integer getIssigndoc() {
		return this.issigndoc;
	}

	public void setIssigndoc(Integer issigndoc) {
		this.issigndoc = issigndoc;
	}

	public Integer getIsprocright() {
		return this.isprocright;
	}

	public void setIsprocright(Integer isprocright) {
		this.isprocright = isprocright;
	}

	public Integer getIsstandard() {
		return this.isstandard;
	}

	public void setIsstandard(Integer isstandard) {
		this.isstandard = isstandard;
	}

	public Integer getIsaccordgd() {
		return this.isaccordgd;
	}

	public void setIsaccordgd(Integer isaccordgd) {
		this.isaccordgd = isaccordgd;
	}

	public Integer getIsmeasure() {
		return this.ismeasure;
	}

	public void setIsmeasure(Integer ismeasure) {
		this.ismeasure = ismeasure;
	}

	public Integer getIsconfdept() {
		return this.isconfdept;
	}

	public void setIsconfdept(Integer isconfdept) {
		this.isconfdept = isconfdept;
	}

	public Integer getIsdeptperfect() {
		return this.isdeptperfect;
	}

	public void setIsdeptperfect(Integer isdeptperfect) {
		this.isdeptperfect = isdeptperfect;
	}

	public Integer getIseffeaction() {
		return this.iseffeaction;
	}

	public void setIseffeaction(Integer iseffeaction) {
		this.iseffeaction = iseffeaction;
	}

	public Integer getIsisolation() {
		return this.isisolation;
	}

	public void setIsisolation(Integer isisolation) {
		this.isisolation = isisolation;
	}

	public Integer getIsdutyclear() {
		return this.isdutyclear;
	}

	public void setIsdutyclear(Integer isdutyclear) {
		this.isdutyclear = isdutyclear;
	}

	public Integer getIscontrol() {
		return this.iscontrol;
	}

	public void setIscontrol(Integer iscontrol) {
		this.iscontrol = iscontrol;
	}

	public Integer getIsfoxcontrol() {
		return this.isfoxcontrol;
	}

	public void setIsfoxcontrol(Integer isfoxcontrol) {
		this.isfoxcontrol = isfoxcontrol;
	}

	public Integer getIssecwork() {
		return this.issecwork;
	}

	public void setIssecwork(Integer issecwork) {
		this.issecwork = issecwork;
	}

	public Integer getIskeep() {
		return this.iskeep;
	}

	public void setIskeep(Integer iskeep) {
		this.iskeep = iskeep;
	}

	public Integer getIsszcopy() {
		return this.isszcopy;
	}

	public void setIsszcopy(Integer isszcopy) {
		this.isszcopy = isszcopy;
	}

	public Integer getIsusecarrier() {
		return this.isusecarrier;
	}

	public void setIsusecarrier(Integer isusecarrier) {
		this.isusecarrier = isusecarrier;
	}

	public Integer getIscorrect() {
		return this.iscorrect;
	}

	public void setIscorrect(Integer iscorrect) {
		this.iscorrect = iscorrect;
	}

	public Integer getIshappen() {
		return this.ishappen;
	}

	public void setIshappen(Integer ishappen) {
		this.ishappen = ishappen;
	}

	public String getCheckcondition() {
		return this.checkcondition;
	}

	public void setCheckcondition(String checkcondition) {
		this.checkcondition = checkcondition;
	}

	public String getOrgsign() {
		return this.orgsign;
	}

	public void setOrgsign(String orgsign) {
		this.orgsign = orgsign;
	}

	public Integer getOrgsignid() {
		return this.orgsignid;
	}

	public void setOrgsignid(Integer orgsignid) {
		this.orgsignid = orgsignid;
	}

	public Date getOrgdate() {
		return this.orgdate;
	}

	public void setOrgdate(Date orgdate) {
		this.orgdate = orgdate;
	}

	public String getXzdeptprom() {
		return this.xzdeptprom;
	}

	public void setXzdeptprom(String xzdeptprom) {
		this.xzdeptprom = xzdeptprom;
	}

	public String getFgleader() {
		return this.fgleader;
	}

	public void setFgleader(String fgleader) {
		this.fgleader = fgleader;
	}

	public Integer getFgleaderid() {
		return this.fgleaderid;
	}

	public void setFgleaderid(Integer fgleaderid) {
		this.fgleaderid = fgleaderid;
	}

	public Date getFgsigndate() {
		return this.fgsigndate;
	}

	public void setFgsigndate(Date fgsigndate) {
		this.fgsigndate = fgsigndate;
	}

	public String getCheckopinion() {
		return this.checkopinion;
	}

	public void setCheckopinion(String checkopinion) {
		this.checkopinion = checkopinion;
	}

	public String getDeptleader() {
		return this.deptleader;
	}

	public void setDeptleader(String deptleader) {
		this.deptleader = deptleader;
	}

	public Integer getDeptleaderid() {
		return this.deptleaderid;
	}

	public void setDeptleaderid(Integer deptleaderid) {
		this.deptleaderid = deptleaderid;
	}

	public Date getLeaderdate() {
		return this.leaderdate;
	}

	public void setLeaderdate(Date leaderdate) {
		this.leaderdate = leaderdate;
	}

}