package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractATelltalerecordTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractATelltalerecordTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer eventtype;
	private Date happendate;
	private String happenreason;
	private String effectrange;
	private String measures;
	private String result;
	private String informant;
	private Integer informantid;
	private String checker;
	private Integer checkerid;

	// Constructors

	/** default constructor */
	public AbstractATelltalerecordTab() {
	}

	/** minimal constructor */
	public AbstractATelltalerecordTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractATelltalerecordTab(Integer id, Integer version,
			Integer eventtype, Date happendate, String happenreason,
			String effectrange, String measures, String result,
			String informant, Integer informantid, String checker,
			Integer checkerid) {
		this.id = id;
		this.version = version;
		this.eventtype = eventtype;
		this.happendate = happendate;
		this.happenreason = happenreason;
		this.effectrange = effectrange;
		this.measures = measures;
		this.result = result;
		this.informant = informant;
		this.informantid = informantid;
		this.checker = checker;
		this.checkerid = checkerid;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getEventtype() {
		return this.eventtype;
	}

	public void setEventtype(Integer eventtype) {
		this.eventtype = eventtype;
	}

	public Date getHappendate() {
		return this.happendate;
	}

	public void setHappendate(Date happendate) {
		this.happendate = happendate;
	}

	public String getHappenreason() {
		return this.happenreason;
	}

	public void setHappenreason(String happenreason) {
		this.happenreason = happenreason;
	}

	public String getEffectrange() {
		return this.effectrange;
	}

	public void setEffectrange(String effectrange) {
		this.effectrange = effectrange;
	}

	public String getMeasures() {
		return this.measures;
	}

	public void setMeasures(String measures) {
		this.measures = measures;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getInformant() {
		return this.informant;
	}

	public void setInformant(String informant) {
		this.informant = informant;
	}

	public Integer getInformantid() {
		return this.informantid;
	}

	public void setInformantid(Integer informantid) {
		this.informantid = informantid;
	}

	public String getChecker() {
		return this.checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public Integer getCheckerid() {
		return this.checkerid;
	}

	public void setCheckerid(Integer checkerid) {
		this.checkerid = checkerid;
	}

}