package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAOasysalterTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAOasysalterTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Date formdate;
	private String agent;
	private String cellphone;
	private String deptalter;
	private String chushialter;
	private String typeelse;
	private String askfor;
	private String applydeptopinion;
	private String applydeptsign;
	private Integer applydeptsignid;
	private Date applydeptsigndate;
	private String officeopinion;
	private String officesign;
	private Integer officesignid;
	private Date officesigndate;
	private String investopinion;
	private String investsign;
	private Integer investsignid;
	private Date investsigndate;
	private String trancondition;
	private String transign;
	private Integer transignid;
	private Date transigndate;

	// Constructors

	/** default constructor */
	public AbstractAOasysalterTab() {
	}

	/** minimal constructor */
	public AbstractAOasysalterTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAOasysalterTab(Integer id, Integer version, Date formdate,
			String agent, String cellphone, String deptalter,
			String chushialter, String typeelse, String askfor,
			String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String officeopinion, String officesign, Integer officesignid,
			Date officesigndate, String investopinion, String investsign,
			Integer investsignid, Date investsigndate, String trancondition,
			String transign, Integer transignid, Date transigndate) {
		this.id = id;
		this.version = version;
		this.formdate = formdate;
		this.agent = agent;
		this.cellphone = cellphone;
		this.deptalter = deptalter;
		this.chushialter = chushialter;
		this.typeelse = typeelse;
		this.askfor = askfor;
		this.applydeptopinion = applydeptopinion;
		this.applydeptsign = applydeptsign;
		this.applydeptsignid = applydeptsignid;
		this.applydeptsigndate = applydeptsigndate;
		this.officeopinion = officeopinion;
		this.officesign = officesign;
		this.officesignid = officesignid;
		this.officesigndate = officesigndate;
		this.investopinion = investopinion;
		this.investsign = investsign;
		this.investsignid = investsignid;
		this.investsigndate = investsigndate;
		this.trancondition = trancondition;
		this.transign = transign;
		this.transignid = transignid;
		this.transigndate = transigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Date getFormdate() {
		return this.formdate;
	}

	public void setFormdate(Date formdate) {
		this.formdate = formdate;
	}

	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getDeptalter() {
		return this.deptalter;
	}

	public void setDeptalter(String deptalter) {
		this.deptalter = deptalter;
	}

	public String getChushialter() {
		return this.chushialter;
	}

	public void setChushialter(String chushialter) {
		this.chushialter = chushialter;
	}

	public String getTypeelse() {
		return this.typeelse;
	}

	public void setTypeelse(String typeelse) {
		this.typeelse = typeelse;
	}

	public String getAskfor() {
		return this.askfor;
	}

	public void setAskfor(String askfor) {
		this.askfor = askfor;
	}

	public String getApplydeptopinion() {
		return this.applydeptopinion;
	}

	public void setApplydeptopinion(String applydeptopinion) {
		this.applydeptopinion = applydeptopinion;
	}

	public String getApplydeptsign() {
		return this.applydeptsign;
	}

	public void setApplydeptsign(String applydeptsign) {
		this.applydeptsign = applydeptsign;
	}

	public Integer getApplydeptsignid() {
		return this.applydeptsignid;
	}

	public void setApplydeptsignid(Integer applydeptsignid) {
		this.applydeptsignid = applydeptsignid;
	}

	public Date getApplydeptsigndate() {
		return this.applydeptsigndate;
	}

	public void setApplydeptsigndate(Date applydeptsigndate) {
		this.applydeptsigndate = applydeptsigndate;
	}

	public String getOfficeopinion() {
		return this.officeopinion;
	}

	public void setOfficeopinion(String officeopinion) {
		this.officeopinion = officeopinion;
	}

	public String getOfficesign() {
		return this.officesign;
	}

	public void setOfficesign(String officesign) {
		this.officesign = officesign;
	}

	public Integer getOfficesignid() {
		return this.officesignid;
	}

	public void setOfficesignid(Integer officesignid) {
		this.officesignid = officesignid;
	}

	public Date getOfficesigndate() {
		return this.officesigndate;
	}

	public void setOfficesigndate(Date officesigndate) {
		this.officesigndate = officesigndate;
	}

	public String getInvestopinion() {
		return this.investopinion;
	}

	public void setInvestopinion(String investopinion) {
		this.investopinion = investopinion;
	}

	public String getInvestsign() {
		return this.investsign;
	}

	public void setInvestsign(String investsign) {
		this.investsign = investsign;
	}

	public Integer getInvestsignid() {
		return this.investsignid;
	}

	public void setInvestsignid(Integer investsignid) {
		this.investsignid = investsignid;
	}

	public Date getInvestsigndate() {
		return this.investsigndate;
	}

	public void setInvestsigndate(Date investsigndate) {
		this.investsigndate = investsigndate;
	}

	public String getTrancondition() {
		return this.trancondition;
	}

	public void setTrancondition(String trancondition) {
		this.trancondition = trancondition;
	}

	public String getTransign() {
		return this.transign;
	}

	public void setTransign(String transign) {
		this.transign = transign;
	}

	public Integer getTransignid() {
		return this.transignid;
	}

	public void setTransignid(Integer transignid) {
		this.transignid = transignid;
	}

	public Date getTransigndate() {
		return this.transigndate;
	}

	public void setTransigndate(Date transigndate) {
		this.transigndate = transigndate;
	}

}