package com.manage.temp.model.original;

/**
 * AbstractSSocialfamilyTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSSocialfamilyTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer eqid;
	private String relation;
	private Integer sex;
	private Integer age;
	private String name;
	private String national;
	private String workunit;

	// Constructors

	/** default constructor */
	public AbstractSSocialfamilyTab() {
	}

	/** minimal constructor */
	public AbstractSSocialfamilyTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSSocialfamilyTab(Integer id, Integer version, Integer eqid,
			String relation, Integer sex, Integer age, String name,
			String national, String workunit) {
		this.id = id;
		this.version = version;
		this.eqid = eqid;
		this.relation = relation;
		this.sex = sex;
		this.age = age;
		this.name = name;
		this.national = national;
		this.workunit = workunit;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getEqid() {
		return this.eqid;
	}

	public void setEqid(Integer eqid) {
		this.eqid = eqid;
	}

	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNational() {
		return this.national;
	}

	public void setNational(String national) {
		this.national = national;
	}

	public String getWorkunit() {
		return this.workunit;
	}

	public void setWorkunit(String workunit) {
		this.workunit = workunit;
	}

}