package com.manage.cooperationcheck.model;

import com.manage.cooperationcheck.model.original.AbstractCooperationCheck;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class CooperationCheck extends AbstractCooperationCheck {

}
