package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSClassifieddestroyInfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SClassifieddestroyInfoTab generated by MyEclipse Persistence Tools
 */
public class SClassifieddestroyInfoTab extends
		AbstractSClassifieddestroyInfoTab implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SClassifieddestroyInfoTab() {
	}

	/** minimal constructor */
	public SClassifieddestroyInfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SClassifieddestroyInfoTab(Integer id, Integer version, Integer cdid,
			String filename, String productunit, Integer carriertype,
			String code, String classification, Integer pages, Integer copies,
			Integer depositoryid, String depository) {
		super(id, version, cdid, filename, productunit, carriertype, code,
				classification, pages, copies, depositoryid, depository);
	}

}
