package com.manage.internetaccount.model;

import com.manage.internetaccount.model.original.AbstractInternetAccount;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class InternetAccount extends AbstractInternetAccount {

}
