package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSFilmingactivityTab;

/**
 * SFilmingactivityTab generated by MyEclipse Persistence Tools
 */
public class SFilmingactivityTab extends AbstractSFilmingactivityTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SFilmingactivityTab() {
	}

	/** minimal constructor */
	public SFilmingactivityTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SFilmingactivityTab(Integer id, Integer version, String orgname,
			String orgid, String shead, String purpose, String shootrange,
			Date shootdate, Integer isclassification, String classification,
			String cameras, String monitors, String trackrecord,
			String depdesc, String depsign, Integer depid, Date depdate,
			String partdesc, String partsign, Integer partid, Date partdate,
			String officedesc, String officesign, Integer officeid,
			Date officedate, String scomdesc, String scomsign, Integer scomid,
			Date scomdate) {
		super(id, version, orgname, orgid, shead, purpose, shootrange,
				shootdate, isclassification, classification, cameras, monitors,
				trackrecord, depdesc, depsign, depid, depdate, partdesc,
				partsign, partid, partdate, officedesc, officesign, officeid,
				officedate, scomdesc, scomsign, scomid, scomdate);
	}

}
