package com.manage.changemedium.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.changemedium.model.original.AbstractSChangemediumTab;

/**
 * SChangemediumTab generated by MyEclipse Persistence Tools
 */
public class SChangemediumTab extends AbstractSChangemediumTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SChangemediumTab() {
	}

	/** minimal constructor */
	public SChangemediumTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SChangemediumTab(Integer id, Integer version, String orgname,
			String orgid, String code,String departdesc,
			Date departdate, String officedesc, Date officedate,String username,Integer userid) {
		super(id, version, orgname, orgid, code, departdesc, departdate, officedesc,
				officedate,username,userid);
	}

}
