package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSEstoragemediumTab;

/**
 * SEstoragemediumTab generated by MyEclipse Persistence Tools
 */
public class SEstoragemediumTab extends AbstractSEstoragemediumTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SEstoragemediumTab() {
	}

	/** minimal constructor */
	public SEstoragemediumTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SEstoragemediumTab(Integer id, Integer version, String mcode,
			Date applydate, String orgname, String orgid, String depository,
			Integer depositoryid, String sign, Integer signid, Date signdate,
			String departmentdesc, String officedesc) {
		super(id, version, mcode, applydate, orgname, orgid, depository,depositoryid, signid, sign, officedesc, signid, signid, officedesc, officedesc, signid, signdate,departmentdesc, officedesc);
	}

}
