package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAWiresysrecordTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAWiresysrecordTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Date checkdate;
	private String checkplace;
	private String checkcondition;
	private String checker;
	private Integer checkerid;
	private String remark;

	// Constructors

	/** default constructor */
	public AbstractAWiresysrecordTab() {
	}

	/** minimal constructor */
	public AbstractAWiresysrecordTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAWiresysrecordTab(Integer id, Integer version,
			Date checkdate, String checkplace, String checkcondition,
			String checker, Integer checkerid, String remark) {
		this.id = id;
		this.version = version;
		this.checkdate = checkdate;
		this.checkplace = checkplace;
		this.checkcondition = checkcondition;
		this.checker = checker;
		this.checkerid = checkerid;
		this.remark = remark;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Date getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(Date checkdate) {
		this.checkdate = checkdate;
	}

	public String getCheckplace() {
		return this.checkplace;
	}

	public void setCheckplace(String checkplace) {
		this.checkplace = checkplace;
	}

	public String getCheckcondition() {
		return this.checkcondition;
	}

	public void setCheckcondition(String checkcondition) {
		this.checkcondition = checkcondition;
	}

	public String getChecker() {
		return this.checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public Integer getCheckerid() {
		return this.checkerid;
	}

	public void setCheckerid(Integer checkerid) {
		this.checkerid = checkerid;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}