package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSGetmediuminfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SGetmediuminfoTab generated by MyEclipse Persistence Tools
 */
public class SGetmediuminfoTab extends AbstractSGetmediuminfoTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SGetmediuminfoTab() {
	}

	/** minimal constructor */
	public SGetmediuminfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SGetmediuminfoTab(Integer id, Integer version, Integer eid,
			Integer rmediumtype, String rspecifications, String rscode,
			String productcode, Integer rcerttype, String rcerrange,
			String rsign, Integer rid) {
		super(id, version, eid, rmediumtype, rspecifications, rscode,
				productcode, rcerttype, rcerrange, rsign, rid);
	}

}
