package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSMigrantsioTab;

// Generated by MyEclipse Persistence Tools

/**
 * SMigrantsioTab generated by MyEclipse Persistence Tools
 */
public class SMigrantsioTab extends AbstractSMigrantsioTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SMigrantsioTab() {
	}

	/** minimal constructor */
	public SMigrantsioTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SMigrantsioTab(Integer id, Integer version, Integer aid,
			String name, String jobs, String workunit) {
		super(id, version, aid, name, jobs, workunit);
	}

}
