package com.manage.examclassification.model;

import com.manage.examclassification.model.original.AbstractSClassifiedprojectTab;

// Generated by MyEclipse Persistence Tools

/**
 * SClassifiedprojectTab generated by MyEclipse Persistence Tools
 */
public class SClassifiedprojectTab extends AbstractSClassifiedprojectTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SClassifiedprojectTab() {
	}

	/** minimal constructor */
	public SClassifiedprojectTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SClassifiedprojectTab(Integer id, Integer version, Integer ecid,
			String proname, Integer classification) {
		super(id, version, ecid, proname, classification);
	}

}
