package com.manage.examclassification.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.examclassification.model.original.AbstractSExamClassificationTab;

/**
 * SExamClassificationTab generated by MyEclipse Persistence Tools
 */
public class SExamClassificationTab extends AbstractSExamClassificationTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SExamClassificationTab() {
	}

	/** minimal constructor */
	public SExamClassificationTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SExamClassificationTab(Integer id, Integer version, String ecname,
			Integer sex, Integer age, String oriname, String orgid,
			String position, String oposition, String oclassification,Integer optype,
			String leadershipsign, Integer leaderid, Date leadersigndate,
			Integer dptype, String departmentsign, Integer departmentid,
			Date departmentdate, Integer sptype, String sofficesign,
			Date sofficesigndate, Integer sofficeid, Integer scptype,
			String scomsign, Date scomsigndate, Integer scomid,String username,Integer userid) {
		super(id, version, ecname, sex, age, oriname, orgid, position,oposition, oclassification,
				optype, leadershipsign, leaderid, leadersigndate,dptype, departmentsign, departmentid, departmentdate,
				sptype, sofficesign, sofficesigndate, sofficeid, scptype,scomsign, scomsigndate, scomid,username,userid);
	}

}
