package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSConagreementybTab;

/**
 * SConagreementybTab generated by MyEclipse Persistence Tools
 */
public class SConagreementybTab extends AbstractSConagreementybTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SConagreementybTab() {
	}

	/** minimal constructor */
	public SConagreementybTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SConagreementybTab(Integer id, Integer version, String jfcontract,
			String yfcb, String pame, String classified, String jfsign,
			Integer jfid, String yfsign, Integer yfid, Date jfdate, Date yfdate) {
		super(id, version, jfcontract, yfcb, pame, classified, jfsign, jfid,
				yfsign, yfid, jfdate, yfdate);
	}

}
