package com.manage.keypartexam.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.keypartexam.model.original.AbstractSKeypartexamTab;

/**
 * SKeypartexamTab generated by MyEclipse Persistence Tools
 */
public class SKeypartexamTab extends AbstractSKeypartexamTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SKeypartexamTab() {
	}

	/** minimal constructor */
	public SKeypartexamTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SKeypartexamTab(Integer id, Integer version, String notification,
			Integer nid, String partname, String parthead, Integer totalstaff,
			String partlocation, String declarationreason, String apmeasures,
			String ppmeasures, String tpmeasures, String uscomdesc,
			String yscomdesc, Date uscomdate, Date yscomdate,String username,Integer userid) {
		super(id, version, notification, nid, partname, parthead, totalstaff,
				partlocation, declarationreason, apmeasures, ppmeasures,
				tpmeasures, uscomdesc, yscomdesc, uscomdate, yscomdate,username,userid);
	}

}
