package com.manage.classifiedprint.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.classifiedprint.model.original.AbstractSClassifiedprintTab;

/**
 * SClassifiedprintTab generated by MyEclipse Persistence Tools
 */
public class SClassifiedprintTab extends AbstractSClassifiedprintTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SClassifiedprintTab() {
	}

	/** minimal constructor */
	public SClassifiedprintTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SClassifiedprintTab(Integer id, Integer version, Date registdate,
			String filename, Integer classification, Integer pages,
			Integer copies, String qxyt, String printername, String approver,
			Date printerdate, String rcode, String gname, Integer gid) {
		super(id, version, registdate, filename, classification, pages, copies,
				qxyt, printername, approver, printerdate, rcode, gname, gid);
	}

}
