package com.manage.temp.model.original;

/**
 * AbstractSOpeninfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSOpeninfoTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer oaid;
	private String partnum;
	private String major;
	private String species;
	private String device;
	private String purpose;

	// Constructors

	/** default constructor */
	public AbstractSOpeninfoTab() {
	}

	/** minimal constructor */
	public AbstractSOpeninfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSOpeninfoTab(Integer id, Integer version, Integer oaid,
			String partnum, String major, String species, String device,
			String purpose) {
		this.id = id;
		this.version = version;
		this.oaid = oaid;
		this.partnum = partnum;
		this.major = major;
		this.species = species;
		this.device = device;
		this.purpose = purpose;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getOaid() {
		return this.oaid;
	}

	public void setOaid(Integer oaid) {
		this.oaid = oaid;
	}

	public String getPartnum() {
		return this.partnum;
	}

	public void setPartnum(String partnum) {
		this.partnum = partnum;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

}