package com.manage.changemedium.model;

import com.manage.changemedium.model.original.AbstractSChangemediumInfoTab;

// Generated by MyEclipse Persistence Tools

/**
 * SChangemediumInfoTab generated by MyEclipse Persistence Tools
 */
public class SChangemediumInfoTab extends AbstractSChangemediumInfoTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SChangemediumInfoTab() {
	}

	/** minimal constructor */
	public SChangemediumInfoTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SChangemediumInfoTab(Integer id, Integer version, 
			String mtype, String specifications, String bcorgname,
			String bcorgid, String bcdepository, String bcclassification,
			String bcscode, String acorgname, String acorgid,
			String acdepository, String acclassification, String acscode,
			String changereason, Integer cid) {
		super(id, version,  mtype, specifications, bcorgname, bcorgid,
				bcdepository, bcclassification, bcscode, acorgname, acorgid,
				acdepository, acclassification, acscode, changereason, cid);
	}

}
