package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAFerrycentreTab;

/**
 * AFerrycentreTab generated by MyEclipse Persistence Tools
 */
public class AFerrycentreTab extends AbstractAFerrycentreTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AFerrycentreTab() {
	}

	/** minimal constructor */
	public AFerrycentreTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AFerrycentreTab(Integer id, Integer version, String applydept,
			Integer applydeptid, Integer security, String linkman,
			String cellphone, String createplace, Date applydate,
			String ferryer, Integer ferryersecurity, String applyreason,
			String applydeptopinion, String applydeptsign,
			Integer applydeptsignid, Date applydeptsigndate,
			String securityopinion, String securitysign, Integer securityid,
			Date securitysigndate, String infordeptopinion,
			String infordeptsign, Integer infordeptsignid,
			Date infordeptsigndate, String trancondition, String transign,
			Integer transignid, Date transigndate) {
		super(id, version, applydept, applydeptid, security, linkman,
				cellphone, createplace, applydate, ferryer, ferryersecurity,
				applyreason, applydeptopinion, applydeptsign, applydeptsignid,
				applydeptsigndate, securityopinion, securitysign, securityid,
				securitysigndate, infordeptopinion, infordeptsign,
				infordeptsignid, infordeptsigndate, trancondition, transign,
				transignid, transigndate);
	}

}
