package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAAuthorityalterTab;

/**
 * AAuthorityalterTab generated by MyEclipse Persistence Tools
 */
public class AAuthorityalterTab extends AbstractAAuthorityalterTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AAuthorityalterTab() {
	}

	/** minimal constructor */
	public AAuthorityalterTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AAuthorityalterTab(Integer id, Integer version, String name,
			String position, String dept, Integer security, String workplace,
			String cellphone, String alterreason,String applicantsign, Integer applicantid, Date applicantsigndate,
			String deptleaderopinion, String deptleadersign,
			Integer deptleaderid, Date leadersigndate, String securityopinion,
			String securitysign, Integer securityid, Date securitysigndate,
			Integer isfinishoperate, Integer isinformapplicat,
			String infordeptsign, Integer infordeptsignid,
			Date infordeptsigndate) {
		super(id, version, name, position, dept, security, workplace,
				cellphone, alterreason, applicantsign, applicantid,
				applicantsigndate, deptleaderopinion, deptleadersign,
				deptleaderid, leadersigndate, securityopinion, securitysign,
				securityid, securitysigndate, isfinishoperate,
				isinformapplicat, infordeptsign, infordeptsignid,
				infordeptsigndate);
	}

}
