package com.manage.changeinternet.model.original;

/**
 * AbstractSChangeinternetInfoTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSChangeinternetInfoTab implements
		java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private Integer cid;
	private String licensenum;
	private String bcorgname;
	private String bcorgid;
	private String bcsresponsible;
	private String bcserialnum;
	private String haddress;
	private String acorgname;
	private String acorgid;
	private String acsresponsible;
	private String acserialnum;
	private String achaddress;
	private String changereason;

	// Constructors

	/** default constructor */
	public AbstractSChangeinternetInfoTab() {
	}

	/** minimal constructor */
	public AbstractSChangeinternetInfoTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSChangeinternetInfoTab(Integer id, Integer version,
			Integer cid, String licensenum, String bcorgname, String bcorgid,
			String bcsresponsible, String bcserialnum, String haddress,
			String acorgname, String acorgid, String acsresponsible,
			String acserialnum, String achaddress, String changereason) {
		this.id = id;
		this.version = version;
		this.cid = cid;
		this.licensenum = licensenum;
		this.bcorgname = bcorgname;
		this.bcorgid = bcorgid;
		this.bcsresponsible = bcsresponsible;
		this.bcserialnum = bcserialnum;
		this.haddress = haddress;
		this.acorgname = acorgname;
		this.acorgid = acorgid;
		this.acsresponsible = acsresponsible;
		this.acserialnum = acserialnum;
		this.achaddress = achaddress;
		this.changereason = changereason;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getLicensenum() {
		return this.licensenum;
	}

	public void setLicensenum(String licensenum) {
		this.licensenum = licensenum;
	}

	public String getBcorgname() {
		return this.bcorgname;
	}

	public void setBcorgname(String bcorgname) {
		this.bcorgname = bcorgname;
	}

	public String getBcorgid() {
		return this.bcorgid;
	}

	public void setBcorgid(String bcorgid) {
		this.bcorgid = bcorgid;
	}

	public String getBcsresponsible() {
		return this.bcsresponsible;
	}

	public void setBcsresponsible(String bcsresponsible) {
		this.bcsresponsible = bcsresponsible;
	}

	public String getBcserialnum() {
		return this.bcserialnum;
	}

	public void setBcserialnum(String bcserialnum) {
		this.bcserialnum = bcserialnum;
	}

	public String getHaddress() {
		return this.haddress;
	}

	public void setHaddress(String haddress) {
		this.haddress = haddress;
	}

	public String getAcorgname() {
		return this.acorgname;
	}

	public void setAcorgname(String acorgname) {
		this.acorgname = acorgname;
	}

	public String getAcorgid() {
		return this.acorgid;
	}

	public void setAcorgid(String acorgid) {
		this.acorgid = acorgid;
	}

	public String getAcsresponsible() {
		return this.acsresponsible;
	}

	public void setAcsresponsible(String acsresponsible) {
		this.acsresponsible = acsresponsible;
	}

	public String getAcserialnum() {
		return this.acserialnum;
	}

	public void setAcserialnum(String acserialnum) {
		this.acserialnum = acserialnum;
	}

	public String getAchaddress() {
		return this.achaddress;
	}

	public void setAchaddress(String achaddress) {
		this.achaddress = achaddress;
	}

	public String getChangereason() {
		return this.changereason;
	}

	public void setChangereason(String changereason) {
		this.changereason = changereason;
	}

}