package com.manage.carrypartmedium.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.carrypartmedium.model.original.AbstractSCarrypartmediumTab;

/**
 * SCarrypartmediumTab generated by MyEclipse Persistence Tools
 */
public class SCarrypartmediumTab extends AbstractSCarrypartmediumTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SCarrypartmediumTab() {
	}

	/** minimal constructor */
	public SCarrypartmediumTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SCarrypartmediumTab(Integer id, Integer version, String code,
			String orgname, String orgid, String agent, String location,
			Date returndate, Date applydate, Integer mclassifition,
			String scode, String yt, String information,
			String imaxclassification, String usign, Integer uid, Date udate,
			String departmentdesc, Date departmentdate, String recheckcase,
			Date recheckdate,String username,Integer userid) {
		super(id, version, code, orgname, orgid, agent, location, returndate,
				applydate, mclassifition, scode, yt, information,
				imaxclassification, usign, uid, udate, departmentdesc,
				departmentdate, recheckcase, recheckdate,username,userid);
	}

}
