package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractSOpenapplyTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSOpenapplyTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String deptname;
	private Integer deptid;
	private Date formdate;
	private String teamname;
	private String invitedept;
	private String purpose;
	private Date lfdate;
	private String linkman;
	private String linktel;
	private String cellphone;
	private String cryptosecurity;
	private String rewsopinion;
	private String rebmopinion;
	private String respopinion;
	private String gswsopinion;
	private String gsbmopinion;
	private String gsspopinion;
	private String groupcompany;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSOpenapplyTab() {
	}

	/** minimal constructor */
	public AbstractSOpenapplyTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSOpenapplyTab(Integer id, Integer version, String deptname,
			Integer deptid, Date formdate, String teamname, String invitedept,
			String purpose, Date lfdate, String linkman, String linktel,
			String cellphone, String cryptosecurity, String rewsopinion, String rebmopinion,
			String respopinion, String gswsopinion, String gsbmopinion,
			String gsspopinion, String groupcompany) {
		this.id = id;
		this.version = version;
		this.deptname = deptname;
		this.deptid = deptid;
		this.formdate = formdate;
		this.teamname = teamname;
		this.invitedept = invitedept;
		this.purpose = purpose;
		this.lfdate = lfdate;
		this.linkman = linkman;
		this.linktel = linktel;
		this.cellphone = cellphone;
		this.cryptosecurity = cryptosecurity;
		this.rewsopinion = rewsopinion;
		this.rebmopinion = rebmopinion;
		this.respopinion = respopinion;
		this.gswsopinion = gswsopinion;
		this.gsbmopinion = gsbmopinion;
		this.gsspopinion = gsspopinion;
		this.groupcompany = groupcompany;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	public Date getFormdate() {
		return this.formdate;
	}

	public void setFormdate(Date formdate) {
		this.formdate = formdate;
	}

	public String getTeamname() {
		return this.teamname;
	}

	public void setTeamname(String teamname) {
		this.teamname = teamname;
	}

	public String getInvitedept() {
		return this.invitedept;
	}

	public void setInvitedept(String invitedept) {
		this.invitedept = invitedept;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public Date getLfdate() {
		return this.lfdate;
	}

	public void setLfdate(Date lfdate) {
		this.lfdate = lfdate;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getLinktel() {
		return this.linktel;
	}

	public void setLinktel(String linktel) {
		this.linktel = linktel;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}


	public String getCryptosecurity() {
		return this.cryptosecurity;
	}

	public void setCryptosecurity(String cryptosecurity) {
		this.cryptosecurity = cryptosecurity;
	}

	public String getRewsopinion() {
		return this.rewsopinion;
	}

	public void setRewsopinion(String rewsopinion) {
		this.rewsopinion = rewsopinion;
	}

	public String getRebmopinion() {
		return this.rebmopinion;
	}

	public void setRebmopinion(String rebmopinion) {
		this.rebmopinion = rebmopinion;
	}

	public String getRespopinion() {
		return this.respopinion;
	}

	public void setRespopinion(String respopinion) {
		this.respopinion = respopinion;
	}

	public String getGswsopinion() {
		return this.gswsopinion;
	}

	public void setGswsopinion(String gswsopinion) {
		this.gswsopinion = gswsopinion;
	}

	public String getGsbmopinion() {
		return this.gsbmopinion;
	}

	public void setGsbmopinion(String gsbmopinion) {
		this.gsbmopinion = gsbmopinion;
	}

	public String getGsspopinion() {
		return this.gsspopinion;
	}

	public void setGsspopinion(String gsspopinion) {
		this.gsspopinion = gsspopinion;
	}

	public String getGroupcompany() {
		return this.groupcompany;
	}

	public void setGroupcompany(String groupcompany) {
		this.groupcompany = groupcompany;
	}

}