package com.manage.filmingactivity.model;

import com.manage.filmingactivity.model.original.AbstractFilmingActivity;



/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class FilmingActivity extends AbstractFilmingActivity {

}
