package com.manage.depseccheck.model;

import com.manage.depseccheck.model.original.AbstractDepsecCheck;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class DepsecCheck extends AbstractDepsecCheck {

}
