package com.manage.equalification.model;

import com.manage.equalification.model.original.AbstractSSocialfamilyTab;

// Generated by MyEclipse Persistence Tools

/**
 * SSocialfamilyTab generated by MyEclipse Persistence Tools
 */
public class SSocialfamilyTab extends AbstractSSocialfamilyTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SSocialfamilyTab() {
	}

	/** minimal constructor */
	public SSocialfamilyTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SSocialfamilyTab(Integer id, Integer version, Integer eqid,
			String relation, Integer sex, Integer age, String name,
			String national, String dwzw) {
		super(id, version, eqid, relation, sex, age, name, national, dwzw);
	}

}
