package com.manage.promise.model;

import com.manage.promise.model.original.AbstractPromise;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class Promise extends AbstractPromise {

}
