package com.manage.leavepromise.model.original;

import java.util.Date;

/**
 * AbstractSLeavepromiseTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractSLeavepromiseTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String lname;
	private String pname;
	private Integer pclassification;
	private Date tstartdate;
	private Date tenddate;
	private String card;
	private String adrress;
	private String pcompany;
	private String cellphone;
	private String lpname;
	private Integer lpid;
	private Date pdate;
	private String username;
	private Integer userid;

	// Constructors

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/** default constructor */
	public AbstractSLeavepromiseTab() {
	}

	/** minimal constructor */
	public AbstractSLeavepromiseTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractSLeavepromiseTab(Integer id, Integer version, String lname,
			String pname, Integer pclassification, Date tstartdate,
			Date tenddate, String card, String adrress, String pcompany,
			String cellphone, String lpname, Integer lpid, Date pdate) {
		this.id = id;
		this.version = version;
		this.lname = lname;
		this.pname = pname;
		this.pclassification = pclassification;
		this.tstartdate = tstartdate;
		this.tenddate = tenddate;
		this.card = card;
		this.adrress = adrress;
		this.pcompany = pcompany;
		this.cellphone = cellphone;
		this.lpname = lpname;
		this.lpid = lpid;
		this.pdate = pdate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}



	public Integer getPclassification() {
		return pclassification;
	}

	public void setPclassification(Integer pclassification) {
		this.pclassification = pclassification;
	}

	public Date getTstartdate() {
		return this.tstartdate;
	}

	public void setTstartdate(Date tstartdate) {
		this.tstartdate = tstartdate;
	}

	public Date getTenddate() {
		return this.tenddate;
	}

	public void setTenddate(Date tenddate) {
		this.tenddate = tenddate;
	}

	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public String getAdrress() {
		return this.adrress;
	}

	public void setAdrress(String adrress) {
		this.adrress = adrress;
	}

	public String getPcompany() {
		return this.pcompany;
	}

	public void setPcompany(String pcompany) {
		this.pcompany = pcompany;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getLpname() {
		return this.lpname;
	}

	public void setLpname(String lpname) {
		this.lpname = lpname;
	}

	public Integer getLpid() {
		return this.lpid;
	}

	public void setLpid(Integer lpid) {
		this.lpid = lpid;
	}

	public Date getPdate() {
		return this.pdate;
	}

	public void setPdate(Date pdate) {
		this.pdate = pdate;
	}

}