package com.manage.temp.model;

import com.manage.temp.model.original.AbstractSForeignguestsTab;

// Generated by MyEclipse Persistence Tools

/**
 * SForeignguestsTab generated by MyEclipse Persistence Tools
 */
public class SForeignguestsTab extends AbstractSForeignguestsTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SForeignguestsTab() {
	}

	/** minimal constructor */
	public SForeignguestsTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SForeignguestsTab(Integer id, Integer version, Integer tid,
			String fname, String translate, String position,
			String nationality, String passportno, String receiver,
			String duties) {
		super(id, version, tid, fname, translate, position, nationality,
				passportno, receiver, duties);
	}

}
