package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractASysconfigalterTab;

/**
 * ASysconfigalterTab generated by MyEclipse Persistence Tools
 */
public class ASysconfigalterTab extends AbstractASysconfigalterTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ASysconfigalterTab() {
	}

	/** minimal constructor */
	public ASysconfigalterTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public ASysconfigalterTab(Integer id, Integer version, String applicant,
			Integer applicantid, Date applydate, String devorsysname,
			String alterreason, String contentanalyze, String infordeptopinion,
			String infordeptsign, Integer infordeptsignid,
			Date infordeptsigndate, String securityopinion,
			String securitysign, Integer securityid, Date securitysigndate,
			String resultanalyze, String operatorsign, Integer operatorid,
			Date operatorsigndate) {
		super(id, version, applicant, applicantid, applydate, devorsysname,
				alterreason, contentanalyze, infordeptopinion, infordeptsign,
				infordeptsignid, infordeptsigndate, securityopinion,
				securitysign, securityid, securitysigndate, resultanalyze,
				operatorsign, operatorid, operatorsigndate);
	}

}
