package com.manage.temp.model.original;

import java.util.Date;

/**
 * AbstractAVideomeetingTab generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAVideomeetingTab implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer version;
	private String meetingname;
	private String applyorgname;
	private String applyorgid;
	private String applicant;
	private Integer applicantid;
	private String cellphone;
	private Integer meetingtype;
	private String meetingplace;
	private String meetingagenda;
	private String jingqu;
	private String jingwai;
	private Date meetingtime;
	private Date jointdebugtime;
	private Integer isppt;
	private Integer meetingmode;
	private String speakplace;
	private String deptopinion;
	private String deptsign;
	private String deptid;
	private Date deptsigndate;

	// Constructors

	/** default constructor */
	public AbstractAVideomeetingTab() {
	}

	/** minimal constructor */
	public AbstractAVideomeetingTab(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AbstractAVideomeetingTab(Integer id, Integer version,
			String meetingname, String applyorgname, String applyorgid,
			String applicant, Integer applicantid, String cellphone,
			Integer meetingtype, String meetingplace, String meetingagenda,
			String jingqu, String jingwai, Date meetingtime,
			Date jointdebugtime, Integer isppt, Integer meetingmode,
			String speakplace, String deptopinion, String deptsign,
			String deptid, Date deptsigndate) {
		this.id = id;
		this.version = version;
		this.meetingname = meetingname;
		this.applyorgname = applyorgname;
		this.applyorgid = applyorgid;
		this.applicant = applicant;
		this.applicantid = applicantid;
		this.cellphone = cellphone;
		this.meetingtype = meetingtype;
		this.meetingplace = meetingplace;
		this.meetingagenda = meetingagenda;
		this.jingqu = jingqu;
		this.jingwai = jingwai;
		this.meetingtime = meetingtime;
		this.jointdebugtime = jointdebugtime;
		this.isppt = isppt;
		this.meetingmode = meetingmode;
		this.speakplace = speakplace;
		this.deptopinion = deptopinion;
		this.deptsign = deptsign;
		this.deptid = deptid;
		this.deptsigndate = deptsigndate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getMeetingname() {
		return this.meetingname;
	}

	public void setMeetingname(String meetingname) {
		this.meetingname = meetingname;
	}

	public String getApplyorgname() {
		return this.applyorgname;
	}

	public void setApplyorgname(String applyorgname) {
		this.applyorgname = applyorgname;
	}

	public String getApplyorgid() {
		return this.applyorgid;
	}

	public void setApplyorgid(String applyorgid) {
		this.applyorgid = applyorgid;
	}

	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	public Integer getApplicantid() {
		return this.applicantid;
	}

	public void setApplicantid(Integer applicantid) {
		this.applicantid = applicantid;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public Integer getMeetingtype() {
		return this.meetingtype;
	}

	public void setMeetingtype(Integer meetingtype) {
		this.meetingtype = meetingtype;
	}

	public String getMeetingplace() {
		return this.meetingplace;
	}

	public void setMeetingplace(String meetingplace) {
		this.meetingplace = meetingplace;
	}

	public String getMeetingagenda() {
		return this.meetingagenda;
	}

	public void setMeetingagenda(String meetingagenda) {
		this.meetingagenda = meetingagenda;
	}

	public String getJingqu() {
		return this.jingqu;
	}

	public void setJingqu(String jingqu) {
		this.jingqu = jingqu;
	}

	public String getJingwai() {
		return this.jingwai;
	}

	public void setJingwai(String jingwai) {
		this.jingwai = jingwai;
	}

	public Date getMeetingtime() {
		return this.meetingtime;
	}

	public void setMeetingtime(Date meetingtime) {
		this.meetingtime = meetingtime;
	}

	public Date getJointdebugtime() {
		return this.jointdebugtime;
	}

	public void setJointdebugtime(Date jointdebugtime) {
		this.jointdebugtime = jointdebugtime;
	}

	public Integer getIsppt() {
		return this.isppt;
	}

	public void setIsppt(Integer isppt) {
		this.isppt = isppt;
	}

	public Integer getMeetingmode() {
		return this.meetingmode;
	}

	public void setMeetingmode(Integer meetingmode) {
		this.meetingmode = meetingmode;
	}

	public String getSpeakplace() {
		return this.speakplace;
	}

	public void setSpeakplace(String speakplace) {
		this.speakplace = speakplace;
	}

	public String getDeptopinion() {
		return this.deptopinion;
	}

	public void setDeptopinion(String deptopinion) {
		this.deptopinion = deptopinion;
	}

	public String getDeptsign() {
		return this.deptsign;
	}

	public void setDeptsign(String deptsign) {
		this.deptsign = deptsign;
	}

	public String getDeptid() {
		return this.deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public Date getDeptsigndate() {
		return this.deptsigndate;
	}

	public void setDeptsigndate(Date deptsigndate) {
		this.deptsigndate = deptsigndate;
	}

}