package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSEmployQualificationTab;

/**
 * SEmployQualificationTab generated by MyEclipse Persistence Tools
 */
public class SEmployQualificationTab extends AbstractSEmployQualificationTab
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public SEmployQualificationTab() {
	}

	/** minimal constructor */
	public SEmployQualificationTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SEmployQualificationTab(Integer id, Integer version, String ename,
			String fname, String national, Integer sex, String image,
			Date brithday, String location, String politicsstatus,
			String education, String professional, String title,
			String language, String abroadcountries, Date studytime,
			String studyway, String cardnum, String policestation,
			String passportno, String address, String zipcode, String ouname,
			String oposition, String classification, String newunit,
			String newposition, String newclassification,
			String democratic, String disciplinary, String otherdesc,
			Date signtime, String signname, Integer type,
			Date offthickstarttime, Date offthickendtime, String ounitdesc,
			String ounitsign, Integer ounitid, Date ounitsigndate,
			String departmentopinion, String departmentsign,
			Date departsigndate, Integer departid, String sofficedesc,
			String sofficesign, Date sofficesigndate, Integer sofficeid,
			String scomdesc, String scomsign, Integer scomid, Date scomdate) {
		super(id, version, ename, fname, national, sex, image, brithday,
				location, politicsstatus, education, professional, title,
				language, abroadcountries, studytime, studyway, cardnum,
				policestation, passportno, address, zipcode, ouname, oposition,
				classification, newunit, newposition, newclassification,
				scomdate, scomdate, democratic, disciplinary, otherdesc, scomsign, scomsign, scomsign, scomid, scomsign, scomsign, scomsign, scomsign, scomsign, scomsign, signtime, signname, type,
				offthickstarttime, offthickendtime, ounitdesc, ounitsign,
				ounitid, ounitsigndate, departmentopinion, departmentsign,
				departsigndate, departid, sofficedesc, sofficesign,
				sofficesigndate, sofficeid, scomdesc, scomsign, scomid,
				scomdate);
	}

}
