package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractSConfidentialityTab;

/**
 * SConfidentialityTab generated by MyEclipse Persistence Tools
 */
public class SConfidentialityTab extends AbstractSConfidentialityTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public SConfidentialityTab() {
	}

	/** minimal constructor */
	public SConfidentialityTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public SConfidentialityTab(Integer id, Integer version, String partya,
			String partyb, String paname, String pbname, Integer paid,
			Integer pbid, Date padate, Date pbdate) {
		super(id, version, partya, partyb, paname, pbname, paid, pbid, padate,
				pbdate);
	}

}
