package com.manage.meetsecrecyrecord.model;

import com.manage.meetsecrecyrecord.model.original.AbstractMeetSecrecyRecord;

/**
 * AVideomeetingTab generated by MyEclipse Persistence Tools
 */
public class MeetSecrecyRecord extends AbstractMeetSecrecyRecord {

}
