package com.manage.temp.model;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

import com.manage.temp.model.original.AbstractAWiresysrecordTab;

/**
 * AWiresysrecordTab generated by MyEclipse Persistence Tools
 */
public class AWiresysrecordTab extends AbstractAWiresysrecordTab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AWiresysrecordTab() {
	}

	/** minimal constructor */
	public AWiresysrecordTab(Integer id) {
		super(id);
	}

	/** full constructor */
	public AWiresysrecordTab(Integer id, Integer version, Date checkdate,
			String checkplace, String checkcondition, String checker,
			Integer checkerid, String remark) {
		super(id, version, checkdate, checkplace, checkcondition, checker,
				checkerid, remark);
	}

}
